%% HC-31 Batch 11O Stage B
% STRICT MOVEMENT-MATCH AND CONTROL-SEGMENT QC CORRECTION
%
% This script requires no raw CSC rereading. It reads the completed Stage B
% pair CSV and checkpoint MAT, removes fallback movement matches and six
% pathological control segments, then rebuilds summaries, statistics and PETHs.

clear; clc; close all; rehash;

[pairFile,pairFolder] = uigetfile('*.csv', ...
    'Select hc31_batch11O_awake_beta2_event_control_pairs.csv');
if isequal(pairFile,0), error('No pair CSV selected.'); end

[checkpointFile,checkpointFolder] = uigetfile('*.mat', ...
    'Select hc31_batch11O_awake_beta2_checkpoint.mat', ...
    pairFolder);
if isequal(checkpointFile,0), error('No checkpoint selected.'); end

Pairs = readtable(fullfile(pairFolder,pairFile), ...
    'TextType','string','VariableNamingRule','preserve');

% Empty CSV columns may be imported as numeric NaN rather than text.
% Convert failure-reason columns safely before using strlength.
if ismember('eventBeta2FailureReason', ...
        Pairs.Properties.VariableNames)
    if isnumeric(Pairs.eventBeta2FailureReason)
        eventFailureText = repmat("",height(Pairs),1);
        numericBad = isfinite(Pairs.eventBeta2FailureReason) & ...
            Pairs.eventBeta2FailureReason ~= 0;
        eventFailureText(numericBad) = ...
            string(Pairs.eventBeta2FailureReason(numericBad));
    else
        eventFailureText = ...
            strtrim(string(Pairs.eventBeta2FailureReason));
        eventFailureText(ismissing(eventFailureText)) = "";
    end
else
    eventFailureText = repmat("",height(Pairs),1);
end

if ismember('controlBeta2FailureReason', ...
        Pairs.Properties.VariableNames)
    if isnumeric(Pairs.controlBeta2FailureReason)
        controlFailureText = repmat("",height(Pairs),1);
        numericBad = isfinite(Pairs.controlBeta2FailureReason) & ...
            Pairs.controlBeta2FailureReason ~= 0;
        controlFailureText(numericBad) = ...
            string(Pairs.controlBeta2FailureReason(numericBad));
    else
        controlFailureText = ...
            strtrim(string(Pairs.controlBeta2FailureReason));
        controlFailureText(ismissing(controlFailureText)) = "";
    end
else
    controlFailureText = repmat("",height(Pairs),1);
end

% Store clean text copies for export, but calculate the QC mask from the
% local string arrays so it does not depend on MATLAB's table-variable type.
Pairs.eventBeta2FailureReasonText = eventFailureText;
Pairs.controlBeta2FailureReasonText = controlFailureText;

noEventBeta2Failure = ...
    eventFailureText == "" | ...
    ismissing(eventFailureText);

noControlBeta2Failure = ...
    controlFailureText == "" | ...
    ismissing(controlFailureText);

Loaded = load(fullfile(checkpointFolder,checkpointFile), ...
    'eventPethZ','controlPethZ');

eventPethZ = Loaded.eventPethZ;
controlPethZ = Loaded.controlPethZ;

if size(eventPethZ,1) ~= height(Pairs)
    error('Checkpoint PETH rows do not match the pair CSV.');
end

speedTolerance = 0.75;
accelerationTolerance = 1.5;
speedChangeTolerance = 1.0;

finiteMovement = ...
    isfinite(Pairs.eventSpeedAtPeakCmS) & ...
    isfinite(Pairs.eventAccelerationAtPeakCmS2) & ...
    isfinite(Pairs.eventSpeedChangeCmS) & ...
    isfinite(Pairs.controlSpeedAtPeakCmS) & ...
    isfinite(Pairs.controlAccelerationAtPeakCmS2) & ...
    isfinite(Pairs.controlSpeedChangeCmS);

Pairs.movementMatchPass = ...
    finiteMovement & ...
    abs(Pairs.eventSpeedAtPeakCmS- ...
        Pairs.controlSpeedAtPeakCmS) <= speedTolerance & ...
    abs(Pairs.eventAccelerationAtPeakCmS2- ...
        Pairs.controlAccelerationAtPeakCmS2) <= ...
        accelerationTolerance & ...
    abs(Pairs.eventSpeedChangeCmS- ...
        Pairs.controlSpeedChangeCmS) <= ...
        speedChangeTolerance & ...
    logical(Pairs.sustainedImmobility) == ...
        logical(Pairs.controlSustainedImmobility);

Pairs.controlSegmentQCPass = ...
    isfinite(Pairs.controlPeakEnvelopeZ) & ...
    Pairs.controlPeakEnvelopeZ <= 100 & ...
    abs(Pairs.controlPreMeanZ) <= 10 & ...
    abs(Pairs.controlCentralMeanZ) <= 10 & ...
    abs(Pairs.controlEarlyPostMeanZ) <= 10 & ...
    abs(Pairs.controlLatePostMeanZ) <= 10;

Pairs.eventSegmentQCPass = ...
    isfinite(Pairs.eventPeakEnvelopeZ) & ...
    Pairs.eventPeakEnvelopeZ <= 100 & ...
    abs(Pairs.eventPreMeanZ) <= 20 & ...
    abs(Pairs.eventCentralMeanZ) <= 20 & ...
    abs(Pairs.eventEarlyPostMeanZ) <= 20 & ...
    abs(Pairs.eventLatePostMeanZ) <= 20;

Pairs.pairQCPass = ...
    logical(Pairs.pairComplete) & ...
    noEventBeta2Failure & ...
    noControlBeta2Failure & ...
    Pairs.movementMatchPass & ...
    Pairs.controlSegmentQCPass & ...
    Pairs.eventSegmentQCPass;

Pairs.absoluteSpeedDifferenceCmS = ...
    abs(Pairs.eventSpeedAtPeakCmS- ...
    Pairs.controlSpeedAtPeakCmS);

Pairs.absoluteAccelerationDifferenceCmS2 = ...
    abs(Pairs.eventAccelerationAtPeakCmS2- ...
    Pairs.controlAccelerationAtPeakCmS2);

Pairs.absoluteSpeedChangeDifferenceCmS = ...
    abs(Pairs.eventSpeedChangeCmS- ...
    Pairs.controlSpeedChangeCmS);

[reuseGroup,~,~] = findgroups( ...
    string(Pairs.animal),Pairs.controlUs);

reuseCountsByGroup = splitapply( ...
    @numel,Pairs.controlUs,reuseGroup);

pairReuseCounts = nan(height(Pairs),1);

validReuseGroup = ...
    isfinite(reuseGroup) & ...
    reuseGroup >= 1 & ...
    reuseGroup <= numel(reuseCountsByGroup);

pairReuseCounts(validReuseGroup) = ...
    reuseCountsByGroup( ...
    reuseGroup(validReuseGroup));

Pairs.controlReuseCountAllPairs = ...
    pairReuseCounts;

Pairs.eventMinusControlPostMinusPreZ = ...
    Pairs.eventPostMinusPreZ- ...
    Pairs.controlPostMinusPreZ;

Pairs.eventMinusControlCentralMinusPreZ = ...
    Pairs.eventCentralMinusPreZ- ...
    Pairs.controlCentralMinusPreZ;

Pairs.eventMinusControlPostBurstCountChange = ...
    (Pairs.eventPostBurstCount-Pairs.eventPreBurstCount) - ...
    (Pairs.controlPostBurstCount-Pairs.controlPreBurstCount);

Pairs.eventMinusControlPostBurstFractionChange = ...
    (Pairs.eventPostBurstFraction-Pairs.eventPreBurstFraction) - ...
    (Pairs.controlPostBurstFraction-Pairs.controlPreBurstFraction);

outputFolder = fullfile(pairFolder, ...
    'hc31_batch11O_stageB_QC_corrected');
if ~exist(outputFolder,'dir'), mkdir(outputFolder); end
figureFolder = fullfile(outputFolder,'figures');
if ~exist(figureFolder,'dir'), mkdir(figureFolder); end

writetable(Pairs,fullfile(outputFolder, ...
    'hc31_batch11O_awake_beta2_event_control_pairs_QC_CORRECTED.csv'));

writetable(Pairs(~Pairs.controlSegmentQCPass,:), ...
    fullfile(outputFolder, ...
    'hc31_batch11O_pathological_control_segments.csv'));

setNames = ["TierA","TierAB","TierAC","TierABC"];
movementNames = [ ...
    "AllStrictMatched", ...
    "SustainedImmobility", ...
    "StableLowSpeed", ...
    "MovementIncrease"];

metricNames = { ...
    'eventPostMinusPreZ', ...
    'eventMinusControlPostMinusPreZ', ...
    'eventMinusControlCentralMinusPreZ', ...
    'eventMinusControlPostBurstCountChange', ...
    'eventMinusControlPostBurstFractionChange'};

animals = unique(Pairs.animal,'stable');
summaryRows = {};
pethRows = {};
pethCenters = -1.975:0.05:1.975;

for setIndex = 1:numel(setNames)
    setName = setNames(setIndex);
    if setName == "TierA"
        setMask = logical(Pairs.inSetTierA);
    elseif setName == "TierAB"
        setMask = logical(Pairs.inSetTierAB);
    elseif setName == "TierAC"
        setMask = logical(Pairs.inSetTierAC);
    else
        setMask = logical(Pairs.inSetTierABC);
    end

    for movementIndex = 1:numel(movementNames)
        movementName = movementNames(movementIndex);

        if movementName == "AllStrictMatched"
            movementMask = Pairs.pairQCPass;
        elseif movementName == "SustainedImmobility"
            movementMask = ...
                Pairs.pairQCPass & ...
                logical(Pairs.sustainedImmobility) & ...
                logical(Pairs.controlSustainedImmobility);
        elseif movementName == "StableLowSpeed"
            movementMask = ...
                Pairs.pairQCPass & ...
                Pairs.eventSpeedAtPeakCmS <= 5 & ...
                abs(Pairs.eventSpeedChangeCmS) <= 1 & ...
                abs(Pairs.controlSpeedChangeCmS) <= 1;
        else
            movementMask = ...
                Pairs.pairQCPass & ...
                logical(Pairs.movementIncrease);
        end

        animalEventPeth = [];
        animalControlPeth = [];
        pairCounts = [];

        for animalIndex = 1:numel(animals)
            animalID = animals(animalIndex);
            mask = ...
                setMask & movementMask & ...
                Pairs.animal == animalID;

            rows = find(mask);
            if isempty(rows), continue; end

            [controlGroup,~] = findgroups( ...
                Pairs.controlUs(rows));

            reuseCountByGroup = splitapply( ...
                @numel, ...
                Pairs.controlUs(rows), ...
                controlGroup);

            reuseCount = nan(numel(rows),1);

            validControlGroup = ...
                isfinite(controlGroup) & ...
                controlGroup >= 1 & ...
                controlGroup <= ...
                    numel(reuseCountByGroup);

            reuseCount(validControlGroup) = ...
                reuseCountByGroup( ...
                controlGroup(validControlGroup));

            weights = 1./reuseCount;

            validWeights = ...
                isfinite(weights) & weights > 0;

            if ~any(validWeights)
                continue
            end

            weights(~validWeights) = 0;
            weights = weights/sum(weights);

            row = { ...
                char(setName),char(movementName), ...
                char(animalID),numel(rows), ...
                numel(unique(Pairs.controlUs(rows)))};

            for metricIndex = 1:numel(metricNames)
                metricName = metricNames{metricIndex};
                values = Pairs.(metricName)(rows);
                row{end+1} = mean(values,'omitnan'); %#ok<SAGROW>
                row{end+1} = sum(weights.*values,'omitnan'); %#ok<SAGROW>
            end

            summaryRows(end+1,:) = row; %#ok<SAGROW>

            animalEventPeth(end+1,:) = ...
                sum(eventPethZ(rows,:).*weights,1,'omitnan'); %#ok<SAGROW>
            animalControlPeth(end+1,:) = ...
                sum(controlPethZ(rows,:).*weights,1,'omitnan'); %#ok<SAGROW>
            pairCounts(end+1,1) = numel(rows); %#ok<SAGROW>
        end

        if isempty(animalEventPeth), continue; end

        eventMean = mean(animalEventPeth,1,'omitnan');
        eventSem = std(animalEventPeth,0,1,'omitnan') / ...
            sqrt(size(animalEventPeth,1));
        controlMean = mean(animalControlPeth,1,'omitnan');
        controlSem = std(animalControlPeth,0,1,'omitnan') / ...
            sqrt(size(animalControlPeth,1));

        for binIndex = 1:numel(pethCenters)
            pethRows(end+1,:) = { ...
                char(setName),char(movementName), ...
                pethCenters(binIndex), ...
                eventMean(binIndex),eventSem(binIndex), ...
                controlMean(binIndex),controlSem(binIndex), ...
                size(animalEventPeth,1),sum(pairCounts)}; %#ok<SAGROW>
        end
    end
end

summaryNames = { ...
    'eventSet','movementGroup','animal','nPairs','nUniqueControls'};
for metricIndex = 1:numel(metricNames)
    summaryNames{end+1} = metricNames{metricIndex}; %#ok<SAGROW>
    summaryNames{end+1} = ...
        ['inverseControlReuseWeighted_' metricNames{metricIndex}]; %#ok<SAGROW>
end

AnimalSummary = cell2table(summaryRows, ...
    'VariableNames',summaryNames);

writetable(AnimalSummary,fullfile(outputFolder, ...
    'hc31_batch11O_awake_beta2_animal_summary_QC_CORRECTED.csv'));

PethSummary = cell2table(pethRows, ...
    'VariableNames', { ...
    'eventSet','movementGroup','timeFromEventSec', ...
    'meanEventBeta2EnvelopeZ','semEventBeta2EnvelopeZ', ...
    'meanControlBeta2EnvelopeZ','semControlBeta2EnvelopeZ', ...
    'nAnimals','nPairs'});

writetable(PethSummary,fullfile(outputFolder, ...
    'hc31_batch11O_awake_beta2_animal_weighted_PETH_QC_CORRECTED.csv'));

statRows = {};
for setIndex = 1:numel(setNames)
    for movementIndex = 1:numel(movementNames)
        mask = ...
            AnimalSummary.eventSet == setNames(setIndex) & ...
            AnimalSummary.movementGroup == movementNames(movementIndex);

        for metricIndex = 1:numel(metricNames)
            metricName = metricNames{metricIndex};
            columns = [ ...
                string(metricName), ...
                "inverseControlReuseWeighted_"+string(metricName)];

            for columnIndex = 1:numel(columns)
                values = ...
                    AnimalSummary.(columns(columnIndex))(mask);
                values = values(isfinite(values));
                pValue = NaN;
                signedRank = NaN;

                if numel(values) >= 3
                    try
                        [pValue,~,stats] = signrank(values,0);
                        signedRank = stats.signedrank;
                    catch
                    end
                end

                if columnIndex == 1
                    weighting = "Unweighted";
                else
                    weighting = "Inverse reuse weighted";
                end

                statRows(end+1,:) = { ...
                    char(setNames(setIndex)), ...
                    char(movementNames(movementIndex)), ...
                    metricName,char(weighting), ...
                    numel(values),mean(values,'omitnan'), ...
                    median(values,'omitnan'),pValue,signedRank}; %#ok<SAGROW>
            end
        end
    end
end

Statistics = cell2table(statRows, ...
    'VariableNames', { ...
    'eventSet','movementGroup','metric', ...
    'controlReuseWeighting','nAnimals', ...
    'meanEffect','medianEffect','pValue','signedRank'});

Statistics.qValueBH = ...
    hc31_batch11O_bh_fdr(Statistics.pValue);

writetable(Statistics,fullfile(outputFolder, ...
    'hc31_batch11O_awake_beta2_statistics_QC_CORRECTED.csv'));

plotMask = ...
    PethSummary.eventSet == "TierAC" & ...
    PethSummary.movementGroup == "SustainedImmobility";

fig = figure('Visible','off','Color','w', ...
    'Position',[80 80 1200 720]);
hold on
plot(PethSummary.timeFromEventSec(plotMask), ...
    PethSummary.meanEventBeta2EnvelopeZ(plotMask), ...
    'LineWidth',1.8);
plot(PethSummary.timeFromEventSec(plotMask), ...
    PethSummary.meanControlBeta2EnvelopeZ(plotMask), ...
    'LineWidth',1.8);
xline(0,'k--'); yline(0,':');
xlabel('Time from event or matched pseudo-time (s)');
ylabel('Local beta2 envelope robust z');
title('Tier A+C sustained immobility: QC-corrected beta2 PETH');
legend({'Event','Strict matched control'},'Location','best');
grid on; box off
exportgraphics(fig,fullfile(figureFolder, ...
    'batch11O_TierAC_sustained_immobility_beta2_PETH_QC_CORRECTED.png'), ...
    'Resolution',200);
close(fig);

QCSummary = table( ...
    height(Pairs), ...
    sum(Pairs.movementMatchPass), ...
    sum(~Pairs.movementMatchPass), ...
    sum(~Pairs.controlSegmentQCPass), ...
    sum(Pairs.pairQCPass), ...
    'VariableNames', { ...
    'nTotalPairs','nStrictMovementMatchPass', ...
    'nMovementMatchFail','nPathologicalControlSegments', ...
    'nFinalPairQCPass'});

writetable(QCSummary,fullfile(outputFolder, ...
    'hc31_batch11O_awake_beta2_pair_QC_summary.csv'));

fprintf('\nStage B QC correction complete.\n');
fprintf('Output folder:\n  %s\n',outputFolder);
fprintf('Final QC-passing pairs: %d / %d\n', ...
    sum(Pairs.pairQCPass),height(Pairs));
