%% HC-31 Batch 11M
% CORRECTED PRE / REST / POST OPERATIONAL BRAIN-STATE CLASSIFICATION
%
% Plain MATLAB script: no local functions.
% Intended to run using the HC-31 fileread/eval workaround.
%
% Purpose
% -------
% 1. Infer PRE, REST, and POST recording intervals from pooled spEpochSep
%    timestamps, following the existing HC-31 epoch map:
%       PRE = column 1, REST = column 3, POST = column 6.
% 2. Load the matching CSC LFP for each epoch.
% 3. Calculate windowed theta power, delta power, theta/delta ratio,
%    broadband RMS, and high-frequency power.
% 4. Assign cautious operational state labels:
%       - Putative NREM / slow-wave-like
%       - Theta-dominant / REM-like or quiet-wake-like
%       - Intermediate / unclassified
%       - Artefact / unusable
% 5. Annotate the existing candidate sleep/rest ripple table with the state
%    at each candidate peak.
% 6. Calculate candidate-event rates per state.
%
% IMPORTANT INTERPRETATION BOUNDARY
% ---------------------------------
% No EMG or formal manual sleep scoring is used here. Therefore:
% - "Putative NREM / slow-wave-like" is an LFP-defined operational label.
% - "Theta-dominant / REM-like or quiet-wake-like" cannot distinguish REM
%   from quiet wake using theta/delta alone.
% - These labels are state filters, not definitive sleep diagnoses.

clearvars -except scriptFile scriptFolder txt
clc
close all

fprintf('\nHC-31 Batch 11M3: corrected PRE/REST/POST operational state classification (CSC output fix)\n');
fprintf('----------------------------------------------------------------\n');

%% Corrected epoch mapping rationale
% Batch 11M2 showed that spEpochSep contains four columns in all five
% analysed animals. The HC-31 example script explicitly uses column 2 for
% Run1. PRE candidate ranges overlap column 1 and REST candidate ranges
% overlap column 3. Therefore the four-column processed mapping is:
%   column 1 = PRE
%   column 2 = Run1
%   column 3 = REST
%   column 4 = POST
%
% Column 4 is fully covered by the selected CSC file for every animal.
% This script does not use the previous invalid POST mapping.

%% User settings

defaultRoot = getenv('HC31_DATA_ROOT');

animalIndices = 5:9;
fallbackAnimalIDs = { ...
    'ANM00190422', ...
    'ANM204878', ...
    'ANM212379', ...
    'ANM228899', ...
    'ANM228900'};

epochNames = {'PRE','REST','POST'};
epochColumns = [1 3 4];

preferredChannels = { ...
    'CSC33', ...
    'CSC33', ...
    'CSC53', ...
    'CSC45', ...
    'CSC45'};

% LFP processing.
targetFs = 250;
chunkLengthSec = 120;
chunkPaddingSec = 5;
maxEpochDurationMin = 90;
minPooledSpikesForEpoch = 20;

% Spectral bands.
deltaBandHz = [1 4];
thetaBandHz = [6 10];
highFrequencyControlBandHz = [70 110];
filterOrder = 4;

% Windowing.
stateWindowSec = 2;
stateStepSec = 1;
minimumWindowCoverage = 0.90;
thetaDeltaSmoothWindows = 5;

% Operational classification thresholds in robust-z units.
thetaDeltaStateThresholdZ = 0.50;
supportingBandMinimumZ = -0.50;
artefactThresholdZ = 6.0;

% Candidate-to-state matching.
maximumCandidateWindowDistanceSec = 2.0;

% Rendering.
saveDpi = 190;

%% Locate dataset root

if exist(defaultRoot, 'dir') == 7
    rootDir = defaultRoot;
else
    rootDir = uigetdir(pwd, ...
        'Select the HC-31 root folder containing resSave.mat');
    if isequal(rootDir, 0)
        error('No dataset root selected.');
    end
end

if exist(fullfile(rootDir, 'resSave.mat'), 'file') ~= 2
    [matFile, matFolder] = uigetfile('*.mat', 'Select resSave.mat');
    if isequal(matFile, 0)
        error('No resSave.mat selected.');
    end
    rootDir = matFolder;
end

fprintf('Dataset root:\n  %s\n', rootDir);

%% Add Neuralynx importer

if exist(fullfile(rootDir, 'neuralynximport'), 'dir') == 7
    addpath(genpath(fullfile(rootDir, 'neuralynximport')));
end

if exist(fullfile(rootDir, 'neuralynximport', 'nlximport'), 'dir') == 7
    addpath(genpath(fullfile(rootDir, 'neuralynximport', 'nlximport')));
end

if exist('Nlx2MatCSC', 'file') ~= 3 && ...
        exist('Nlx2MatCSC', 'file') ~= 2
    error(['MATLAB cannot find Nlx2MatCSC. ', ...
        'Add neuralynximport to the MATLAB path and rerun.']);
end

%% Load resSave

S = load(fullfile(rootDir, 'resSave.mat'));

if ~isfield(S, 'resSave')
    error('The selected MAT file does not contain resSave.');
end

resSave = S.resSave;

%% Select existing sleep/rest candidate-event table

candidateCsv = '';

candidatePaths = { ...
    fullfile(rootDir, ...
        'hc31_batch10_sleep_replay_memory_link_FORCE_V2', ...
        'hc31_batch10_candidate_sleep_ripples.csv'), ...
    fullfile(rootDir, ...
        'allresults', ...
        'hc31_batch10_sleep_replay_memory_link_FORCE_V2', ...
        'hc31_batch10_candidate_sleep_ripples.csv'), ...
    fullfile(rootDir, ...
        'hc31_batch10_sleep_replay_memory_link_FORCE', ...
        'hc31_batch10_candidate_sleep_ripples.csv'), ...
    fullfile(rootDir, ...
        'allresults', ...
        'hc31_batch10_sleep_replay_memory_link_FORCE', ...
        'hc31_batch10_candidate_sleep_ripples.csv'), ...
    fullfile(rootDir, ...
        'hc31_batch10_candidate_sleep_ripples.csv')};

for q = 1:numel(candidatePaths)
    if exist(candidatePaths{q}, 'file') == 2
        candidateCsv = candidatePaths{q};
        break
    end
end

if isempty(candidateCsv)
    [f,p] = uigetfile( ...
        '*.csv', ...
        'Select hc31_batch10_candidate_sleep_ripples.csv');

    if isequal(f, 0)
        error(['No sleep/rest candidate-event table selected. ', ...
            'Batch 11M requires this table for event-state annotation.']);
    end

    candidateCsv = fullfile(p,f);
end

CandidateRaw = readtable( ...
    candidateCsv, ...
    'TextType', 'string', ...
    'VariableNamingRule', 'preserve');

fprintf('Candidate event table:\n  %s\n', candidateCsv);

%% Standardise candidate-event columns

candidateVars = CandidateRaw.Properties.VariableNames;
candidateVarsLower = lower(candidateVars);

animalCol = '';
animalCandidates = {'animal','animalid','animal_id','rat','subject'};
for q = 1:numel(animalCandidates)
    hit = find(strcmp(candidateVarsLower, lower(animalCandidates{q})), 1);
    if ~isempty(hit)
        animalCol = candidateVars{hit};
        break
    end
end

epochCol = '';
epochCandidates = {'epochname','epoch','epoch_name','state','session'};
for q = 1:numel(epochCandidates)
    hit = find(strcmp(candidateVarsLower, lower(epochCandidates{q})), 1);
    if ~isempty(hit)
        epochCol = candidateVars{hit};
        break
    end
end

peakCol = '';
peakCandidates = { ...
    'peakus', ...
    'ripplepeakus', ...
    'eventpeakus', ...
    'peaktimeus', ...
    'peak_time_us'};
for q = 1:numel(peakCandidates)
    hit = find(strcmp(candidateVarsLower, lower(peakCandidates{q})), 1);
    if ~isempty(hit)
        peakCol = candidateVars{hit};
        break
    end
end

startCol = '';
startCandidates = { ...
    'startus', ...
    'ripplestartus', ...
    'eventstartus', ...
    'starttimeus', ...
    'start_time_us'};
for q = 1:numel(startCandidates)
    hit = find(strcmp(candidateVarsLower, lower(startCandidates{q})), 1);
    if ~isempty(hit)
        startCol = candidateVars{hit};
        break
    end
end

endCol = '';
endCandidates = { ...
    'endus', ...
    'rippleendus', ...
    'eventendus', ...
    'endtimeus', ...
    'end_time_us'};
for q = 1:numel(endCandidates)
    hit = find(strcmp(candidateVarsLower, lower(endCandidates{q})), 1);
    if ~isempty(hit)
        endCol = candidateVars{hit};
        break
    end
end

artifactCol = '';
artifactCandidates = { ...
    'isartifactlike', ...
    'excludedasartifact', ...
    'isartifact', ...
    'artifactlike', ...
    'isartefactlike', ...
    'excludedasartefact'};
for q = 1:numel(artifactCandidates)
    hit = find(strcmp(candidateVarsLower, lower(artifactCandidates{q})), 1);
    if ~isempty(hit)
        artifactCol = candidateVars{hit};
        break
    end
end

if isempty(animalCol) || isempty(epochCol) || isempty(peakCol)
    fprintf('Available candidate-table columns:\n');
    disp(candidateVars');
    error(['Could not identify animal, epoch, and peak-time columns ', ...
        'in the candidate-event table.']);
end

Candidate = table();
Candidate.sourceRow = (1:height(CandidateRaw))';

Candidate.animal = string(CandidateRaw.(animalCol));
Candidate.animal = strtrim(Candidate.animal);

rawEpoch = lower(strtrim(string(CandidateRaw.(epochCol))));
Candidate.epoch = repmat("", height(CandidateRaw), 1);

Candidate.epoch(contains(rawEpoch, 'pre')) = "PRE";
Candidate.epoch(contains(rawEpoch, 'rest')) = "REST";
Candidate.epoch(contains(rawEpoch, 'post')) = "POST";

Candidate.peakUs = double(CandidateRaw.(peakCol));

if median(abs(Candidate.peakUs), 'omitnan') < 1e6
    Candidate.peakUs = Candidate.peakUs .* 1e6;
end

if ~isempty(startCol)
    Candidate.startUs = double(CandidateRaw.(startCol));
    if median(abs(Candidate.startUs), 'omitnan') < 1e6
        Candidate.startUs = Candidate.startUs .* 1e6;
    end
else
    Candidate.startUs = Candidate.peakUs - 0.050e6;
end

if ~isempty(endCol)
    Candidate.endUs = double(CandidateRaw.(endCol));
    if median(abs(Candidate.endUs), 'omitnan') < 1e6
        Candidate.endUs = Candidate.endUs .* 1e6;
    end
else
    Candidate.endUs = Candidate.peakUs + 0.050e6;
end

Candidate.currentArtifactFlag = false(height(CandidateRaw), 1);

if ~isempty(artifactCol)
    rawArtifact = CandidateRaw.(artifactCol);

    if islogical(rawArtifact)
        Candidate.currentArtifactFlag = rawArtifact;
    elseif isnumeric(rawArtifact)
        Candidate.currentArtifactFlag = rawArtifact ~= 0;
    else
        rawArtifactString = lower(strtrim(string(rawArtifact)));
        Candidate.currentArtifactFlag = ...
            rawArtifactString == "true" | ...
            rawArtifactString == "1" | ...
            rawArtifactString == "yes" | ...
            rawArtifactString == "y";
    end
end

Candidate = Candidate( ...
    Candidate.epoch ~= "" & ...
    isfinite(Candidate.peakUs), :);

%% Output folder

outputFolder = fullfile(rootDir, ...
    'hc31_batch11M3_corrected_pre_rest_post_state_classification');

if ~exist(outputFolder, 'dir')
    mkdir(outputFolder);
end

figureFolder = fullfile(outputFolder, 'figures');

if ~exist(figureFolder, 'dir')
    mkdir(figureFolder);
end

%% Resolve animal names from resSave

animalMapNames = string(fallbackAnimalIDs(:));
animalMapIndices = animalIndices(:);

for ai = 1:numel(animalIndices)
    idx = animalIndices(ai);

    if idx > numel(resSave)
        continue
    end

    R = resSave(idx);
    resolvedName = animalMapNames(ai);

    try
        if isfield(R, 'spAll') && ...
                ~isempty(R.spAll) && ...
                isfield(R.spAll, 'animal')
            resolvedName = strtrim(string(R.spAll(1).animal));
        elseif isfield(R, 'animal')
            resolvedName = strtrim(string(R.animal));
        elseif isfield(R, 'name')
            resolvedName = strtrim(string(R.name));
        end
    catch
    end

    animalMapNames(ai) = resolvedName;
end

%% Find candidate CSC files and read coverage

allNcs = dir(fullfile(rootDir, 'csc_files', '**', '*.ncs'));

if isempty(allNcs)
    allNcs = dir(fullfile(rootDir, '**', '*.ncs'));
end

if isempty(allNcs)
    error('No Neuralynx .ncs files were found under the dataset root.');
end

coverageRows = {};

for ai = 1:numel(animalIndices)
    animalID = animalMapNames(ai);
    preferredChannel = preferredChannels{ai};

    matchingIndices = [];

    for ff = 1:numel(allNcs)
        thisPath = fullfile(allNcs(ff).folder, allNcs(ff).name);

        if contains(lower(thisPath), lower(char(animalID))) && ...
                contains(lower(allNcs(ff).name), lower(preferredChannel))
            matchingIndices(end+1) = ff; %#ok<SAGROW>
        end
    end

    if isempty(matchingIndices)
        for ff = 1:numel(allNcs)
            thisPath = fullfile(allNcs(ff).folder, allNcs(ff).name);

            if contains(lower(thisPath), lower(char(animalID)))
                matchingIndices(end+1) = ff; %#ok<SAGROW>
            end
        end
    end

    for mm = 1:numel(matchingIndices)
        ff = matchingIndices(mm);
        cscPath = fullfile(allNcs(ff).folder, allNcs(ff).name);

        coverageStartUs = NaN;
        coverageEndUs = NaN;
        coverageReadable = false;

        try
            coverageTs = Nlx2MatCSC( ...
                cscPath, ...
                [1 0 0 0 0], ...
                0, ...
                1, ...
                []);

            coverageTs = double(coverageTs(:));
            coverageTs = coverageTs(isfinite(coverageTs));

            if ~isempty(coverageTs)
                coverageStartUs = min(coverageTs);
                coverageEndUs = max(coverageTs);
                coverageReadable = coverageEndUs > coverageStartUs;
            end
        catch
            coverageReadable = false;
        end

        coverageRows(end+1,:) = { ...
            char(animalID), ...
            animalIndices(ai), ...
            preferredChannel, ...
            cscPath, ...
            coverageStartUs, ...
            coverageEndUs, ...
            coverageReadable}; %#ok<SAGROW>
    end
end

Coverage = cell2table(coverageRows, ...
    'VariableNames', { ...
        'animal', ...
        'resSaveIndex', ...
        'preferredChannel', ...
        'cscPath', ...
        'coverageStartUs', ...
        'coverageEndUs', ...
        'coverageReadable'});

writetable(Coverage, fullfile(outputFolder, ...
    'hc31_batch11M3_csc_coverage.csv'));

%% Infer epoch intervals from pooled spEpochSep timestamps

epochRows = {};

for ai = 1:numel(animalIndices)
    resIdx = animalIndices(ai);

    if resIdx > numel(resSave)
        continue
    end

    R = resSave(resIdx);
    animalID = animalMapNames(ai);

    if ~isfield(R, 'spEpochSep') || isempty(R.spEpochSep)
        for ep = 1:numel(epochNames)
            epochRows(end+1,:) = { ...
                char(animalID), ...
                resIdx, ...
                epochNames{ep}, ...
                epochColumns(ep), ...
                NaN, ...
                NaN, ...
                NaN, ...
                0, ...
                false, ...
                '', ...
                NaN}; %#ok<SAGROW>
        end
        continue
    end

    nEpochColumns = size(R.spEpochSep, 2);

    for ep = 1:numel(epochNames)
        epochName = epochNames{ep};
        epochColumn = epochColumns(ep);

        pooledSpikes = [];

        if epochColumn <= nEpochColumns
            for uu = 1:size(R.spEpochSep, 1)
                spikeTimes = [];

                try
                    if isfield(R.spEpochSep, 'timeStamps')
                        spikeTimes = double( ...
                            R.spEpochSep(uu, epochColumn).timeStamps(:));
                    elseif isfield(R.spEpochSep, 'timestamps')
                        spikeTimes = double( ...
                            R.spEpochSep(uu, epochColumn).timestamps(:));
                    elseif isfield(R.spEpochSep, 'times')
                        spikeTimes = double( ...
                            R.spEpochSep(uu, epochColumn).times(:));
                    elseif isfield(R.spEpochSep, 'time')
                        spikeTimes = double( ...
                            R.spEpochSep(uu, epochColumn).time(:));
                    end
                catch
                    spikeTimes = [];
                end

                spikeTimes = spikeTimes(isfinite(spikeTimes));

                if ~isempty(spikeTimes) && ...
                        median(abs(spikeTimes), 'omitnan') < 1e6
                    spikeTimes = spikeTimes .* 1e6;
                end

                pooledSpikes = [pooledSpikes; spikeTimes(:)]; %#ok<AGROW>
            end
        end

        pooledSpikes = pooledSpikes(isfinite(pooledSpikes));

        epochStartUs = NaN;
        epochEndUs = NaN;
        usableEpoch = false;

        if numel(pooledSpikes) >= minPooledSpikesForEpoch
            epochStartUs = min(pooledSpikes);
            epochEndUs = max(pooledSpikes);
            usableEpoch = epochEndUs > epochStartUs;
        end

        % Extend interval to include all existing candidate events assigned
        % to this animal and epoch.
        candidateMask = ...
            Candidate.animal == animalID & ...
            Candidate.epoch == string(epochName);

        if any(candidateMask)
            candidateMinimum = min( ...
                Candidate.startUs(candidateMask), ...
                [], ...
                'omitnan');

            candidateMaximum = max( ...
                Candidate.endUs(candidateMask), ...
                [], ...
                'omitnan');

            if isfinite(candidateMinimum) && isfinite(candidateMaximum)
                if ~isfinite(epochStartUs)
                    epochStartUs = candidateMinimum;
                else
                    epochStartUs = min(epochStartUs, candidateMinimum);
                end

                if ~isfinite(epochEndUs)
                    epochEndUs = candidateMaximum;
                else
                    epochEndUs = max(epochEndUs, candidateMaximum);
                end

                usableEpoch = epochEndUs > epochStartUs;
            end
        end

        if usableEpoch && isfinite(maxEpochDurationMin)
            maximumDurationUs = maxEpochDurationMin * 60 * 1e6;

            if epochEndUs - epochStartUs > maximumDurationUs
                warning([ ...
                    '%s %s interval exceeded %.1f minutes. ', ...
                    'Trimming to the first %.1f minutes.'], ...
                    animalID, ...
                    epochName, ...
                    maxEpochDurationMin, ...
                    maxEpochDurationMin);

                epochEndUs = epochStartUs + maximumDurationUs;
            end
        end

        selectedCscPath = '';
        overlapSec = 0;

        coverageMask = ...
            string(Coverage.animal) == animalID & ...
            Coverage.coverageReadable;

        candidateCoverageRows = find(coverageMask);
        bestOverlapUs = -Inf;

        for cc = 1:numel(candidateCoverageRows)
            coverageRow = candidateCoverageRows(cc);

            overlapUs = max(0, ...
                min(epochEndUs, Coverage.coverageEndUs(coverageRow)) - ...
                max(epochStartUs, Coverage.coverageStartUs(coverageRow)));

            if overlapUs > bestOverlapUs
                bestOverlapUs = overlapUs;
                selectedCscPath = Coverage.cscPath{coverageRow};
                overlapSec = overlapUs / 1e6;
            end
        end

        if isempty(selectedCscPath) || overlapSec <= 0
            usableEpoch = false;
        end

        epochDurationSec = NaN;

        if isfinite(epochStartUs) && isfinite(epochEndUs)
            epochDurationSec = ...
                (epochEndUs - epochStartUs) / 1e6;
        end

        epochRows(end+1,:) = { ...
            char(animalID), ...
            resIdx, ...
            epochName, ...
            epochColumn, ...
            epochStartUs, ...
            epochEndUs, ...
            epochDurationSec, ...
            numel(pooledSpikes), ...
            usableEpoch, ...
            selectedCscPath, ...
            overlapSec}; %#ok<SAGROW>
    end
end

EpochInventory = cell2table(epochRows, ...
    'VariableNames', { ...
        'animal', ...
        'resSaveIndex', ...
        'epoch', ...
        'spEpochSepColumn', ...
        'epochStartUs', ...
        'epochEndUs', ...
        'epochDurationSec', ...
        'nPooledSpikes', ...
        'isUsable', ...
        'cscPath', ...
        'cscOverlapSec'});

writetable(EpochInventory, fullfile(outputFolder, ...
    'hc31_batch11M3_epoch_inventory.csv'));

%% Process full epochs into state windows

windowRows = {};
failureRows = {};

for er = 1:height(EpochInventory)
    if ~EpochInventory.isUsable(er)
        failureRows(end+1,:) = { ...
            EpochInventory.animal{er}, ...
            EpochInventory.epoch{er}, ...
            'Epoch interval or CSC coverage was unusable.'}; %#ok<SAGROW>
        continue
    end

    animalID = string(EpochInventory.animal{er});
    epochName = string(EpochInventory.epoch{er});
    epochStartUs = EpochInventory.epochStartUs(er);
    epochEndUs = EpochInventory.epochEndUs(er);
    cscPath = EpochInventory.cscPath{er};

    fprintf('\n%s %s\n', animalID, epochName);
    fprintf('  Loading %.2f minutes from:\n  %s\n', ...
        (epochEndUs - epochStartUs) / 1e6 / 60, ...
        cscPath);

    allTimeUs = [];
    allLfp = [];
    actualFs = NaN;

    currentChunkStartUs = epochStartUs;

    while currentChunkStartUs < epochEndUs
        currentChunkEndUs = min( ...
            epochEndUs, ...
            currentChunkStartUs + chunkLengthSec * 1e6);

        loadStartUs = max( ...
            epochStartUs, ...
            currentChunkStartUs - chunkPaddingSec * 1e6);

        loadEndUs = min( ...
            epochEndUs, ...
            currentChunkEndUs + chunkPaddingSec * 1e6);

        try
            % Field selection [1 0 1 1 1] requests four data fields:
            % timestamps, sample frequencies, valid-sample counts and
            % samples. ExtractHeader = 1 adds the header as the fifth
            % output. Do not include a placeholder for channel numbers,
            % because that field is not selected.
            [recordTimestamps, sampleFrequencies, ...
                nValidSamples, samples, header] = ...
                Nlx2MatCSC( ...
                    cscPath, ...
                    [1 0 1 1 1], ...
                    1, ...
                    4, ...
                    [loadStartUs loadEndUs]);
        catch ME
            failureRows(end+1,:) = { ...
                char(animalID), ...
                char(epochName), ...
                ['Interval load failed: ' ME.message]}; %#ok<SAGROW>

            recordTimestamps = [];
            sampleFrequencies = [];
            nValidSamples = [];
            samples = [];
            header = {};
        end

        if ~isempty(recordTimestamps) && ~isempty(samples)
            rawFs = median( ...
                double(sampleFrequencies(:)), ...
                'omitnan');

            if ~isfinite(rawFs) || rawFs <= 0
                rawFs = 32551.34;
            end

            adBitVolts = 1;

            for hh = 1:numel(header)
                headerLine = string(header{hh});

                if contains( ...
                        headerLine, ...
                        'ADBitVolts', ...
                        'IgnoreCase', ...
                        true)

                    numericTokens = regexp( ...
                        char(headerLine), ...
                        '[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?', ...
                        'match');

                    if ~isempty(numericTokens)
                        candidateScale = ...
                            str2double(numericTokens{end});

                        if isfinite(candidateScale) && candidateScale > 0
                            adBitVolts = candidateScale;
                        end
                    end
                end
            end

            rawTimeCell = cell(numel(recordTimestamps), 1);
            rawLfpCell = cell(numel(recordTimestamps), 1);
            dtUs = 1e6 / rawFs;

            for rr = 1:numel(recordTimestamps)
                validCount = 512;

                if ~isempty(nValidSamples)
                    validCount = min( ...
                        512, ...
                        double(nValidSamples(rr)));
                end

                if validCount <= 0
                    continue
                end

                rawTimeCell{rr} = ...
                    double(recordTimestamps(rr)) + ...
                    (0:validCount-1)' .* dtUs;

                rawLfpCell{rr} = ...
                    double(samples(1:validCount, rr)) .* ...
                    adBitVolts .* 1e6;
            end

            rawTimeUs = vertcat(rawTimeCell{:});
            rawLfpUv = vertcat(rawLfpCell{:});

            validRaw = ...
                isfinite(rawTimeUs) & ...
                isfinite(rawLfpUv) & ...
                rawTimeUs >= loadStartUs & ...
                rawTimeUs <= loadEndUs;

            rawTimeUs = rawTimeUs(validRaw);
            rawLfpUv = rawLfpUv(validRaw);

            [rawTimeUs, sortOrder] = sort(rawTimeUs);
            rawLfpUv = rawLfpUv(sortOrder);

            [rawTimeUs, uniqueIndices] = ...
                unique(rawTimeUs, 'stable');

            rawLfpUv = rawLfpUv(uniqueIndices);

            if numel(rawLfpUv) > 20
                rawLfpUv = ...
                    rawLfpUv - median(rawLfpUv, 'omitnan');

                downsampleFactor = ...
                    max(1, round(rawFs / targetFs));

                actualFs = rawFs / downsampleFactor;

                if downsampleFactor > 1
                    try
                        downsampledLfp = ...
                            decimate(rawLfpUv, downsampleFactor);

                        downsampledTimeUs = linspace( ...
                            rawTimeUs(1), ...
                            rawTimeUs(end), ...
                            numel(downsampledLfp))';
                    catch
                        downsampledLfp = ...
                            rawLfpUv(1:downsampleFactor:end);

                        downsampledTimeUs = ...
                            rawTimeUs(1:downsampleFactor:end);
                    end
                else
                    downsampledLfp = rawLfpUv;
                    downsampledTimeUs = rawTimeUs;
                end

                centralKeep = ...
                    downsampledTimeUs >= currentChunkStartUs & ...
                    downsampledTimeUs < currentChunkEndUs;

                if currentChunkEndUs >= epochEndUs
                    centralKeep = ...
                        downsampledTimeUs >= currentChunkStartUs & ...
                        downsampledTimeUs <= currentChunkEndUs;
                end

                downsampledTimeUs = ...
                    downsampledTimeUs(centralKeep);

                downsampledLfp = ...
                    downsampledLfp(centralKeep);

                if ~isempty(downsampledTimeUs)
                    if isempty(allTimeUs)
                        allTimeUs = downsampledTimeUs(:);
                        allLfp = downsampledLfp(:);
                    else
                        keepNew = ...
                            downsampledTimeUs(:) > allTimeUs(end);

                        allTimeUs = [ ...
                            allTimeUs; ...
                            downsampledTimeUs(keepNew)]; %#ok<AGROW>

                        allLfp = [ ...
                            allLfp; ...
                            downsampledLfp(keepNew)]; %#ok<AGROW>
                    end
                end
            end
        end

        currentChunkStartUs = currentChunkEndUs;
    end

    if isempty(allTimeUs) || numel(allTimeUs) < round(targetFs * 10)
        failureRows(end+1,:) = { ...
            char(animalID), ...
            char(epochName), ...
            'Insufficient downsampled LFP after interval loading.'}; %#ok<SAGROW>
        continue
    end

    if ~isfinite(actualFs)
        actualFs = 1e6 / median(diff(allTimeUs), 'omitnan');
    end

    % Identify continuous segments so filters are not applied across gaps.
    gapThresholdUs = max(0.050e6, 5 * 1e6 / actualFs);
    gapIndices = find(diff(allTimeUs) > gapThresholdUs);

    segmentStarts = [1; gapIndices + 1];
    segmentEnds = [gapIndices; numel(allTimeUs)];

    thetaFiltered = nan(size(allLfp));
    deltaFiltered = nan(size(allLfp));
    highFrequencyFiltered = nan(size(allLfp));

    nyquistHz = actualFs / 2;

    if thetaBandHz(2) >= nyquistHz || ...
            deltaBandHz(2) >= nyquistHz || ...
            highFrequencyControlBandHz(2) >= nyquistHz
        error(['Target sampling rate is too low for one of the ', ...
            'configured filter bands.']);
    end

    [bTheta, aTheta] = butter( ...
        filterOrder, ...
        thetaBandHz / nyquistHz, ...
        'bandpass');

    [bDelta, aDelta] = butter( ...
        filterOrder, ...
        deltaBandHz / nyquistHz, ...
        'bandpass');

    [bHigh, aHigh] = butter( ...
        filterOrder, ...
        highFrequencyControlBandHz / nyquistHz, ...
        'bandpass');

    minimumFilterSamples = round(actualFs * 10);

    for ss = 1:numel(segmentStarts)
        segmentIndices = ...
            segmentStarts(ss):segmentEnds(ss);

        if numel(segmentIndices) < minimumFilterSamples
            continue
        end

        segmentLfp = double(allLfp(segmentIndices));

        segmentLfp = ...
            segmentLfp - median(segmentLfp, 'omitnan');

        try
            thetaFiltered(segmentIndices) = ...
                filtfilt(bTheta, aTheta, segmentLfp);

            deltaFiltered(segmentIndices) = ...
                filtfilt(bDelta, aDelta, segmentLfp);

            highFrequencyFiltered(segmentIndices) = ...
                filtfilt(bHigh, aHigh, segmentLfp);
        catch ME
            failureRows(end+1,:) = { ...
                char(animalID), ...
                char(epochName), ...
                ['Filtering failed in one segment: ' ME.message]}; %#ok<SAGROW>
        end
    end

    windowSamples = round(stateWindowSec * actualFs);
    stepSamples = round(stateStepSec * actualFs);
    epochWindowIndex = 0;

    for ss = 1:numel(segmentStarts)
        segmentStartIndex = segmentStarts(ss);
        segmentEndIndex = segmentEnds(ss);

        if segmentEndIndex - segmentStartIndex + 1 < windowSamples
            continue
        end

        firstWindowStart = segmentStartIndex;
        finalWindowStart = segmentEndIndex - windowSamples + 1;

        for windowStartIndex = ...
                firstWindowStart:stepSamples:finalWindowStart

            windowEndIndex = ...
                windowStartIndex + windowSamples - 1;

            windowIndices = ...
                windowStartIndex:windowEndIndex;

            epochWindowIndex = epochWindowIndex + 1;

            finiteMask = ...
                isfinite(allLfp(windowIndices)) & ...
                isfinite(thetaFiltered(windowIndices)) & ...
                isfinite(deltaFiltered(windowIndices)) & ...
                isfinite(highFrequencyFiltered(windowIndices));

            coverageFraction = mean(finiteMask);

            thetaPower = NaN;
            deltaPower = NaN;
            highFrequencyPower = NaN;
            rawRms = NaN;
            logThetaDelta = NaN;

            if coverageFraction >= minimumWindowCoverage
                thetaValues = ...
                    thetaFiltered(windowIndices);

                deltaValues = ...
                    deltaFiltered(windowIndices);

                highValues = ...
                    highFrequencyFiltered(windowIndices);

                rawValues = allLfp(windowIndices);

                thetaPower = ...
                    mean(thetaValues(finiteMask).^2, 'omitnan');

                deltaPower = ...
                    mean(deltaValues(finiteMask).^2, 'omitnan');

                highFrequencyPower = ...
                    mean(highValues(finiteMask).^2, 'omitnan');

                rawRms = sqrt( ...
                    mean(rawValues(finiteMask).^2, 'omitnan'));

                logThetaDelta = log10( ...
                    (thetaPower + eps) / ...
                    (deltaPower + eps));
            end

            windowRows(end+1,:) = { ...
                char(animalID), ...
                EpochInventory.resSaveIndex(er), ...
                char(epochName), ...
                epochWindowIndex, ...
                ss, ...
                allTimeUs(windowStartIndex), ...
                allTimeUs(windowEndIndex), ...
                mean([ ...
                    allTimeUs(windowStartIndex), ...
                    allTimeUs(windowEndIndex)]), ...
                stateWindowSec, ...
                coverageFraction, ...
                thetaPower, ...
                deltaPower, ...
                highFrequencyPower, ...
                rawRms, ...
                logThetaDelta, ...
                actualFs}; %#ok<SAGROW>
        end
    end
end

if isempty(windowRows)
    error('No valid state windows were generated.');
end

StateWindows = cell2table(windowRows, ...
    'VariableNames', { ...
        'animal', ...
        'resSaveIndex', ...
        'epoch', ...
        'epochWindowIndex', ...
        'continuousSegmentIndex', ...
        'windowStartUs', ...
        'windowEndUs', ...
        'windowCenterUs', ...
        'windowDurationSec', ...
        'coverageFraction', ...
        'thetaPower', ...
        'deltaPower', ...
        'highFrequencyPower', ...
        'rawRmsUv', ...
        'log10ThetaDelta', ...
        'effectiveSamplingRateHz'});

StateWindows.animal = string(StateWindows.animal);
StateWindows.epoch = string(StateWindows.epoch);

%% Smooth theta/delta within each animal and epoch

StateWindows.smoothedLog10ThetaDelta = ...
    StateWindows.log10ThetaDelta;

for ai = 1:numel(animalMapNames)
    for ep = 1:numel(epochNames)
        stateMask = ...
            StateWindows.animal == animalMapNames(ai) & ...
            StateWindows.epoch == string(epochNames{ep});

        stateRows = find(stateMask);

        if isempty(stateRows)
            continue
        end

        [~, orderWithinEpoch] = sort( ...
            StateWindows.windowCenterUs(stateRows));

        orderedRows = stateRows(orderWithinEpoch);

        StateWindows.smoothedLog10ThetaDelta(orderedRows) = ...
            movmedian( ...
                StateWindows.log10ThetaDelta(orderedRows), ...
                thetaDeltaSmoothWindows, ...
                'omitnan');
    end
end

%% Robust animal-level normalisation and state classification

StateWindows.thetaLogPower = ...
    log10(StateWindows.thetaPower + eps);

StateWindows.deltaLogPower = ...
    log10(StateWindows.deltaPower + eps);

StateWindows.highFrequencyLogPower = ...
    log10(StateWindows.highFrequencyPower + eps);

StateWindows.rawLogRms = ...
    log10(StateWindows.rawRmsUv + eps);

StateWindows.thetaDeltaRobustZ = ...
    nan(height(StateWindows), 1);

StateWindows.thetaPowerRobustZ = ...
    nan(height(StateWindows), 1);

StateWindows.deltaPowerRobustZ = ...
    nan(height(StateWindows), 1);

StateWindows.highFrequencyRobustZ = ...
    nan(height(StateWindows), 1);

StateWindows.rawRmsRobustZ = ...
    nan(height(StateWindows), 1);

StateWindows.isArtefactOrUnusable = ...
    false(height(StateWindows), 1);

StateWindows.operationalState = ...
    repmat("Intermediate / unclassified", ...
        height(StateWindows), 1);

StateWindows.stateConfidenceScore = ...
    zeros(height(StateWindows), 1);

thresholdRows = {};

for ai = 1:numel(animalMapNames)
    animalID = animalMapNames(ai);

    animalMask = ...
        StateWindows.animal == animalID & ...
        StateWindows.coverageFraction >= minimumWindowCoverage & ...
        isfinite(StateWindows.smoothedLog10ThetaDelta) & ...
        isfinite(StateWindows.thetaLogPower) & ...
        isfinite(StateWindows.deltaLogPower) & ...
        isfinite(StateWindows.highFrequencyLogPower) & ...
        isfinite(StateWindows.rawLogRms);

    animalRows = find(animalMask);

    if isempty(animalRows)
        thresholdRows(end+1,:) = { ...
            char(animalID), ...
            0, ...
            NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN}; %#ok<SAGROW>
        continue
    end

    thetaDeltaValues = ...
        StateWindows.smoothedLog10ThetaDelta(animalRows);

    thetaLogValues = ...
        StateWindows.thetaLogPower(animalRows);

    deltaLogValues = ...
        StateWindows.deltaLogPower(animalRows);

    highLogValues = ...
        StateWindows.highFrequencyLogPower(animalRows);

    rawLogValues = ...
        StateWindows.rawLogRms(animalRows);

    thetaDeltaMedian = median( ...
        thetaDeltaValues, 'omitnan');

    thetaDeltaMad = 1.4826 * median( ...
        abs(thetaDeltaValues - thetaDeltaMedian), ...
        'omitnan');

    thetaMedian = median(thetaLogValues, 'omitnan');
    thetaMad = 1.4826 * median( ...
        abs(thetaLogValues - thetaMedian), ...
        'omitnan');

    deltaMedian = median(deltaLogValues, 'omitnan');
    deltaMad = 1.4826 * median( ...
        abs(deltaLogValues - deltaMedian), ...
        'omitnan');

    highMedian = median(highLogValues, 'omitnan');
    highMad = 1.4826 * median( ...
        abs(highLogValues - highMedian), ...
        'omitnan');

    rawMedian = median(rawLogValues, 'omitnan');
    rawMad = 1.4826 * median( ...
        abs(rawLogValues - rawMedian), ...
        'omitnan');

    if ~isfinite(thetaDeltaMad) || thetaDeltaMad <= 0
        thetaDeltaMad = std(thetaDeltaValues, 'omitnan');
    end

    if ~isfinite(thetaMad) || thetaMad <= 0
        thetaMad = std(thetaLogValues, 'omitnan');
    end

    if ~isfinite(deltaMad) || deltaMad <= 0
        deltaMad = std(deltaLogValues, 'omitnan');
    end

    if ~isfinite(highMad) || highMad <= 0
        highMad = std(highLogValues, 'omitnan');
    end

    if ~isfinite(rawMad) || rawMad <= 0
        rawMad = std(rawLogValues, 'omitnan');
    end

    thetaDeltaMad = max(thetaDeltaMad, eps);
    thetaMad = max(thetaMad, eps);
    deltaMad = max(deltaMad, eps);
    highMad = max(highMad, eps);
    rawMad = max(rawMad, eps);

    StateWindows.thetaDeltaRobustZ(animalRows) = ...
        (thetaDeltaValues - thetaDeltaMedian) ./ ...
        thetaDeltaMad;

    StateWindows.thetaPowerRobustZ(animalRows) = ...
        (thetaLogValues - thetaMedian) ./ thetaMad;

    StateWindows.deltaPowerRobustZ(animalRows) = ...
        (deltaLogValues - deltaMedian) ./ deltaMad;

    StateWindows.highFrequencyRobustZ(animalRows) = ...
        (highLogValues - highMedian) ./ highMad;

    StateWindows.rawRmsRobustZ(animalRows) = ...
        (rawLogValues - rawMedian) ./ rawMad;

    thresholdRows(end+1,:) = { ...
        char(animalID), ...
        numel(animalRows), ...
        thetaDeltaMedian, ...
        thetaDeltaMad, ...
        thetaMedian, ...
        thetaMad, ...
        deltaMedian, ...
        deltaMad, ...
        highMedian, ...
        highMad, ...
        rawMedian, ...
        rawMad}; %#ok<SAGROW>
end

unusableMask = ...
    StateWindows.coverageFraction < minimumWindowCoverage | ...
    ~isfinite(StateWindows.thetaDeltaRobustZ) | ...
    ~isfinite(StateWindows.thetaPowerRobustZ) | ...
    ~isfinite(StateWindows.deltaPowerRobustZ) | ...
    ~isfinite(StateWindows.highFrequencyRobustZ) | ...
    ~isfinite(StateWindows.rawRmsRobustZ);

artefactMask = ...
    unusableMask | ...
    abs(StateWindows.rawRmsRobustZ) > artefactThresholdZ | ...
    StateWindows.highFrequencyRobustZ > artefactThresholdZ;

nremMask = ...
    ~artefactMask & ...
    StateWindows.thetaDeltaRobustZ <= ...
        -thetaDeltaStateThresholdZ & ...
    StateWindows.deltaPowerRobustZ >= ...
        supportingBandMinimumZ;

thetaDominantMask = ...
    ~artefactMask & ...
    StateWindows.thetaDeltaRobustZ >= ...
        thetaDeltaStateThresholdZ & ...
    StateWindows.thetaPowerRobustZ >= ...
        supportingBandMinimumZ;

StateWindows.operationalState(nremMask) = ...
    "Putative NREM / slow-wave-like";

StateWindows.operationalState(thetaDominantMask) = ...
    "Theta-dominant / REM-like or quiet-wake-like";

StateWindows.operationalState(artefactMask) = ...
    "Artefact / unusable";

StateWindows.isArtefactOrUnusable = artefactMask;

StateWindows.stateConfidenceScore(nremMask) = min( ...
    -StateWindows.thetaDeltaRobustZ(nremMask) - ...
        thetaDeltaStateThresholdZ, ...
    StateWindows.deltaPowerRobustZ(nremMask) - ...
        supportingBandMinimumZ);

StateWindows.stateConfidenceScore(thetaDominantMask) = min( ...
    StateWindows.thetaDeltaRobustZ(thetaDominantMask) - ...
        thetaDeltaStateThresholdZ, ...
    StateWindows.thetaPowerRobustZ(thetaDominantMask) - ...
        supportingBandMinimumZ);

StateThresholds = cell2table(thresholdRows, ...
    'VariableNames', { ...
        'animal', ...
        'nFiniteWindows', ...
        'thetaDeltaMedianLog10', ...
        'thetaDeltaRobustScale', ...
        'thetaLogPowerMedian', ...
        'thetaLogPowerRobustScale', ...
        'deltaLogPowerMedian', ...
        'deltaLogPowerRobustScale', ...
        'highFrequencyLogPowerMedian', ...
        'highFrequencyLogPowerRobustScale', ...
        'rawLogRmsMedian', ...
        'rawLogRmsRobustScale'});

StateThresholds.thetaDeltaStateThresholdZ = ...
    repmat(thetaDeltaStateThresholdZ, ...
        height(StateThresholds), 1);

StateThresholds.supportingBandMinimumZ = ...
    repmat(supportingBandMinimumZ, ...
        height(StateThresholds), 1);

StateThresholds.artefactThresholdZ = ...
    repmat(artefactThresholdZ, ...
        height(StateThresholds), 1);

writetable(StateThresholds, fullfile(outputFolder, ...
    'hc31_batch11M3_state_thresholds_by_animal.csv'));

writetable(StateWindows, fullfile(outputFolder, ...
    'hc31_batch11M3_state_windows.csv'));

%% Epoch and animal state-duration summaries

stateOrder = [ ...
    "Putative NREM / slow-wave-like", ...
    "Theta-dominant / REM-like or quiet-wake-like", ...
    "Intermediate / unclassified", ...
    "Artefact / unusable"];

summaryRows = {};

for ai = 1:numel(animalMapNames)
    for ep = 1:numel(epochNames)
        animalID = animalMapNames(ai);
        epochName = string(epochNames{ep});

        baseMask = ...
            StateWindows.animal == animalID & ...
            StateWindows.epoch == epochName;

        nEpochWindows = sum(baseMask);
        totalClassifiedDurationSec = ...
            nEpochWindows * stateStepSec;

        for st = 1:numel(stateOrder)
            stateMask = ...
                baseMask & ...
                StateWindows.operationalState == stateOrder(st);

            nStateWindows = sum(stateMask);
            stateDurationSec = ...
                nStateWindows * stateStepSec;

            summaryRows(end+1,:) = { ...
                char(animalID), ...
                char(epochName), ...
                char(stateOrder(st)), ...
                nStateWindows, ...
                stateDurationSec, ...
                stateDurationSec / 60, ...
                stateDurationSec / ...
                    max(totalClassifiedDurationSec, eps), ...
                median( ...
                    StateWindows.log10ThetaDelta(stateMask), ...
                    'omitnan'), ...
                median( ...
                    StateWindows.thetaDeltaRobustZ(stateMask), ...
                    'omitnan'), ...
                median( ...
                    StateWindows.deltaPowerRobustZ(stateMask), ...
                    'omitnan'), ...
                median( ...
                    StateWindows.thetaPowerRobustZ(stateMask), ...
                    'omitnan')}; %#ok<SAGROW>
        end
    end
end

EpochStateSummary = cell2table(summaryRows, ...
    'VariableNames', { ...
        'animal', ...
        'epoch', ...
        'operationalState', ...
        'nWindows', ...
        'stateDurationSec', ...
        'stateDurationMin', ...
        'fractionOfEpochWindows', ...
        'medianLog10ThetaDelta', ...
        'medianThetaDeltaRobustZ', ...
        'medianDeltaPowerRobustZ', ...
        'medianThetaPowerRobustZ'});

writetable(EpochStateSummary, fullfile(outputFolder, ...
    'hc31_batch11M3_epoch_state_summary.csv'));

%% Annotate candidate events with operational state

CandidateState = Candidate;

CandidateState.operationalStateAtPeak = ...
    repmat("No matching state window", ...
        height(CandidateState), 1);

CandidateState.stateWindowCenterUs = ...
    nan(height(CandidateState), 1);

CandidateState.distanceToStateWindowSec = ...
    nan(height(CandidateState), 1);

CandidateState.log10ThetaDeltaAtPeak = ...
    nan(height(CandidateState), 1);

CandidateState.thetaDeltaRobustZAtPeak = ...
    nan(height(CandidateState), 1);

CandidateState.thetaPowerRobustZAtPeak = ...
    nan(height(CandidateState), 1);

CandidateState.deltaPowerRobustZAtPeak = ...
    nan(height(CandidateState), 1);

CandidateState.highFrequencyRobustZAtPeak = ...
    nan(height(CandidateState), 1);

CandidateState.rawRmsRobustZAtPeak = ...
    nan(height(CandidateState), 1);

CandidateState.stateConfidenceScoreAtPeak = ...
    nan(height(CandidateState), 1);

for rr = 1:height(CandidateState)
    eventMask = ...
        StateWindows.animal == CandidateState.animal(rr) & ...
        StateWindows.epoch == CandidateState.epoch(rr);

    eventRows = find(eventMask);

    if isempty(eventRows)
        continue
    end

    [minimumDistanceUs, closestRelativeIndex] = min( ...
        abs( ...
            StateWindows.windowCenterUs(eventRows) - ...
            CandidateState.peakUs(rr)));

    closestRow = eventRows(closestRelativeIndex);
    distanceSec = minimumDistanceUs / 1e6;

    CandidateState.distanceToStateWindowSec(rr) = ...
        distanceSec;

    if distanceSec <= maximumCandidateWindowDistanceSec
        CandidateState.operationalStateAtPeak(rr) = ...
            StateWindows.operationalState(closestRow);

        CandidateState.stateWindowCenterUs(rr) = ...
            StateWindows.windowCenterUs(closestRow);

        CandidateState.log10ThetaDeltaAtPeak(rr) = ...
            StateWindows.log10ThetaDelta(closestRow);

        CandidateState.thetaDeltaRobustZAtPeak(rr) = ...
            StateWindows.thetaDeltaRobustZ(closestRow);

        CandidateState.thetaPowerRobustZAtPeak(rr) = ...
            StateWindows.thetaPowerRobustZ(closestRow);

        CandidateState.deltaPowerRobustZAtPeak(rr) = ...
            StateWindows.deltaPowerRobustZ(closestRow);

        CandidateState.highFrequencyRobustZAtPeak(rr) = ...
            StateWindows.highFrequencyRobustZ(closestRow);

        CandidateState.rawRmsRobustZAtPeak(rr) = ...
            StateWindows.rawRmsRobustZ(closestRow);

        CandidateState.stateConfidenceScoreAtPeak(rr) = ...
            StateWindows.stateConfidenceScore(closestRow);
    end
end

writetable(CandidateState, fullfile(outputFolder, ...
    'hc31_batch11M3_candidate_sleep_ripples_with_state.csv'));

%% Candidate-event rates per state

rateRows = {};

for ai = 1:numel(animalMapNames)
    for ep = 1:numel(epochNames)
        animalID = animalMapNames(ai);
        epochName = string(epochNames{ep});

        for st = 1:numel(stateOrder)
            stateName = stateOrder(st);

            durationMask = ...
                string(EpochStateSummary.animal) == animalID & ...
                string(EpochStateSummary.epoch) == epochName & ...
                string(EpochStateSummary.operationalState) == stateName;

            stateDurationMin = 0;

            if any(durationMask)
                stateDurationMin = ...
                    EpochStateSummary.stateDurationMin( ...
                        find(durationMask, 1));
            end

            candidateMask = ...
                CandidateState.animal == animalID & ...
                CandidateState.epoch == epochName & ...
                CandidateState.operationalStateAtPeak == stateName;

            nAllCandidates = sum(candidateMask);

            nCurrentNonArtifactCandidates = sum( ...
                candidateMask & ...
                ~CandidateState.currentArtifactFlag);

            allCandidateRate = ...
                nAllCandidates / max(stateDurationMin, eps);

            nonArtifactCandidateRate = ...
                nCurrentNonArtifactCandidates / ...
                max(stateDurationMin, eps);

            if stateDurationMin <= 0
                allCandidateRate = NaN;
                nonArtifactCandidateRate = NaN;
            end

            rateRows(end+1,:) = { ...
                char(animalID), ...
                char(epochName), ...
                char(stateName), ...
                stateDurationMin, ...
                nAllCandidates, ...
                nCurrentNonArtifactCandidates, ...
                allCandidateRate, ...
                nonArtifactCandidateRate}; %#ok<SAGROW>
        end
    end
end

CandidateRateByState = cell2table(rateRows, ...
    'VariableNames', { ...
        'animal', ...
        'epoch', ...
        'operationalState', ...
        'stateDurationMin', ...
        'nAllCandidates', ...
        'nCurrentNonArtifactCandidates', ...
        'allCandidateRatePerMinute', ...
        'currentNonArtifactCandidateRatePerMinute'});

writetable(CandidateRateByState, fullfile(outputFolder, ...
    'hc31_batch11M3_candidate_ripple_rate_by_state.csv'));

%% Candidate-state coverage summary

coverageSummaryRows = {};

for ep = 1:numel(epochNames)
    epochName = string(epochNames{ep});
    epochMask = CandidateState.epoch == epochName;

    for st = 1:numel(stateOrder)
        stateName = stateOrder(st);
        stateMask = ...
            epochMask & ...
            CandidateState.operationalStateAtPeak == stateName;

        coverageSummaryRows(end+1,:) = { ...
            char(epochName), ...
            char(stateName), ...
            sum(stateMask), ...
            sum(stateMask & ...
                ~CandidateState.currentArtifactFlag), ...
            mean( ...
                CandidateState.thetaDeltaRobustZAtPeak(stateMask), ...
                'omitnan')}; %#ok<SAGROW>
    end

    unmatchedMask = ...
        epochMask & ...
        CandidateState.operationalStateAtPeak == ...
            "No matching state window";

    coverageSummaryRows(end+1,:) = { ...
        char(epochName), ...
        'No matching state window', ...
        sum(unmatchedMask), ...
        sum(unmatchedMask & ...
            ~CandidateState.currentArtifactFlag), ...
        NaN}; %#ok<SAGROW>
end

CandidateStateCoverage = cell2table(coverageSummaryRows, ...
    'VariableNames', { ...
        'epoch', ...
        'operationalState', ...
        'nAllCandidates', ...
        'nCurrentNonArtifactCandidates', ...
        'meanThetaDeltaRobustZAtCandidate'});

writetable(CandidateStateCoverage, fullfile(outputFolder, ...
    'hc31_batch11M3_candidate_state_coverage_summary.csv'));

%% Failure table

if isempty(failureRows)
    FailureTable = table( ...
        strings(0,1), ...
        strings(0,1), ...
        strings(0,1), ...
        'VariableNames', { ...
            'animal', ...
            'epoch', ...
            'reason'});
else
    FailureTable = cell2table(failureRows, ...
        'VariableNames', { ...
            'animal', ...
            'epoch', ...
            'reason'});
end

writetable(FailureTable, fullfile(outputFolder, ...
    'hc31_batch11M3_failed_epochs_or_segments.csv'));

%% Figures: per-animal timelines

for ai = 1:numel(animalMapNames)
    animalID = animalMapNames(ai);

    fig = figure( ...
        'Visible', 'off', ...
        'Color', 'w', ...
        'Position', [80 80 1500 1000]);

    tl = tiledlayout( ...
        numel(epochNames), ...
        2, ...
        'TileSpacing', 'compact', ...
        'Padding', 'compact');

    for ep = 1:numel(epochNames)
        epochName = string(epochNames{ep});

        timelineMask = ...
            StateWindows.animal == animalID & ...
            StateWindows.epoch == epochName;

        timelineRows = find(timelineMask);

        if isempty(timelineRows)
            nexttile
            axis off
            text(0.5, 0.5, ...
                sprintf('%s unavailable', epochName), ...
                'HorizontalAlignment', 'center');

            nexttile
            axis off
            text(0.5, 0.5, ...
                sprintf('%s unavailable', epochName), ...
                'HorizontalAlignment', 'center');
            continue
        end

        [~, timelineOrder] = sort( ...
            StateWindows.windowCenterUs(timelineRows));

        timelineRows = ...
            timelineRows(timelineOrder);

        epochZeroUs = ...
            StateWindows.windowCenterUs(timelineRows(1));

        timelineMinutes = ...
            (StateWindows.windowCenterUs(timelineRows) - ...
            epochZeroUs) / 1e6 / 60;

        nexttile
        hold on

        plot( ...
            timelineMinutes, ...
            StateWindows.thetaDeltaRobustZ(timelineRows), ...
            '-', ...
            'LineWidth', 0.8);

        yline( ...
            thetaDeltaStateThresholdZ, ...
            '--', ...
            'Theta-dominant threshold');

        yline( ...
            -thetaDeltaStateThresholdZ, ...
            '--', ...
            'Slow-wave threshold');

        candidateTimelineMask = ...
            CandidateState.animal == animalID & ...
            CandidateState.epoch == epochName & ...
            isfinite( ...
                CandidateState.thetaDeltaRobustZAtPeak);

        if any(candidateTimelineMask)
            candidateMinutes = ...
                (CandidateState.peakUs(candidateTimelineMask) - ...
                epochZeroUs) / 1e6 / 60;

            scatter( ...
                candidateMinutes, ...
                CandidateState.thetaDeltaRobustZAtPeak( ...
                    candidateTimelineMask), ...
                14, ...
                'filled');
        end

        xlabel('Time from analysed epoch start (min)');
        ylabel('Theta/delta robust z');
        title(sprintf('%s: theta/delta state timeline', epochName));
        grid on
        box off

        nexttile
        hold on

        plot( ...
            timelineMinutes, ...
            StateWindows.deltaPowerRobustZ(timelineRows), ...
            '-', ...
            'LineWidth', 0.8);

        plot( ...
            timelineMinutes, ...
            StateWindows.thetaPowerRobustZ(timelineRows), ...
            '-', ...
            'LineWidth', 0.8);

        plot( ...
            timelineMinutes, ...
            StateWindows.highFrequencyRobustZ(timelineRows), ...
            '-', ...
            'LineWidth', 0.7);

        yline(artefactThresholdZ, '--');

        xlabel('Time from analysed epoch start (min)');
        ylabel('Robust z');
        title(sprintf('%s: band-power and artefact context', epochName));
        legend( ...
            {'Delta power','Theta power','70-110 Hz power'}, ...
            'Location', 'best');
        grid on
        box off
    end

    title(tl, sprintf( ...
        '%s PRE/REST/POST operational LFP-state classification', ...
        animalID), ...
        'Interpreter', 'none');

    figurePath = fullfile(figureFolder, sprintf( ...
        '%s_batch11M3_state_timelines.png', ...
        animalID));

    try
        exportgraphics(fig, figurePath, ...
            'Resolution', saveDpi);
    catch
        saveas(fig, figurePath);
    end

    close(fig);
end

%% Figure: state fractions by animal and epoch

rowLabels = strings(0,1);
stateFractionMatrix = zeros(0, numel(stateOrder));

for ai = 1:numel(animalMapNames)
    for ep = 1:numel(epochNames)
        animalID = animalMapNames(ai);
        epochName = string(epochNames{ep});

        rowLabels(end+1,1) = ...
            animalID + " " + epochName; %#ok<SAGROW>

        thisRow = zeros(1, numel(stateOrder));

        for st = 1:numel(stateOrder)
            summaryMask = ...
                string(EpochStateSummary.animal) == animalID & ...
                string(EpochStateSummary.epoch) == epochName & ...
                string(EpochStateSummary.operationalState) == ...
                    stateOrder(st);

            if any(summaryMask)
                thisRow(st) = ...
                    EpochStateSummary.fractionOfEpochWindows( ...
                        find(summaryMask, 1));
            end
        end

        stateFractionMatrix(end+1,:) = thisRow; %#ok<SAGROW>
    end
end

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [100 100 1300 850]);

barh(stateFractionMatrix, 'stacked');

set(gca, ...
    'YTick', 1:numel(rowLabels), ...
    'YTickLabel', rowLabels, ...
    'YDir', 'reverse');

xlabel('Fraction of analysed epoch windows');
title('Operational LFP-state composition by animal and epoch');
legend(cellstr(stateOrder), ...
    'Location', 'southoutside');
xlim([0 1]);
grid on
box off

try
    exportgraphics(fig, fullfile(figureFolder, ...
        'batch11M3_state_fraction_by_animal_epoch.png'), ...
        'Resolution', saveDpi);
catch
    saveas(fig, fullfile(figureFolder, ...
        'batch11M3_state_fraction_by_animal_epoch.png'));
end

close(fig);

%% Figure: mean candidate-event rate by state and epoch

rateMeanMatrix = nan(numel(stateOrder), numel(epochNames));
rateSemMatrix = nan(numel(stateOrder), numel(epochNames));

for st = 1:numel(stateOrder)
    for ep = 1:numel(epochNames)
        rateMask = ...
            string(CandidateRateByState.operationalState) == ...
                stateOrder(st) & ...
            string(CandidateRateByState.epoch) == ...
                string(epochNames{ep});

        rateValues = ...
            CandidateRateByState. ...
                currentNonArtifactCandidateRatePerMinute(rateMask);

        rateValues = rateValues(isfinite(rateValues));

        if ~isempty(rateValues)
            rateMeanMatrix(st, ep) = ...
                mean(rateValues, 'omitnan');

            rateSemMatrix(st, ep) = ...
                std(rateValues, 'omitnan') / ...
                sqrt(numel(rateValues));
        end
    end
end

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [100 100 1200 720]);

bar(rateMeanMatrix);

set(gca, ...
    'XTick', 1:numel(stateOrder), ...
    'XTickLabel', stateOrder, ...
    'XTickLabelRotation', 20);

ylabel('Current non-artefact candidate events per minute');
title('Candidate-event rate by operational state');
legend(epochNames, 'Location', 'northoutside');
grid on
box off

try
    exportgraphics(fig, fullfile(figureFolder, ...
        'batch11M3_candidate_rate_by_state_epoch.png'), ...
        'Resolution', saveDpi);
catch
    saveas(fig, fullfile(figureFolder, ...
        'batch11M3_candidate_rate_by_state_epoch.png'));
end

close(fig);

%% Figure: candidate counts by operational state

candidateStateCount = zeros(numel(stateOrder), numel(epochNames));

for st = 1:numel(stateOrder)
    for ep = 1:numel(epochNames)
        candidateStateCount(st, ep) = sum( ...
            CandidateState.operationalStateAtPeak == ...
                stateOrder(st) & ...
            CandidateState.epoch == ...
                string(epochNames{ep}) & ...
            ~CandidateState.currentArtifactFlag);
    end
end

fig = figure( ...
    'Visible', 'off', ...
    'Color', 'w', ...
    'Position', [100 100 1200 720]);

bar(candidateStateCount);

set(gca, ...
    'XTick', 1:numel(stateOrder), ...
    'XTickLabel', stateOrder, ...
    'XTickLabelRotation', 20);

ylabel('Number of current non-artefact candidates');
title('Candidate-event counts by operational state');
legend(epochNames, 'Location', 'northoutside');
grid on
box off

try
    exportgraphics(fig, fullfile(figureFolder, ...
        'batch11M3_candidate_counts_by_state_epoch.png'), ...
        'Resolution', saveDpi);
catch
    saveas(fig, fullfile(figureFolder, ...
        'batch11M3_candidate_counts_by_state_epoch.png'));
end

close(fig);

%% Text summary

summaryPath = fullfile(outputFolder, ...
    'hc31_batch11M3_state_classification_summary.txt');

fid = fopen(summaryPath, 'w');

if fid >= 0
    fprintf(fid, ...
        'HC-31 Batch 11M3: corrected PRE/REST/POST operational state classification\n');
    fprintf(fid, ...
        '================================================================\n\n');

    fprintf(fid, 'Input candidate-event table:\n%s\n\n', candidateCsv);

    fprintf(fid, 'Epoch mapping\n');
    fprintf(fid, '-------------\n');
    fprintf(fid, 'PRE = spEpochSep column 1\n');
    fprintf(fid, 'REST = spEpochSep column 3\n');
    fprintf(fid, 'POST = spEpochSep column 4\n\n');

    fprintf(fid, 'Signal windows\n');
    fprintf(fid, '--------------\n');
    fprintf(fid, 'Window length: %.2f s\n', stateWindowSec);
    fprintf(fid, 'Window step: %.2f s\n', stateStepSec);
    fprintf(fid, 'Delta band: %.1f-%.1f Hz\n', ...
        deltaBandHz(1), deltaBandHz(2));
    fprintf(fid, 'Theta band: %.1f-%.1f Hz\n', ...
        thetaBandHz(1), thetaBandHz(2));
    fprintf(fid, 'High-frequency control band: %.1f-%.1f Hz\n\n', ...
        highFrequencyControlBandHz(1), ...
        highFrequencyControlBandHz(2));

    fprintf(fid, 'Operational labels\n');
    fprintf(fid, '------------------\n');
    fprintf(fid, [ ...
        'Putative NREM / slow-wave-like: ', ...
        'theta/delta z <= -%.2f and delta-power z >= %.2f\n'], ...
        thetaDeltaStateThresholdZ, ...
        supportingBandMinimumZ);

    fprintf(fid, [ ...
        'Theta-dominant / REM-like or quiet-wake-like: ', ...
        'theta/delta z >= %.2f and theta-power z >= %.2f\n'], ...
        thetaDeltaStateThresholdZ, ...
        supportingBandMinimumZ);

    fprintf(fid, [ ...
        'Artefact / unusable: insufficient coverage, ', ...
        '|raw RMS z| > %.2f, or high-frequency z > %.2f\n\n'], ...
        artefactThresholdZ, ...
        artefactThresholdZ);

    fprintf(fid, 'Output coverage\n');
    fprintf(fid, '---------------\n');
    fprintf(fid, 'State windows: %d\n', height(StateWindows));
    fprintf(fid, 'Candidate events annotated: %d\n', height(CandidateState));
    fprintf(fid, 'Unmatched candidates: %d\n', sum( ...
        CandidateState.operationalStateAtPeak == ...
            "No matching state window"));
    fprintf(fid, 'Failed epoch/segment rows: %d\n\n', ...
        height(FailureTable));

    fprintf(fid, 'Interpretation boundary\n');
    fprintf(fid, '-----------------------\n');
    fprintf(fid, [ ...
        'These labels are based on LFP theta/delta structure only. ', ...
        'Without EMG and formal manual sleep scoring, theta-dominant ', ...
        'periods cannot be separated confidently into REM versus quiet wake.\n']);
    fprintf(fid, [ ...
        'Candidate-event rates remain rates of automatically detected ', ...
        'candidate events, not confirmed physiological sharp-wave ripples.\n']);
    fprintf(fid, [ ...
        'Use state labels as filters for later validation, not as ', ...
        'standalone proof of sleep stage or replay.\n']);

    fclose(fid);
end

%% Completion

fprintf('\nBatch 11M3 complete.\n');
fprintf('Output folder:\n  %s\n\n', outputFolder);

fprintf('Primary files to send back:\n');
fprintf('  hc31_batch11M3_state_windows.csv\n');
fprintf('  hc31_batch11M3_epoch_state_summary.csv\n');
fprintf('  hc31_batch11M3_candidate_sleep_ripples_with_state.csv\n');
fprintf('  hc31_batch11M3_candidate_ripple_rate_by_state.csv\n');
fprintf('  hc31_batch11M3_state_thresholds_by_animal.csv\n');
fprintf('  hc31_batch11M3_epoch_inventory.csv\n');
fprintf('  hc31_batch11M3_failed_epochs_or_segments.csv\n');
fprintf('  hc31_batch11M3_state_classification_summary.txt\n');
fprintf('  figures folder\n\n');

fprintf(['Remember: these are operational LFP-state labels, ', ...
    'not formal EMG-confirmed sleep stages.\n']);
