function AnimalSummary = make_animal_unit_summary(U)
    U.band = string(U.band);
    U.category = string(U.category);
    animals = unique(string(U.animal), 'stable');
    bands = unique(U.band, 'stable');
    cats = unique(U.category, 'stable');

    rows = {};
    for ai = 1:numel(animals)
        for bi = 1:numel(bands)
            for ci = 1:numel(cats)
                idx = string(U.animal) == animals(ai) & U.band == bands(bi) & U.category == cats(ci);
                if ~any(idx), continue; end

                diffFR = U.burstMinusControlFiringRateHz(idx);
                diffPart = U.burstMinusControlParticipationFraction(idx);
                hasNov = logical(U.hasNovelField(idx));
                hasFam = logical(U.hasFamiliarField(idx));

                rows(end+1,:) = {char(animals(ai)), char(bands(bi)), char(cats(ci)), ...
                    nnz(idx), mean(U.burstFiringRateHz(idx), 'omitnan'), ...
                    mean(U.controlFiringRateHz(idx), 'omitnan'), ...
                    mean(diffFR, 'omitnan'), median(diffFR, 'omitnan'), ...
                    nnz(diffFR > 0), mean(diffPart, 'omitnan'), ...
                    mean(diffFR(hasNov), 'omitnan'), mean(diffFR(~hasNov), 'omitnan'), ...
                    mean(diffFR(hasFam), 'omitnan'), mean(diffFR(~hasFam), 'omitnan')}; %#ok<SAGROW>
            end
        end
    end

    AnimalSummary = cell2table(rows, 'VariableNames', { ...
        'animal','band','category','nUnits','meanBurstFiringRateHz', ...
        'meanControlFiringRateHz','meanBurstMinusControlFiringRateHz', ...
        'medianBurstMinusControlFiringRateHz','nUnitsBurstHigherThanControl', ...
        'meanBurstMinusControlParticipationFraction', ...
        'meanDiffFR_hasNovelField','meanDiffFR_noNovelField', ...
        'meanDiffFR_hasFamiliarField','meanDiffFR_noFamiliarField'});
end
