%% HC-31 Batch 11O
% VALIDATED CA1 POPULATION RECRUITMENT AND STATE-MATCHED EVENT RATES
%
% Plain script: no local functions.
%
% Primary questions:
% 1. Do locked candidate-event tiers coincide with increased CA1 population
%    firing relative to equal-duration flanks?
% 2. Does recruitment exceed state-matched pseudo-event recruitment?
% 3. How do screened event rates differ across PRE, REST and POST when the
%    operational LFP state is matched?
% 4. Are conclusions stable across Tier A, A+B, A+C and A+B+C definitions?
%
% Inference is animal-weighted. Event-level rows are retained for audit, but
% event counts are not treated as independent biological replicates.

clearvars -except scriptFile scriptFolder txt
clc
close all
rehash

fprintf('\nHC-31 Batch 11O Stage A\n');
fprintf('Validated CA1 recruitment and state-matched rates\n');
fprintf('--------------------------------------------------\n');

%% Settings

defaultRoot = getenv('HC31_DATA_ROOT');

animalIndices = 5:9;
fallbackAnimalIDs = { ...
    'ANM00190422', ...
    'ANM204878', ...
    'ANM212379', ...
    'ANM228899', ...
    'ANM228900'};

pethHalfWindowSec = 0.50;
pethBinSec = 0.010;

centralWindow = [-0.050 0.050];
leftFlankWindow = [-0.300 -0.200];
rightFlankWindow = [0.200 0.300];

pseudoExclusionSec = 0.50;
minimumEventsForAnimalSummary = 3;
minimumAnimalsForTest = 3;

rng(31,'twister');

pethEdges = ...
    -pethHalfWindowSec:pethBinSec:pethHalfWindowSec;

pethCenters = ...
    pethEdges(1:end-1)+pethBinSec/2;

centralDurationSec = diff(centralWindow);
flankDurationSec = ...
    diff(leftFlankWindow)+diff(rightFlankWindow);

%% Script folder

if exist('scriptFolder','var') && ...
        exist(scriptFolder,'dir') == 7
    addpath(scriptFolder);
else
    thisScriptPath = mfilename('fullpath');

    if ~isempty(thisScriptPath)
        scriptFolder = fileparts(thisScriptPath);
        addpath(scriptFolder);
    end
end

if exist('hc31_batch11O_load_epoch_spikes','file') ~= 2 || ...
        exist('hc31_batch11O_bh_fdr','file') ~= 2
    error(['Keep the Batch 11O helper files beside ', ...
        'the Stage A script.']);
end

%% Locate root and inputs

if exist(defaultRoot,'dir') == 7
    rootDir = defaultRoot;
else
    rootDir = uigetdir(pwd, ...
        'Select the HC-31 root folder');

    if isequal(rootDir,0)
        error('No root folder selected.');
    end
end

resSavePath = fullfile(rootDir,'resSave.mat');

if exist(resSavePath,'file') ~= 2
    [f,p] = uigetfile('*.mat','Select resSave.mat');

    if isequal(f,0)
        error('No resSave.mat selected.');
    end

    resSavePath = fullfile(p,f);
end

defaultMasterPath = fullfile( ...
    rootDir, ...
    'hc31_batch11Nplus_final_master_event_set', ...
    'hc31_batch11Nplus_manual_review_override_corrected', ...
    'hc31_batch11Nplus_MASTER_EVENT_TABLE_MANUAL_OVERRIDE_CORRECTED.csv');

masterPath = defaultMasterPath;

if exist(masterPath,'file') ~= 2
    [f,p] = uigetfile('*.csv', ...
        ['Select ', ...
        'hc31_batch11Nplus_MASTER_EVENT_TABLE_MANUAL_OVERRIDE_CORRECTED.csv']);

    if isequal(f,0)
        error('No corrected master table selected.');
    end

    masterPath = fullfile(p,f);
end

defaultStateWindowsPath = fullfile( ...
    rootDir, ...
    'hc31_batch11M3_corrected_pre_rest_post_state_classification', ...
    'hc31_batch11M3_state_windows.csv');

stateWindowsPath = defaultStateWindowsPath;

if exist(stateWindowsPath,'file') ~= 2
    [f,p] = uigetfile('*.csv', ...
        'Select hc31_batch11M3_state_windows.csv');

    if isequal(f,0)
        error('No corrected state-window table selected.');
    end

    stateWindowsPath = fullfile(p,f);
end

defaultStateSummaryPath = fullfile( ...
    rootDir, ...
    'hc31_batch11M3_corrected_pre_rest_post_state_classification', ...
    'hc31_batch11M3_epoch_state_summary.csv');

stateSummaryPath = defaultStateSummaryPath;

if exist(stateSummaryPath,'file') ~= 2
    [f,p] = uigetfile('*.csv', ...
        'Select hc31_batch11M3_epoch_state_summary.csv');

    if isequal(f,0)
        error('No epoch-state summary selected.');
    end

    stateSummaryPath = fullfile(p,f);
end

%% Optional beta2 unit tags

unitTagPath = '';

tagCandidates = { ...
    fullfile(rootDir, ...
        'hc31_batch10_sleep_replay_memory_link_FORCE_V2', ...
        'hc31_batch10_run1_beta2_unit_tags.csv'), ...
    fullfile(rootDir, ...
        'hc31_batch10_sleep_replay_memory_link_FORCE', ...
        'hc31_batch10_run1_beta2_unit_tags.csv'), ...
    fullfile(rootDir, ...
        'hc31_batch8_spikes_placefield_linkage_FORCE', ...
        'hc31_batch8_unit_burst_participation.csv')};

for candidateIndex = 1:numel(tagCandidates)
    if exist(tagCandidates{candidateIndex},'file') == 2
        unitTagPath = tagCandidates{candidateIndex};
        break
    end
end

if isempty(unitTagPath)
    [f,p] = uigetfile('*.csv', ...
        ['Optional: select a Run1 beta2 unit-tag CSV, ', ...
        'or Cancel']);

    if ~isequal(f,0)
        unitTagPath = fullfile(p,f);
    end
end

%% Read data

Loaded = load(resSavePath);

if ~isfield(Loaded,'resSave')
    error('The MAT file does not contain resSave.');
end

resSave = Loaded.resSave;

Master = readtable( ...
    masterPath, ...
    'TextType','string', ...
    'VariableNamingRule','preserve');

StateWindows = readtable( ...
    stateWindowsPath, ...
    'TextType','string', ...
    'VariableNamingRule','preserve');

StateSummary = readtable( ...
    stateSummaryPath, ...
    'TextType','string', ...
    'VariableNamingRule','preserve');

if ~isempty(unitTagPath)
    UnitTags = readtable( ...
        unitTagPath, ...
        'TextType','string', ...
        'VariableNamingRule','preserve');
else
    UnitTags = table();
end

requiredMaster = { ...
    'eventID','animal','epoch','peakUs', ...
    'operationalStateAtPeak','masterTier', ...
    'screenedAnalysisEligible', ...
    'strictReviewedEligible'};

missingMaster = setdiff( ...
    requiredMaster, ...
    Master.Properties.VariableNames);

if ~isempty(missingMaster)
    error('Master table is missing: %s', ...
        strjoin(missingMaster,', '));
end

Master.animal = strtrim(string(Master.animal));
Master.epoch = upper(strtrim(string(Master.epoch)));
Master.masterTier = string(Master.masterTier);
Master.operationalStateAtPeak = ...
    string(Master.operationalStateAtPeak);

StateWindows.animal = ...
    strtrim(string(StateWindows.animal));
StateWindows.epoch = ...
    upper(strtrim(string(StateWindows.epoch)));
StateWindows.operationalState = ...
    string(StateWindows.operationalState);

StateSummary.animal = ...
    strtrim(string(StateSummary.animal));
StateSummary.epoch = ...
    upper(strtrim(string(StateSummary.epoch)));
StateSummary.operationalState = ...
    string(StateSummary.operationalState);

%% Define permanent tier memberships

isTierA = startsWith( ...
    Master.masterTier, ...
    "Tier A:");

isTierB = startsWith( ...
    Master.masterTier, ...
    "Tier B:");

isTierC = startsWith( ...
    Master.masterTier, ...
    "Tier C:");

isTierD = startsWith( ...
    Master.masterTier, ...
    "Tier D:");

analysisMask = ...
    isTierA | isTierB | isTierC | isTierD;

Events = Master(analysisMask,:);

Events.isTierA = isTierA(analysisMask);
Events.isTierB = isTierB(analysisMask);
Events.isTierC = isTierC(analysisMask);
Events.isTierD = isTierD(analysisMask);

Events.inSetTierA = Events.isTierA;
Events.inSetTierAB = ...
    Events.isTierA | Events.isTierB;
Events.inSetTierAC = ...
    Events.isTierA | Events.isTierC;
Events.inSetTierABC = ...
    Events.isTierA | Events.isTierB | Events.isTierC;
Events.inSetTierABCD = true(height(Events),1);

Events.stateGroup = ...
    repmat("Other",height(Events),1);

Events.stateGroup(contains( ...
    Events.operationalStateAtPeak, ...
    "NREM", ...
    'IgnoreCase',true)) = "NREM";

Events.stateGroup(contains( ...
    Events.operationalStateAtPeak, ...
    "Intermediate", ...
    'IgnoreCase',true)) = "Intermediate";

Events.stateGroup(contains( ...
    Events.operationalStateAtPeak, ...
    "Theta-dominant", ...
    'IgnoreCase',true)) = "ThetaDominant";

Events.stateGroup(Events.epoch == "RUN1AWAKE") = ...
    "Awake";

Events = sortrows( ...
    Events, ...
    {'animal','epoch','peakUs'});

nEventsTotal = height(Events);

fprintf('Permanent Tier A-D events: %d\n', ...
    nEventsTotal);

%% Output folders

outputFolder = fullfile(rootDir, ...
    'hc31_batch11O_validated_biological_results', ...
    'stageA_population_recruitment_and_rates');

figureFolder = fullfile(outputFolder,'figures');

if ~exist(outputFolder,'dir')
    mkdir(outputFolder);
end

if ~exist(figureFolder,'dir')
    mkdir(figureFolder);
end

%% Resolve optional unit-tag columns

tagAnimalColumn = '';
tagUnitColumn = '';
tagBetaColumn = '';
tagNovelColumn = '';
tagBandColumn = '';

if ~isempty(UnitTags)
    tagNames = UnitTags.Properties.VariableNames;
    tagLower = lower(tagNames);

    candidates = {'animal','animalid','animal_id','rat','subject'};
    for candidateIndex = 1:numel(candidates)
        hit = find(strcmp( ...
            tagLower,lower(candidates{candidateIndex})),1);

        if ~isempty(hit)
            tagAnimalColumn = tagNames{hit};
            break
        end
    end

    candidates = { ...
        'unitindex','unit','unitid','unit_id', ...
        'cellindex','cell'};
    for candidateIndex = 1:numel(candidates)
        hit = find(strcmp( ...
            tagLower,lower(candidates{candidateIndex})),1);

        if ~isempty(hit)
            tagUnitColumn = tagNames{hit};
            break
        end
    end

    candidates = { ...
        'isbeta2tagged','beta2tagged', ...
        'anybeta2tagged','participatedinbeta2'};
    for candidateIndex = 1:numel(candidates)
        hit = find(strcmp( ...
            tagLower,lower(candidates{candidateIndex})),1);

        if ~isempty(hit)
            tagBetaColumn = tagNames{hit};
            break
        end
    end

    candidates = { ...
        'isnovelbeta2tagged','novelbeta2tagged', ...
        'participatedinnovelbeta2'};
    for candidateIndex = 1:numel(candidates)
        hit = find(strcmp( ...
            tagLower,lower(candidates{candidateIndex})),1);

        if ~isempty(hit)
            tagNovelColumn = tagNames{hit};
            break
        end
    end

    candidates = {'band','frequencyband','bandname'};
    for candidateIndex = 1:numel(candidates)
        hit = find(strcmp( ...
            tagLower,lower(candidates{candidateIndex})),1);

        if ~isempty(hit)
            tagBandColumn = tagNames{hit};
            break
        end
    end
end

%% Allocate event-level metrics

nBins = numel(pethCenters);

nUsableUnits = nan(nEventsTotal,1);
centralRateHzPerUnit = nan(nEventsTotal,1);
flankRateHzPerUnit = nan(nEventsTotal,1);
centralMinusFlankRate = nan(nEventsTotal,1);
centralActiveFraction = nan(nEventsTotal,1);
flankActiveFraction = nan(nEventsTotal,1);
centralMinusFlankActiveFraction = nan(nEventsTotal,1);

pseudoPeakUs = nan(nEventsTotal,1);
pseudoCentralRateHzPerUnit = nan(nEventsTotal,1);
pseudoCentralActiveFraction = nan(nEventsTotal,1);
eventMinusPseudoRate = nan(nEventsTotal,1);
eventMinusPseudoActiveFraction = nan(nEventsTotal,1);

beta2TaggedNUnits = nan(nEventsTotal,1);
beta2TaggedCentralMinusFlankRate = nan(nEventsTotal,1);
untaggedNUnits = nan(nEventsTotal,1);
untaggedCentralMinusFlankRate = nan(nEventsTotal,1);
novelBeta2TaggedNUnits = nan(nEventsTotal,1);
novelBeta2TaggedCentralMinusFlankRate = nan(nEventsTotal,1);

eventPethRate = nan(nEventsTotal,nBins);
pseudoPethRate = nan(nEventsTotal,nBins);

%% Main animal/epoch processing

epochNames = ["PRE","REST","POST","RUN1AWAKE"];
epochColumns = [1 3 4 2];

for animalPosition = 1:numel(animalIndices)
    resSaveIndex = animalIndices(animalPosition);

    if resSaveIndex > numel(resSave)
        continue
    end

    R = resSave(resSaveIndex);
    animalID = string(fallbackAnimalIDs{animalPosition});

    try
        if isfield(R,'spAll') && ...
                ~isempty(R.spAll) && ...
                isfield(R.spAll,'animal')
            animalID = strtrim(string(R.spAll(1).animal));
        elseif isfield(R,'name')
            animalID = strtrim(string(R.name));
        elseif isfield(R,'animal')
            animalID = strtrim(string(R.animal));
        end
    catch
    end

    fprintf('\nProcessing %s\n',animalID);

    for epochIndex = 1:numel(epochNames)
        epochName = epochNames(epochIndex);

        eventRows = find( ...
            Events.animal == animalID & ...
            Events.epoch == epochName);

        if isempty(eventRows)
            continue
        end

        [spikeCell,usableMask,nUnits,loadedColumn] = ...
            hc31_batch11O_load_epoch_spikes( ...
            R,epochName);

        usableUnits = find(usableMask);

        if isempty(usableUnits)
            fprintf('  %s: no usable spike data.\n',epochName);
            continue
        end

        fprintf('  %s: %d events, %d usable units, column %d\n', ...
            epochName, ...
            numel(eventRows), ...
            numel(usableUnits), ...
            loadedColumn);

        isBeta2Tagged = false(nUnits,1);
        isNovelTagged = false(nUnits,1);

        if ~isempty(UnitTags) && ...
                ~isempty(tagAnimalColumn) && ...
                ~isempty(tagUnitColumn)

            tagMask = ...
                strtrim(string( ...
                UnitTags.(tagAnimalColumn))) == ...
                animalID;

            TagSub = UnitTags(tagMask,:);

            if ~isempty(tagBandColumn) && ...
                    ~isempty(TagSub)
                bandText = lower(strtrim(string( ...
                    TagSub.(tagBandColumn))));

                betaBandMask = ...
                    contains(bandText,'beta2') | ...
                    contains(bandText,'23-30') | ...
                    contains(bandText,'23_30');

                if any(betaBandMask)
                    TagSub = TagSub(betaBandMask,:);
                end
            end

            if ~isempty(TagSub)
                unitValues = ...
                    str2double(string( ...
                    TagSub.(tagUnitColumn)));

                if isnumeric(TagSub.(tagUnitColumn))
                    unitValues = ...
                        double(TagSub.(tagUnitColumn));
                end

                betaValues = false(height(TagSub),1);
                novelValues = false(height(TagSub),1);

                if ~isempty(tagBetaColumn)
                    raw = TagSub.(tagBetaColumn);

                    if isnumeric(raw) || islogical(raw)
                        betaValues = logical(raw);
                    else
                        textValues = lower(strtrim(string(raw)));
                        betaValues = ...
                            textValues == "true" | ...
                            textValues == "1" | ...
                            textValues == "yes";
                    end
                end

                if ~isempty(tagNovelColumn)
                    raw = TagSub.(tagNovelColumn);

                    if isnumeric(raw) || islogical(raw)
                        novelValues = logical(raw);
                    else
                        textValues = lower(strtrim(string(raw)));
                        novelValues = ...
                            textValues == "true" | ...
                            textValues == "1" | ...
                            textValues == "yes";
                    end
                end

                for tagIndex = 1:numel(unitValues)
                    unitIndex = round(unitValues(tagIndex));

                    if isfinite(unitIndex) && ...
                            unitIndex >= 1 && ...
                            unitIndex <= nUnits
                        isBeta2Tagged(unitIndex) = ...
                            isBeta2Tagged(unitIndex) | ...
                            betaValues(tagIndex);

                        isNovelTagged(unitIndex) = ...
                            isNovelTagged(unitIndex) | ...
                            novelValues(tagIndex);
                    end
                end

                isBeta2Tagged = ...
                    isBeta2Tagged | isNovelTagged;
            end
        end

        % Build same-state pseudo-event pools for sleep epochs.
        pseudoPools = struct();

        if epochName ~= "RUN1AWAKE"
            stateNamesThisEpoch = unique( ...
                Events.operationalStateAtPeak(eventRows), ...
                'stable');

            allEpochPeaks = double( ...
                Master.peakUs( ...
                Master.animal == animalID & ...
                Master.epoch == epochName));

            for stateIndex = 1:numel(stateNamesThisEpoch)
                stateName = stateNamesThisEpoch(stateIndex);

                windowMask = ...
                    StateWindows.animal == animalID & ...
                    StateWindows.epoch == epochName & ...
                    StateWindows.operationalState == stateName & ...
                    ~logical( ...
                    StateWindows.isArtefactOrUnusable);

                candidateCenters = double( ...
                    StateWindows.windowCenterUs(windowMask));

                keepCenters = true(size(candidateCenters));

                for centerIndex = 1:numel(candidateCenters)
                    if any(abs( ...
                            allEpochPeaks- ...
                            candidateCenters(centerIndex)) <= ...
                            pseudoExclusionSec*1e6)
                        keepCenters(centerIndex) = false;
                    end
                end

                candidateCenters = ...
                    candidateCenters(keepCenters);

                if ~isempty(candidateCenters)
                    candidateCenters = ...
                        candidateCenters( ...
                        randperm(numel(candidateCenters)));
                end

                fieldName = matlab.lang.makeValidName( ...
                    char(stateName));

                pseudoPools.(fieldName) = candidateCenters;
            end
        end

        pseudoPoolCounters = struct();

        for localEventIndex = 1:numel(eventRows)
            rowIndex = eventRows(localEventIndex);
            peakUs = double(Events.peakUs(rowIndex));

            centralCounts = zeros(nUnits,1);
            leftCounts = zeros(nUnits,1);
            rightCounts = zeros(nUnits,1);
            pethCounts = zeros(nUnits,nBins);

            for unitIndex = usableUnits(:)'
                spikeTimes = spikeCell{unitIndex};
                relativeSec = ...
                    (spikeTimes-peakUs)/1e6;

                pethMask = ...
                    relativeSec >= -pethHalfWindowSec & ...
                    relativeSec < pethHalfWindowSec;

                if any(pethMask)
                    pethCounts(unitIndex,:) = histcounts( ...
                        relativeSec(pethMask), ...
                        pethEdges);
                end

                centralCounts(unitIndex) = sum( ...
                    relativeSec >= centralWindow(1) & ...
                    relativeSec < centralWindow(2));

                leftCounts(unitIndex) = sum( ...
                    relativeSec >= leftFlankWindow(1) & ...
                    relativeSec < leftFlankWindow(2));

                rightCounts(unitIndex) = sum( ...
                    relativeSec >= rightFlankWindow(1) & ...
                    relativeSec < rightFlankWindow(2));
            end

            flankCounts = leftCounts+rightCounts;
            nUsable = numel(usableUnits);

            nUsableUnits(rowIndex) = nUsable;

            centralRateHzPerUnit(rowIndex) = ...
                sum(centralCounts(usableUnits)) / ...
                (nUsable*centralDurationSec);

            flankRateHzPerUnit(rowIndex) = ...
                sum(flankCounts(usableUnits)) / ...
                (nUsable*flankDurationSec);

            centralMinusFlankRate(rowIndex) = ...
                centralRateHzPerUnit(rowIndex)- ...
                flankRateHzPerUnit(rowIndex);

            centralActiveFraction(rowIndex) = ...
                mean(centralCounts(usableUnits) >= 1);

            flankActiveFraction(rowIndex) = mean([ ...
                mean(leftCounts(usableUnits) >= 1), ...
                mean(rightCounts(usableUnits) >= 1)]);

            centralMinusFlankActiveFraction(rowIndex) = ...
                centralActiveFraction(rowIndex)- ...
                flankActiveFraction(rowIndex);

            eventPethRate(rowIndex,:) = ...
                sum(pethCounts(usableUnits,:),1) / ...
                (nUsable*pethBinSec);

            taggedMask = usableMask & isBeta2Tagged;
            untaggedMask = usableMask & ~isBeta2Tagged;
            novelMask = usableMask & isNovelTagged;

            if any(taggedMask)
                beta2TaggedNUnits(rowIndex) = sum(taggedMask);

                taggedCentral = ...
                    sum(centralCounts(taggedMask)) / ...
                    (sum(taggedMask)*centralDurationSec);

                taggedFlank = ...
                    sum(flankCounts(taggedMask)) / ...
                    (sum(taggedMask)*flankDurationSec);

                beta2TaggedCentralMinusFlankRate(rowIndex) = ...
                    taggedCentral-taggedFlank;
            end

            if any(untaggedMask)
                untaggedNUnits(rowIndex) = sum(untaggedMask);

                untaggedCentral = ...
                    sum(centralCounts(untaggedMask)) / ...
                    (sum(untaggedMask)*centralDurationSec);

                untaggedFlank = ...
                    sum(flankCounts(untaggedMask)) / ...
                    (sum(untaggedMask)*flankDurationSec);

                untaggedCentralMinusFlankRate(rowIndex) = ...
                    untaggedCentral-untaggedFlank;
            end

            if any(novelMask)
                novelBeta2TaggedNUnits(rowIndex) = sum(novelMask);

                novelCentral = ...
                    sum(centralCounts(novelMask)) / ...
                    (sum(novelMask)*centralDurationSec);

                novelFlank = ...
                    sum(flankCounts(novelMask)) / ...
                    (sum(novelMask)*flankDurationSec);

                novelBeta2TaggedCentralMinusFlankRate(rowIndex) = ...
                    novelCentral-novelFlank;
            end

            % State-matched pseudo-event control for sleep epochs.
            if epochName ~= "RUN1AWAKE"
                stateName = ...
                    Events.operationalStateAtPeak(rowIndex);

                fieldName = matlab.lang.makeValidName( ...
                    char(stateName));

                if isfield(pseudoPools,fieldName)
                    pool = pseudoPools.(fieldName);

                    if ~isempty(pool)
                        if ~isfield(pseudoPoolCounters,fieldName)
                            pseudoPoolCounters.(fieldName) = 1;
                        end

                        poolIndex = ...
                            pseudoPoolCounters.(fieldName);

                        if poolIndex > numel(pool)
                            poolIndex = ...
                                mod(poolIndex-1,numel(pool))+1;
                        end

                        controlUs = pool(poolIndex);
                        pseudoPoolCounters.(fieldName) = ...
                            poolIndex+1;
                        pseudoPeakUs(rowIndex) = controlUs;

                        controlCentralCounts = zeros(nUnits,1);
                        controlPethCounts = zeros(nUnits,nBins);

                        for unitIndex = usableUnits(:)'
                            spikeTimes = spikeCell{unitIndex};
                            relativeSec = ...
                                (spikeTimes-controlUs)/1e6;

                            pethMask = ...
                                relativeSec >= ...
                                    -pethHalfWindowSec & ...
                                relativeSec < ...
                                    pethHalfWindowSec;

                            if any(pethMask)
                                controlPethCounts(unitIndex,:) = ...
                                    histcounts( ...
                                    relativeSec(pethMask), ...
                                    pethEdges);
                            end

                            controlCentralCounts(unitIndex) = ...
                                sum( ...
                                relativeSec >= ...
                                    centralWindow(1) & ...
                                relativeSec < ...
                                    centralWindow(2));
                        end

                        pseudoCentralRateHzPerUnit(rowIndex) = ...
                            sum(controlCentralCounts(usableUnits)) / ...
                            (nUsable*centralDurationSec);

                        pseudoCentralActiveFraction(rowIndex) = ...
                            mean( ...
                            controlCentralCounts(usableUnits) >= 1);

                        eventMinusPseudoRate(rowIndex) = ...
                            centralRateHzPerUnit(rowIndex)- ...
                            pseudoCentralRateHzPerUnit(rowIndex);

                        eventMinusPseudoActiveFraction(rowIndex) = ...
                            centralActiveFraction(rowIndex)- ...
                            pseudoCentralActiveFraction(rowIndex);

                        pseudoPethRate(rowIndex,:) = ...
                            sum(controlPethCounts(usableUnits,:),1) / ...
                            (nUsable*pethBinSec);
                    end
                end
            end
        end
    end
end

%% Event-level output

EventRecruitment = Events;

EventRecruitment.nUsableUnits = nUsableUnits;
EventRecruitment.centralRateHzPerUnit = ...
    centralRateHzPerUnit;
EventRecruitment.flankRateHzPerUnit = ...
    flankRateHzPerUnit;
EventRecruitment.centralMinusFlankRateHzPerUnit = ...
    centralMinusFlankRate;
EventRecruitment.centralActiveUnitFraction = ...
    centralActiveFraction;
EventRecruitment.flankActiveUnitFraction = ...
    flankActiveFraction;
EventRecruitment.centralMinusFlankActiveFraction = ...
    centralMinusFlankActiveFraction;

EventRecruitment.pseudoPeakUs = pseudoPeakUs;
EventRecruitment.pseudoCentralRateHzPerUnit = ...
    pseudoCentralRateHzPerUnit;
EventRecruitment.pseudoCentralActiveUnitFraction = ...
    pseudoCentralActiveFraction;
EventRecruitment.eventMinusPseudoRateHzPerUnit = ...
    eventMinusPseudoRate;
EventRecruitment.eventMinusPseudoActiveFraction = ...
    eventMinusPseudoActiveFraction;

EventRecruitment.beta2TaggedNUnits = ...
    beta2TaggedNUnits;
EventRecruitment.beta2TaggedCentralMinusFlankRate = ...
    beta2TaggedCentralMinusFlankRate;
EventRecruitment.untaggedNUnits = ...
    untaggedNUnits;
EventRecruitment.untaggedCentralMinusFlankRate = ...
    untaggedCentralMinusFlankRate;
EventRecruitment.novelBeta2TaggedNUnits = ...
    novelBeta2TaggedNUnits;
EventRecruitment.novelBeta2TaggedCentralMinusFlankRate = ...
    novelBeta2TaggedCentralMinusFlankRate;

writetable(EventRecruitment,fullfile(outputFolder, ...
    'hc31_batch11O_event_level_population_recruitment.csv'));

%% Event-rate table

setNames = [ ...
    "TierA", ...
    "TierAB", ...
    "TierAC", ...
    "TierABC", ...
    "TierABCD"];

stateGroupNames = [ ...
    "NREM", ...
    "NREMPlusIntermediate", ...
    "ThetaDominant"];

sleepEpochs = ["PRE","REST","POST"];
animals = string(fallbackAnimalIDs);

rateRows = {};

for setIndex = 1:numel(setNames)
    setName = setNames(setIndex);

    if setName == "TierA"
        setMask = isTierA;
    elseif setName == "TierAB"
        setMask = isTierA | isTierB;
    elseif setName == "TierAC"
        setMask = isTierA | isTierC;
    elseif setName == "TierABC"
        setMask = isTierA | isTierB | isTierC;
    else
        setMask = isTierA | isTierB | isTierC | isTierD;
    end

    for stateGroupIndex = 1:numel(stateGroupNames)
        stateGroupName = ...
            stateGroupNames(stateGroupIndex);

        for animalIndex = 1:numel(animals)
            animalID = animals(animalIndex);

            for epochIndex = 1:numel(sleepEpochs)
                epochName = sleepEpochs(epochIndex);

                if stateGroupName == "NREM"
                    stateMaskMaster = contains( ...
                        Master.operationalStateAtPeak, ...
                        "NREM", ...
                        'IgnoreCase',true);

                    stateMaskSummary = contains( ...
                        StateSummary.operationalState, ...
                        "NREM", ...
                        'IgnoreCase',true);

                elseif stateGroupName == ...
                        "NREMPlusIntermediate"

                    stateMaskMaster = ...
                        contains( ...
                        Master.operationalStateAtPeak, ...
                        "NREM", ...
                        'IgnoreCase',true) | ...
                        contains( ...
                        Master.operationalStateAtPeak, ...
                        "Intermediate", ...
                        'IgnoreCase',true);

                    stateMaskSummary = ...
                        contains( ...
                        StateSummary.operationalState, ...
                        "NREM", ...
                        'IgnoreCase',true) | ...
                        contains( ...
                        StateSummary.operationalState, ...
                        "Intermediate", ...
                        'IgnoreCase',true);
                else
                    stateMaskMaster = contains( ...
                        Master.operationalStateAtPeak, ...
                        "Theta-dominant", ...
                        'IgnoreCase',true);

                    stateMaskSummary = contains( ...
                        StateSummary.operationalState, ...
                        "Theta-dominant", ...
                        'IgnoreCase',true);
                end

                eventMask = ...
                    setMask & ...
                    Master.animal == animalID & ...
                    Master.epoch == epochName & ...
                    stateMaskMaster;

                durationMask = ...
                    StateSummary.animal == animalID & ...
                    StateSummary.epoch == epochName & ...
                    stateMaskSummary;

                durationMin = sum( ...
                    double(StateSummary.stateDurationMin( ...
                    durationMask)), ...
                    'omitnan');

                nEvents = sum(eventMask);
                ratePerMin = NaN;

                if durationMin > 0
                    ratePerMin = nEvents/durationMin;
                end

                rateRows(end+1,:) = { ...
                    char(setName), ...
                    char(stateGroupName), ...
                    char(animalID), ...
                    char(epochName), ...
                    durationMin, ...
                    nEvents, ...
                    ratePerMin}; %#ok<SAGROW>
            end
        end
    end
end

RateTable = cell2table(rateRows, ...
    'VariableNames', { ...
    'eventSet', ...
    'stateGroup', ...
    'animal', ...
    'epoch', ...
    'stateDurationMin', ...
    'nEvents', ...
    'eventRatePerMinute'});

writetable(RateTable,fullfile(outputFolder, ...
    'hc31_batch11O_state_matched_event_rates.csv'));

%% Animal-level recruitment summaries

recruitmentStateGroups = [ ...
    "NREM", ...
    "NREMPlusIntermediate", ...
    "ThetaDominant", ...
    "Awake"];

summaryRows = {};

for setIndex = 1:numel(setNames)
    setName = setNames(setIndex);

    if setName == "TierA"
        setMask = EventRecruitment.inSetTierA;
    elseif setName == "TierAB"
        setMask = EventRecruitment.inSetTierAB;
    elseif setName == "TierAC"
        setMask = EventRecruitment.inSetTierAC;
    elseif setName == "TierABC"
        setMask = EventRecruitment.inSetTierABC;
    else
        setMask = EventRecruitment.inSetTierABCD;
    end

    for stateGroupIndex = 1:numel(recruitmentStateGroups)
        stateGroupName = ...
            recruitmentStateGroups(stateGroupIndex);

        if stateGroupName == "NREM"
            stateMask = ...
                EventRecruitment.stateGroup == "NREM";
        elseif stateGroupName == "NREMPlusIntermediate"
            stateMask = ...
                EventRecruitment.stateGroup == "NREM" | ...
                EventRecruitment.stateGroup == "Intermediate";
        elseif stateGroupName == "ThetaDominant"
            stateMask = ...
                EventRecruitment.stateGroup == ...
                "ThetaDominant";
        else
            stateMask = ...
                EventRecruitment.stateGroup == "Awake";
        end

        for animalIndex = 1:numel(animals)
            animalID = animals(animalIndex);

            for epochIndex = 1:numel(epochNames)
                epochName = epochNames(epochIndex);

                mask = ...
                    setMask & ...
                    stateMask & ...
                    EventRecruitment.animal == animalID & ...
                    EventRecruitment.epoch == epochName & ...
                    isfinite( ...
                    EventRecruitment. ...
                    centralMinusFlankRateHzPerUnit);

                nEvents = sum(mask);

                if nEvents == 0
                    continue
                end

                summaryRows(end+1,:) = { ...
                    char(setName), ...
                    char(stateGroupName), ...
                    char(animalID), ...
                    char(epochName), ...
                    nEvents, ...
                    mean( ...
                    EventRecruitment. ...
                    centralRateHzPerUnit(mask), ...
                    'omitnan'), ...
                    mean( ...
                    EventRecruitment. ...
                    flankRateHzPerUnit(mask), ...
                    'omitnan'), ...
                    mean( ...
                    EventRecruitment. ...
                    centralMinusFlankRateHzPerUnit(mask), ...
                    'omitnan'), ...
                    mean( ...
                    EventRecruitment. ...
                    centralMinusFlankActiveFraction(mask), ...
                    'omitnan'), ...
                    mean( ...
                    EventRecruitment. ...
                    eventMinusPseudoRateHzPerUnit(mask), ...
                    'omitnan'), ...
                    mean( ...
                    EventRecruitment. ...
                    eventMinusPseudoActiveFraction(mask), ...
                    'omitnan'), ...
                    mean( ...
                    EventRecruitment. ...
                    beta2TaggedCentralMinusFlankRate(mask), ...
                    'omitnan'), ...
                    mean( ...
                    EventRecruitment. ...
                    untaggedCentralMinusFlankRate(mask), ...
                    'omitnan'), ...
                    mean( ...
                    EventRecruitment. ...
                    novelBeta2TaggedCentralMinusFlankRate(mask), ...
                    'omitnan')}; %#ok<SAGROW>
            end
        end
    end
end

AnimalSummary = cell2table(summaryRows, ...
    'VariableNames', { ...
    'eventSet', ...
    'stateGroup', ...
    'animal', ...
    'epoch', ...
    'nEvents', ...
    'centralRateHzPerUnit', ...
    'flankRateHzPerUnit', ...
    'centralMinusFlankRateHzPerUnit', ...
    'centralMinusFlankActiveFraction', ...
    'eventMinusPseudoRateHzPerUnit', ...
    'eventMinusPseudoActiveFraction', ...
    'beta2TaggedCentralMinusFlankRate', ...
    'untaggedCentralMinusFlankRate', ...
    'novelBeta2TaggedCentralMinusFlankRate'});

writetable(AnimalSummary,fullfile(outputFolder, ...
    'hc31_batch11O_animal_level_population_recruitment.csv'));

%% Aggregate PETH output

pethRows = {};

for setIndex = 1:numel(setNames)
    setName = setNames(setIndex);

    if setName == "TierA"
        setMask = EventRecruitment.inSetTierA;
    elseif setName == "TierAB"
        setMask = EventRecruitment.inSetTierAB;
    elseif setName == "TierAC"
        setMask = EventRecruitment.inSetTierAC;
    elseif setName == "TierABC"
        setMask = EventRecruitment.inSetTierABC;
    else
        setMask = EventRecruitment.inSetTierABCD;
    end

    for stateGroupIndex = 1:numel(recruitmentStateGroups)
        stateGroupName = ...
            recruitmentStateGroups(stateGroupIndex);

        if stateGroupName == "NREM"
            stateMask = ...
                EventRecruitment.stateGroup == "NREM";
        elseif stateGroupName == "NREMPlusIntermediate"
            stateMask = ...
                EventRecruitment.stateGroup == "NREM" | ...
                EventRecruitment.stateGroup == "Intermediate";
        elseif stateGroupName == "ThetaDominant"
            stateMask = ...
                EventRecruitment.stateGroup == "ThetaDominant";
        else
            stateMask = ...
                EventRecruitment.stateGroup == "Awake";
        end

        for epochIndex = 1:numel(epochNames)
            epochName = epochNames(epochIndex);

            animalPeth = [];
            animalPseudoPeth = [];
            nEventsByAnimal = [];

            for animalIndex = 1:numel(animals)
                animalID = animals(animalIndex);

                mask = ...
                    setMask & ...
                    stateMask & ...
                    EventRecruitment.animal == animalID & ...
                    EventRecruitment.epoch == epochName;

                validRows = find(mask & ...
                    isfinite(eventPethRate(:,1)));

                if isempty(validRows)
                    continue
                end

                animalPeth(end+1,:) = mean( ...
                    eventPethRate(validRows,:), ...
                    1, ...
                    'omitnan'); %#ok<SAGROW>

                animalPseudoPeth(end+1,:) = mean( ...
                    pseudoPethRate(validRows,:), ...
                    1, ...
                    'omitnan'); %#ok<SAGROW>

                nEventsByAnimal(end+1,1) = ...
                    numel(validRows); %#ok<SAGROW>
            end

            if isempty(animalPeth)
                continue
            end

            meanEventPeth = mean( ...
                animalPeth,1,'omitnan');

            semEventPeth = std( ...
                animalPeth,0,1,'omitnan') / ...
                sqrt(size(animalPeth,1));

            meanPseudoPeth = mean( ...
                animalPseudoPeth,1,'omitnan');

            semPseudoPeth = std( ...
                animalPseudoPeth,0,1,'omitnan') / ...
                sqrt(size(animalPseudoPeth,1));

            for binIndex = 1:nBins
                pethRows(end+1,:) = { ...
                    char(setName), ...
                    char(stateGroupName), ...
                    char(epochName), ...
                    pethCenters(binIndex), ...
                    meanEventPeth(binIndex), ...
                    semEventPeth(binIndex), ...
                    meanPseudoPeth(binIndex), ...
                    semPseudoPeth(binIndex), ...
                    size(animalPeth,1), ...
                    sum(nEventsByAnimal)}; %#ok<SAGROW>
            end
        end
    end
end

PethTable = cell2table(pethRows, ...
    'VariableNames', { ...
    'eventSet', ...
    'stateGroup', ...
    'epoch', ...
    'timeFromEventSec', ...
    'meanEventPopulationRateHzPerUnit', ...
    'semEventPopulationRateHzPerUnit', ...
    'meanPseudoPopulationRateHzPerUnit', ...
    'semPseudoPopulationRateHzPerUnit', ...
    'nAnimals', ...
    'nEvents'});

writetable(PethTable,fullfile(outputFolder, ...
    'hc31_batch11O_animal_weighted_population_PETH.csv'));

%% Statistical tests

statRows = {};

metrics = { ...
    'centralMinusFlankRateHzPerUnit', ...
    'centralMinusFlankActiveFraction', ...
    'eventMinusPseudoRateHzPerUnit', ...
    'eventMinusPseudoActiveFraction'};

for setIndex = 1:numel(setNames)
    setName = setNames(setIndex);

    for stateGroupIndex = 1:numel(recruitmentStateGroups)
        stateGroupName = ...
            recruitmentStateGroups(stateGroupIndex);

        for epochIndex = 1:numel(epochNames)
            epochName = epochNames(epochIndex);

            mask = ...
                string(AnimalSummary.eventSet) == setName & ...
                string(AnimalSummary.stateGroup) == ...
                    stateGroupName & ...
                string(AnimalSummary.epoch) == epochName;

            for metricIndex = 1:numel(metrics)
                metricName = metrics{metricIndex};
                values = double( ...
                    AnimalSummary.(metricName)(mask));

                values = values(isfinite(values));
                pValue = NaN;
                signedRank = NaN;

                if numel(values) >= minimumAnimalsForTest
                    try
                        [pValue,~,stats] = signrank(values,0);
                        signedRank = stats.signedrank;
                    catch
                    end
                end

                statRows(end+1,:) = { ...
                    'oneSampleAgainstZero', ...
                    char(setName), ...
                    char(stateGroupName), ...
                    char(epochName), ...
                    '', ...
                    metricName, ...
                    numel(values), ...
                    mean(values,'omitnan'), ...
                    median(values,'omitnan'), ...
                    pValue, ...
                    signedRank}; %#ok<SAGROW>
            end
        end
    end
end

epochPairs = { ...
    'PRE','REST'; ...
    'REST','POST'; ...
    'PRE','POST'};

for setIndex = 1:numel(setNames)
    setName = setNames(setIndex);

    for stateGroupIndex = 1:numel(stateGroupNames)
        stateGroupName = ...
            stateGroupNames(stateGroupIndex);

        for metricIndex = 1:numel(metrics)
            metricName = metrics{metricIndex};

            for pairIndex = 1:size(epochPairs,1)
                epochA = string(epochPairs{pairIndex,1});
                epochB = string(epochPairs{pairIndex,2});

                A = AnimalSummary( ...
                    string(AnimalSummary.eventSet) == setName & ...
                    string(AnimalSummary.stateGroup) == ...
                        stateGroupName & ...
                    string(AnimalSummary.epoch) == epochA, ...
                    {'animal',metricName});

                B = AnimalSummary( ...
                    string(AnimalSummary.eventSet) == setName & ...
                    string(AnimalSummary.stateGroup) == ...
                        stateGroupName & ...
                    string(AnimalSummary.epoch) == epochB, ...
                    {'animal',metricName});

                if isempty(A) || isempty(B)
                    continue
                end

                Joined = innerjoin(A,B, ...
                    'Keys','animal', ...
                    'LeftVariables',{'animal',metricName}, ...
                    'RightVariables',{metricName});

                if width(Joined) < 3
                    continue
                end

                valuesA = double(Joined{:,2});
                valuesB = double(Joined{:,3});
                valid = isfinite(valuesA) & ...
                    isfinite(valuesB);

                pValue = NaN;
                signedRank = NaN;

                if sum(valid) >= minimumAnimalsForTest
                    try
                        [pValue,~,stats] = signrank( ...
                            valuesA(valid), ...
                            valuesB(valid));

                        signedRank = stats.signedrank;
                    catch
                    end
                end

                statRows(end+1,:) = { ...
                    'pairedEpochComparison', ...
                    char(setName), ...
                    char(stateGroupName), ...
                    char(epochA), ...
                    char(epochB), ...
                    metricName, ...
                    sum(valid), ...
                    mean( ...
                    valuesB(valid)-valuesA(valid), ...
                    'omitnan'), ...
                    median( ...
                    valuesB(valid)-valuesA(valid), ...
                    'omitnan'), ...
                    pValue, ...
                    signedRank}; %#ok<SAGROW>
            end
        end
    end
end

RecruitmentStats = cell2table(statRows, ...
    'VariableNames', { ...
    'testType', ...
    'eventSet', ...
    'stateGroup', ...
    'epochA', ...
    'epochB', ...
    'metric', ...
    'nAnimals', ...
    'meanEffectOrDifference', ...
    'medianEffectOrDifference', ...
    'pValue', ...
    'signedRank'});

RecruitmentStats.qValueBH = ...
    hc31_batch11O_bh_fdr( ...
    RecruitmentStats.pValue);

writetable(RecruitmentStats,fullfile(outputFolder, ...
    'hc31_batch11O_population_recruitment_statistics.csv'));

%% Event-rate statistics

rateStatRows = {};

for setIndex = 1:numel(setNames)
    setName = setNames(setIndex);

    for stateGroupIndex = 1:numel(stateGroupNames)
        stateGroupName = ...
            stateGroupNames(stateGroupIndex);

        for pairIndex = 1:size(epochPairs,1)
            epochA = string(epochPairs{pairIndex,1});
            epochB = string(epochPairs{pairIndex,2});

            A = RateTable( ...
                string(RateTable.eventSet) == setName & ...
                string(RateTable.stateGroup) == ...
                    stateGroupName & ...
                string(RateTable.epoch) == epochA, ...
                {'animal','eventRatePerMinute'});

            B = RateTable( ...
                string(RateTable.eventSet) == setName & ...
                string(RateTable.stateGroup) == ...
                    stateGroupName & ...
                string(RateTable.epoch) == epochB, ...
                {'animal','eventRatePerMinute'});

            Joined = innerjoin(A,B, ...
                'Keys','animal', ...
                'LeftVariables', { ...
                'animal','eventRatePerMinute'}, ...
                'RightVariables', { ...
                'eventRatePerMinute'});

            if width(Joined) < 3
                continue
            end

            valuesA = double(Joined{:,2});
            valuesB = double(Joined{:,3});

            valid = ...
                isfinite(valuesA) & ...
                isfinite(valuesB);

            pValue = NaN;
            signedRank = NaN;

            if sum(valid) >= minimumAnimalsForTest
                try
                    [pValue,~,stats] = signrank( ...
                        valuesA(valid), ...
                        valuesB(valid));

                    signedRank = stats.signedrank;
                catch
                end
            end

            rateStatRows(end+1,:) = { ...
                char(setName), ...
                char(stateGroupName), ...
                char(epochA), ...
                char(epochB), ...
                sum(valid), ...
                mean(valuesA(valid),'omitnan'), ...
                mean(valuesB(valid),'omitnan'), ...
                mean(valuesB(valid)-valuesA(valid), ...
                    'omitnan'), ...
                pValue, ...
                signedRank}; %#ok<SAGROW>
        end
    end
end

RateStats = cell2table(rateStatRows, ...
    'VariableNames', { ...
    'eventSet', ...
    'stateGroup', ...
    'epochA', ...
    'epochB', ...
    'nAnimals', ...
    'meanRateA', ...
    'meanRateB', ...
    'meanRateDifferenceBMinusA', ...
    'pValue', ...
    'signedRank'});

RateStats.qValueBH = ...
    hc31_batch11O_bh_fdr(RateStats.pValue);

writetable(RateStats,fullfile(outputFolder, ...
    'hc31_batch11O_state_matched_event_rate_statistics.csv'));

%% Leave-one-animal-out and ANM228899 sensitivity

looRows = {};

primaryMask = ...
    string(AnimalSummary.eventSet) == "TierAC" & ...
    string(AnimalSummary.stateGroup) == "NREM";

for heldOutIndex = 0:numel(animals)
    if heldOutIndex == 0
        heldOutAnimal = "None";
        keepMask = primaryMask;
    else
        heldOutAnimal = animals(heldOutIndex);
        keepMask = ...
            primaryMask & ...
            string(AnimalSummary.animal) ~= ...
                heldOutAnimal;
    end

    for epochIndex = 1:numel(sleepEpochs)
        epochName = sleepEpochs(epochIndex);

        values = double( ...
            AnimalSummary. ...
            centralMinusFlankRateHzPerUnit( ...
            keepMask & ...
            string(AnimalSummary.epoch) == ...
                epochName));

        looRows(end+1,:) = { ...
            char(heldOutAnimal), ...
            char(epochName), ...
            sum(isfinite(values)), ...
            mean(values,'omitnan'), ...
            median(values,'omitnan')}; %#ok<SAGROW>
    end
end

LOOSummary = cell2table(looRows, ...
    'VariableNames', { ...
    'heldOutAnimal', ...
    'epoch', ...
    'nAnimals', ...
    'meanCentralMinusFlankRate', ...
    'medianCentralMinusFlankRate'});

writetable(LOOSummary,fullfile(outputFolder, ...
    'hc31_batch11O_leave_one_animal_out_recruitment.csv'));

%% Figures

% Primary Tier A+C NREM population PETH.
fig = figure( ...
    'Visible','off', ...
    'Color','w', ...
    'Position',[80 80 1250 760]);

hold on

for epochIndex = 1:numel(sleepEpochs)
    epochName = sleepEpochs(epochIndex);

    plotMask = ...
        string(PethTable.eventSet) == "TierAC" & ...
        string(PethTable.stateGroup) == "NREM" & ...
        string(PethTable.epoch) == epochName;

    if any(plotMask)
        plot( ...
            PethTable.timeFromEventSec(plotMask), ...
            PethTable. ...
            meanEventPopulationRateHzPerUnit(plotMask), ...
            'LineWidth',1.8);
    end
end

xline(0,'k--');
xline(centralWindow(1),':');
xline(centralWindow(2),':');
xlabel('Time from event peak (s)');
ylabel('Population spike rate (Hz/unit)');
title('Tier A+C, NREM-compatible state: CA1 population recruitment');
legend(cellstr(sleepEpochs),'Location','best');
grid on
box off

exportgraphics(fig,fullfile(figureFolder, ...
    'batch11O_TierAC_NREM_population_PETH.png'), ...
    'Resolution',200);

close(fig);

% Animal-level recruitment effect.
primarySummary = AnimalSummary( ...
    string(AnimalSummary.eventSet) == "TierAC" & ...
    string(AnimalSummary.stateGroup) == "NREM" & ...
    ismember(string(AnimalSummary.epoch),sleepEpochs),:);

fig = figure( ...
    'Visible','off', ...
    'Color','w', ...
    'Position',[80 80 1100 700]);

hold on

for animalIndex = 1:numel(animals)
    animalMask = ...
        string(primarySummary.animal) == ...
        animals(animalIndex);

    if any(animalMask)
        [~,order] = ismember( ...
            string(primarySummary.epoch(animalMask)), ...
            sleepEpochs);

        [order,sortOrder] = sort(order);

        plot( ...
            order, ...
            primarySummary. ...
            centralMinusFlankRateHzPerUnit( ...
            find(animalMask,1)-1+sortOrder), ...
            '-o', ...
            'LineWidth',1.1);
    end
end

xlim([0.5 3.5]);
xticks(1:3);
xticklabels(cellstr(sleepEpochs));
yline(0,'k--');
ylabel('Central - flank rate (Hz/unit)');
title('Tier A+C NREM recruitment by animal');
grid on
box off

exportgraphics(fig,fullfile(figureFolder, ...
    'batch11O_TierAC_NREM_animal_recruitment.png'), ...
    'Resolution',200);

close(fig);

% State-matched event rates.
primaryRates = RateTable( ...
    string(RateTable.eventSet) == "TierAC" & ...
    string(RateTable.stateGroup) == "NREM",:);

fig = figure( ...
    'Visible','off', ...
    'Color','w', ...
    'Position',[80 80 1100 700]);

hold on

for animalIndex = 1:numel(animals)
    animalMask = ...
        string(primaryRates.animal) == ...
        animals(animalIndex);

    if any(animalMask)
        [~,order] = ismember( ...
            string(primaryRates.epoch(animalMask)), ...
            sleepEpochs);

        [order,sortOrder] = sort(order);
        values = primaryRates. ...
            eventRatePerMinute(animalMask);
        values = values(sortOrder);

        plot(order,values,'-o','LineWidth',1.1);
    end
end

xlim([0.5 3.5]);
xticks(1:3);
xticklabels(cellstr(sleepEpochs));
ylabel('Events per minute');
title('Tier A+C NREM-compatible screened event rates');
grid on
box off

exportgraphics(fig,fullfile(figureFolder, ...
    'batch11O_TierAC_NREM_event_rates.png'), ...
    'Resolution',200);

close(fig);

% Tier sensitivity.
fig = figure( ...
    'Visible','off', ...
    'Color','w', ...
    'Position',[80 80 1150 700]);

tierPlotRows = AnimalSummary( ...
    ismember(string(AnimalSummary.eventSet), ...
    ["TierA","TierAB","TierAC","TierABC"]) & ...
    string(AnimalSummary.stateGroup) == "NREM" & ...
    string(AnimalSummary.epoch) == "REST",:);

tierPlotNames = ["TierA","TierAB","TierAC","TierABC"];
tierMeans = nan(numel(tierPlotNames),1);
tierSem = nan(numel(tierPlotNames),1);

for tierIndex = 1:numel(tierPlotNames)
    values = double( ...
        tierPlotRows. ...
        centralMinusFlankRateHzPerUnit( ...
        string(tierPlotRows.eventSet) == ...
        tierPlotNames(tierIndex)));

    tierMeans(tierIndex) = ...
        mean(values,'omitnan');

    tierSem(tierIndex) = ...
        std(values,0,'omitnan') / ...
        sqrt(sum(isfinite(values)));
end

bar(categorical(tierPlotNames),tierMeans);
hold on
errorbar(1:numel(tierMeans), ...
    tierMeans,tierSem, ...
    'k.','LineWidth',1.2);
yline(0,'k--');
ylabel('Central - flank rate (Hz/unit)');
title('REST NREM recruitment sensitivity to event-set definition');
grid on
box off

exportgraphics(fig,fullfile(figureFolder, ...
    'batch11O_REST_NREM_tier_sensitivity.png'), ...
    'Resolution',200);

close(fig);

%% Text summary

fid = fopen(fullfile(outputFolder, ...
    'hc31_batch11O_STAGE_A_SUMMARY.txt'),'w');

if fid >= 0
    fprintf(fid, ...
        'HC-31 Batch 11O Stage A\n');
    fprintf(fid, ...
        'Validated population recruitment and state-matched rates\n');
    fprintf(fid, ...
        '========================================================\n\n');

    fprintf(fid,'Corrected master table:\n%s\n\n',masterPath);
    fprintf(fid,'Permanent Tier A-D events analysed: %d\n', ...
        height(EventRecruitment));
    fprintf(fid,'PETH bin: %.1f ms\n',pethBinSec*1000);
    fprintf(fid,'Central window: %.0f to %.0f ms\n', ...
        centralWindow(1)*1000, ...
        centralWindow(2)*1000);
    fprintf(fid,'Epoch spike mapping: PRE 1, Run1 2, REST 3, POST 4\n\n');

    fprintf(fid,'Primary inference set\n');
    fprintf(fid,'---------------------\n');
    fprintf(fid,[ ...
        'Tier A+C, NREM-compatible state, animal-weighted. ', ...
        'Tier A, A+B and A+B+C are sensitivity sets.\n\n']);

    fprintf(fid,'Interpretation boundaries\n');
    fprintf(fid,'-------------------------\n');
    fprintf(fid,[ ...
        'Event-level rows are not independent biological replicates.\n']);
    fprintf(fid,[ ...
        'POST events are automatically screened and not manually reviewed.\n']);
    fprintf(fid,[ ...
        'Beta2 unit-tag analyses are exploratory and run only when a ', ...
        'compatible unit-tag CSV was supplied.\n']);
    fprintf(fid,[ ...
        'PRE/REST and POST were proposed by different broad source ', ...
        'detectors before receiving the same L2 morphology screen.\n']);

    fclose(fid);
end

fprintf('\nBatch 11O Stage A complete.\n');
fprintf('Output folder:\n  %s\n',outputFolder);
