%% HC-31 Batch 11O
% RUN1-AWAKE BETA2 COUPLING WITH SPEED/ACCELERATION-MATCHED CONTROLS
%
% Plain script: no local functions.
%
% Every eligible Run1-awake event is paired with a pseudo-time from the same
% animal, matched on speed, acceleration, speed change and movement stability.
% Event and control beta2 envelopes are extracted identically from raw CSC.

clearvars -except scriptFile scriptFolder txt
clc
close all
rehash

fprintf('\nHC-31 Batch 11O Stage B\n');
fprintf('Run1-awake beta2 coupling with movement-matched controls\n');
fprintf('--------------------------------------------------------\n');

%% Settings

defaultRoot = getenv('HC31_DATA_ROOT');

animalIndices = 5:9;
fallbackAnimalIDs = { ...
    'ANM00190422', ...
    'ANM204878', ...
    'ANM212379', ...
    'ANM228899', ...
    'ANM228900'};

lowSpeedThresholdCmS = 5;
stableSpeedChangeThresholdCmS = 1;
stableAccelerationThresholdCmS2 = 2;

controlGridStepSec = 0.50;
controlEventExclusionSec = 2.0;
controlMinimumEdgeSec = 3.2;

speedMatchToleranceCmS = 0.75;
accelerationMatchToleranceCmS2 = 1.5;
speedChangeMatchToleranceCmS = 1.0;

maximumPairsThisInvocationSmoke = 20;
checkpointEveryNPairs = 20;

settings = struct();
settings.beta2BandHz = [23 30];
settings.beta2FilterOrder = 4;
settings.beta2TargetFs = 250;
settings.beta2LoadHalfWindowSec = 3.0;
settings.beta2PethHalfWindowSec = 2.0;
settings.beta2PethBinSec = 0.050;
settings.beta2PethEdges = ...
    -settings.beta2PethHalfWindowSec: ...
    settings.beta2PethBinSec: ...
    settings.beta2PethHalfWindowSec;
settings.beta2PethCenters = ...
    settings.beta2PethEdges(1:end-1)+ ...
    settings.beta2PethBinSec/2;
settings.beta2BaselineExclusionSec = 1.2;
settings.beta2EnvelopeSmoothSec = 0.050;
settings.beta2PreWindow = [-1.0 -0.2];
settings.beta2CentralWindow = [-0.1 0.1];
settings.beta2EarlyPostWindow = [0.2 1.0];
settings.beta2LatePostWindow = [1.0 2.0];
settings.beta2BurstThresholdZ = 2.0;
settings.beta2BurstMinDurationSec = 0.100;

rng(31,'twister');

%% Helpers and root

if exist('scriptFolder','var') && ...
        exist(scriptFolder,'dir') == 7
    addpath(scriptFolder);
else
    thisScriptPath = mfilename('fullpath');

    if ~isempty(thisScriptPath)
        scriptFolder = fileparts(thisScriptPath);
        addpath(scriptFolder);
    end
end

if exist('hc31_batch11O_extract_beta2_context','file') ~= 2 || ...
        exist('hc31_batch11O_bh_fdr','file') ~= 2
    error(['Keep the Batch 11O helper files beside ', ...
        'the Stage B script.']);
end

if exist(defaultRoot,'dir') == 7
    rootDir = defaultRoot;
else
    rootDir = uigetdir(pwd,'Select HC-31 root folder');

    if isequal(rootDir,0)
        error('No root folder selected.');
    end
end

if exist(fullfile(rootDir,'neuralynximport'),'dir') == 7
    addpath(genpath(fullfile(rootDir,'neuralynximport')));
end

if exist(fullfile(rootDir, ...
        'neuralynximport','nlximport'),'dir') == 7
    addpath(genpath(fullfile(rootDir, ...
        'neuralynximport','nlximport')));
end

if exist('Nlx2MatCSC','file') ~= 2 && ...
        exist('Nlx2MatCSC','file') ~= 3
    error('MATLAB cannot find Nlx2MatCSC.');
end

resSavePath = fullfile(rootDir,'resSave.mat');

if exist(resSavePath,'file') ~= 2
    [f,p] = uigetfile('*.mat','Select resSave.mat');

    if isequal(f,0)
        error('No resSave.mat selected.');
    end

    resSavePath = fullfile(p,f);
end

defaultMasterPath = fullfile( ...
    rootDir, ...
    'hc31_batch11Nplus_final_master_event_set', ...
    'hc31_batch11Nplus_manual_review_override_corrected', ...
    'hc31_batch11Nplus_MASTER_EVENT_TABLE_MANUAL_OVERRIDE_CORRECTED.csv');

masterPath = defaultMasterPath;

if exist(masterPath,'file') ~= 2
    [f,p] = uigetfile('*.csv', ...
        ['Select corrected Batch 11N+ ', ...
        'MASTER_EVENT_TABLE CSV']);

    if isequal(f,0)
        error('No corrected master table selected.');
    end

    masterPath = fullfile(p,f);
end

Loaded = load(resSavePath);
resSave = Loaded.resSave;

Master = readtable( ...
    masterPath, ...
    'TextType','string', ...
    'VariableNamingRule','preserve');

Master.animal = strtrim(string(Master.animal));
Master.epoch = upper(strtrim(string(Master.epoch)));
Master.masterTier = string(Master.masterTier);

isTierA = startsWith(Master.masterTier,"Tier A:");
isTierB = startsWith(Master.masterTier,"Tier B:");
isTierC = startsWith(Master.masterTier,"Tier C:");

awakeAnalysisMask = ...
    Master.epoch == "RUN1AWAKE" & ...
    (isTierA | isTierB | isTierC);

AwakeEvents = Master(awakeAnalysisMask,:);

AwakeEvents.isTierA = isTierA(awakeAnalysisMask);
AwakeEvents.isTierB = isTierB(awakeAnalysisMask);
AwakeEvents.isTierC = isTierC(awakeAnalysisMask);
AwakeEvents.inSetTierA = AwakeEvents.isTierA;
AwakeEvents.inSetTierAB = ...
    AwakeEvents.isTierA | AwakeEvents.isTierB;
AwakeEvents.inSetTierAC = ...
    AwakeEvents.isTierA | AwakeEvents.isTierC;
AwakeEvents.inSetTierABC = true(height(AwakeEvents),1);

AwakeEvents = sortrows( ...
    AwakeEvents, ...
    {'animal','peakUs'});

fprintf('Run1-awake Tier A/B/C events: %d\n', ...
    height(AwakeEvents));

%% Output and run mode

outputFolder = fullfile(rootDir, ...
    'hc31_batch11O_validated_biological_results', ...
    'stageB_awake_beta2_speed_matched');

figureFolder = fullfile(outputFolder,'figures');

if ~exist(outputFolder,'dir')
    mkdir(outputFolder);
end

if ~exist(figureFolder,'dir')
    mkdir(figureFolder);
end

checkpointPath = fullfile(outputFolder, ...
    'hc31_batch11O_awake_beta2_checkpoint.mat');

runMode = menu( ...
    'Batch 11O Stage B run mode', ...
    'Smoke test / resume: process 20 pending pairs', ...
    'Full / resume: process all pending pairs', ...
    'Finalise only from completed checkpoint');

if runMode == 0
    error('No run mode selected.');
end

if runMode == 1
    maximumPairsThisInvocation = ...
        maximumPairsThisInvocationSmoke;
elseif runMode == 2
    maximumPairsThisInvocation = Inf;
else
    maximumPairsThisInvocation = 0;
end

%% Build movement traces and matched controls

nEvents = height(AwakeEvents);
nBins = numel(settings.beta2PethCenters);

eventSpeedAtPeak = nan(nEvents,1);
eventAccelerationAtPeak = nan(nEvents,1);
eventPreSpeed = nan(nEvents,1);
eventPostSpeed = nan(nEvents,1);
eventSpeedChange = nan(nEvents,1);
eventMaxSpeedTwoSec = nan(nEvents,1);
eventSustainedImmobility = false(nEvents,1);
eventMovementIncrease = false(nEvents,1);

controlUs = nan(nEvents,1);
controlSpeedAtPeak = nan(nEvents,1);
controlAccelerationAtPeak = nan(nEvents,1);
controlSpeedChange = nan(nEvents,1);
controlSustainedImmobility = false(nEvents,1);
controlMatchDistance = nan(nEvents,1);

allAwakePeaksByAnimal = struct();

for animalIndex = 1:numel(fallbackAnimalIDs)
    animalID = string(fallbackAnimalIDs{animalIndex});

    allAwakePeaksByAnimal.( ...
        matlab.lang.makeValidName(char(animalID))) = ...
        double(Master.peakUs( ...
        Master.animal == animalID & ...
        Master.epoch == "RUN1AWAKE"));
end

for animalPosition = 1:numel(animalIndices)
    resSaveIndex = animalIndices(animalPosition);

    if resSaveIndex > numel(resSave)
        continue
    end

    R = resSave(resSaveIndex);
    animalID = string(fallbackAnimalIDs{animalPosition});

    try
        if isfield(R,'spAll') && ...
                ~isempty(R.spAll) && ...
                isfield(R.spAll,'animal')
            animalID = strtrim(string(R.spAll(1).animal));
        elseif isfield(R,'name')
            animalID = strtrim(string(R.name));
        elseif isfield(R,'animal')
            animalID = strtrim(string(R.animal));
        end
    catch
    end

    animalRows = find( ...
        AwakeEvents.animal == animalID);

    if isempty(animalRows)
        continue
    end

    try
        posUnit = R.posMazeLin(1);
        posData = double(posUnit.data);
    catch
        warning('%s has no usable posMazeLin(1).',animalID);
        continue
    end

    if size(posData,2) < 4
        warning('%s position table lacks speed column 4.', ...
            animalID);
        continue
    end

    positionTimeUs = posData(:,1);

    if max(abs(positionTimeUs),[],'omitnan') < 1e6
        positionTimeUs = positionTimeUs*1e6;
    end

    speedCmS = abs(posData(:,4));

    if isfield(posUnit,'unitsPerCm') && ...
            isfield(posUnit,'unitsPerSecond')
        speedCmS = speedCmS .* ...
            (1/posUnit.unitsPerCm) .* ...
            posUnit.unitsPerSecond;
    end

    validPosition = ...
        isfinite(positionTimeUs) & ...
        isfinite(speedCmS);

    positionTimeUs = positionTimeUs(validPosition);
    speedCmS = speedCmS(validPosition);

    [positionTimeUs,uniqueIndex] = ...
        unique(positionTimeUs,'stable');

    speedCmS = speedCmS(uniqueIndex);

    positionTimeSec = positionTimeUs/1e6;
    dtSec = median(diff(positionTimeSec),'omitnan');

    if ~isfinite(dtSec) || dtSec <= 0
        continue
    end

    smoothSamples = max( ...
        1,round(0.25/dtSec));

    speedSmooth = movmean( ...
        speedCmS,smoothSamples,'omitnan');

    acceleration = gradient(speedSmooth) ./ ...
        max(gradient(positionTimeSec),eps);

    acceleration = movmean( ...
        acceleration,smoothSamples,'omitnan');

    halfWindowSamples = max( ...
        1,round(1.0/dtSec));

    maxSpeedTwoSec = movmax( ...
        speedSmooth, ...
        [halfWindowSamples halfWindowSamples]);

    preSampleSpeed = interp1( ...
        positionTimeSec, ...
        speedSmooth, ...
        positionTimeSec-0.6, ...
        'linear',NaN);

    postSampleSpeed = interp1( ...
        positionTimeSec, ...
        speedSmooth, ...
        positionTimeSec+0.6, ...
        'linear',NaN);

    speedChangeTrace = ...
        postSampleSpeed-preSampleSpeed;

    sustainedTrace = ...
        maxSpeedTwoSec <= lowSpeedThresholdCmS & ...
        abs(speedChangeTrace) <= ...
            stableSpeedChangeThresholdCmS & ...
        abs(acceleration) <= ...
            stableAccelerationThresholdCmS2;

    firstAllowedSec = ...
        min(positionTimeSec)+controlMinimumEdgeSec;

    lastAllowedSec = ...
        max(positionTimeSec)-controlMinimumEdgeSec;

    controlGridSec = ...
        (ceil(firstAllowedSec/controlGridStepSec)* ...
        controlGridStepSec): ...
        controlGridStepSec: ...
        lastAllowedSec;

    controlGridUs = controlGridSec(:)*1e6;

    controlGridSpeed = interp1( ...
        positionTimeUs, ...
        speedSmooth, ...
        controlGridUs, ...
        'linear',NaN);

    controlGridAcceleration = interp1( ...
        positionTimeUs, ...
        acceleration, ...
        controlGridUs, ...
        'linear',NaN);

    controlGridSpeedChange = interp1( ...
        positionTimeUs, ...
        speedChangeTrace, ...
        controlGridUs, ...
        'linear',NaN);

    controlGridSustained = interp1( ...
        positionTimeUs, ...
        double(sustainedTrace), ...
        controlGridUs, ...
        'nearest',0) > 0.5;

    allAwakePeaks = ...
        allAwakePeaksByAnimal.( ...
        matlab.lang.makeValidName(char(animalID)));

    controlAllowed = ...
        isfinite(controlGridSpeed) & ...
        isfinite(controlGridAcceleration) & ...
        isfinite(controlGridSpeedChange);

    for controlIndex = 1:numel(controlGridUs)
        if any(abs(allAwakePeaks- ...
                controlGridUs(controlIndex)) <= ...
                controlEventExclusionSec*1e6)
            controlAllowed(controlIndex) = false;
        end
    end

    controlGridUs = controlGridUs(controlAllowed);
    controlGridSpeed = controlGridSpeed(controlAllowed);
    controlGridAcceleration = ...
        controlGridAcceleration(controlAllowed);
    controlGridSpeedChange = ...
        controlGridSpeedChange(controlAllowed);
    controlGridSustained = ...
        controlGridSustained(controlAllowed);

    controlUsed = false(size(controlGridUs));

    for localIndex = 1:numel(animalRows)
        rowIndex = animalRows(localIndex);
        eventUs = double(AwakeEvents.peakUs(rowIndex));

        eventSpeedAtPeak(rowIndex) = interp1( ...
            positionTimeUs,speedSmooth,eventUs, ...
            'linear',NaN);

        eventAccelerationAtPeak(rowIndex) = interp1( ...
            positionTimeUs,acceleration,eventUs, ...
            'linear',NaN);

        eventPreSpeed(rowIndex) = interp1( ...
            positionTimeUs,speedSmooth, ...
            eventUs-0.6e6,'linear',NaN);

        eventPostSpeed(rowIndex) = interp1( ...
            positionTimeUs,speedSmooth, ...
            eventUs+0.6e6,'linear',NaN);

        eventSpeedChange(rowIndex) = ...
            eventPostSpeed(rowIndex)- ...
            eventPreSpeed(rowIndex);

        eventMaxSpeedTwoSec(rowIndex) = interp1( ...
            positionTimeUs,maxSpeedTwoSec,eventUs, ...
            'linear',NaN);

        eventSustainedImmobility(rowIndex) = ...
            eventMaxSpeedTwoSec(rowIndex) <= ...
                lowSpeedThresholdCmS & ...
            abs(eventSpeedChange(rowIndex)) <= ...
                stableSpeedChangeThresholdCmS & ...
            abs(eventAccelerationAtPeak(rowIndex)) <= ...
                stableAccelerationThresholdCmS2;

        eventMovementIncrease(rowIndex) = ...
            eventSpeedChange(rowIndex) > ...
                stableSpeedChangeThresholdCmS | ...
            eventAccelerationAtPeak(rowIndex) > ...
                stableAccelerationThresholdCmS2;

        if isempty(controlGridUs)
            continue
        end

        sameSustained = ...
            controlGridSustained == ...
            eventSustainedImmobility(rowIndex);

        withinTolerance = ...
            abs(controlGridSpeed- ...
                eventSpeedAtPeak(rowIndex)) <= ...
                speedMatchToleranceCmS & ...
            abs(controlGridAcceleration- ...
                eventAccelerationAtPeak(rowIndex)) <= ...
                accelerationMatchToleranceCmS2 & ...
            abs(controlGridSpeedChange- ...
                eventSpeedChange(rowIndex)) <= ...
                speedChangeMatchToleranceCmS & ...
            sameSustained;

        preferred = find(withinTolerance & ~controlUsed);

        if isempty(preferred)
            preferred = find(withinTolerance);
        end

        standardDistance = ...
            ((controlGridSpeed- ...
            eventSpeedAtPeak(rowIndex)) / ...
            max(speedMatchToleranceCmS,eps)).^2 + ...
            ((controlGridAcceleration- ...
            eventAccelerationAtPeak(rowIndex)) / ...
            max(accelerationMatchToleranceCmS2,eps)).^2 + ...
            ((controlGridSpeedChange- ...
            eventSpeedChange(rowIndex)) / ...
            max(speedChangeMatchToleranceCmS,eps)).^2 + ...
            4*double(~sameSustained);

        if isempty(preferred)
            [minimumDistance,selectedControl] = ...
                min(standardDistance);
        else
            [minimumDistance,relativeControl] = ...
                min(standardDistance(preferred));

            selectedControl = ...
                preferred(relativeControl);
        end

        controlUs(rowIndex) = ...
            controlGridUs(selectedControl);

        controlSpeedAtPeak(rowIndex) = ...
            controlGridSpeed(selectedControl);

        controlAccelerationAtPeak(rowIndex) = ...
            controlGridAcceleration(selectedControl);

        controlSpeedChange(rowIndex) = ...
            controlGridSpeedChange(selectedControl);

        controlSustainedImmobility(rowIndex) = ...
            controlGridSustained(selectedControl);

        controlMatchDistance(rowIndex) = ...
            minimumDistance;

        controlUsed(selectedControl) = true;
    end
end

AwakeEvents.eventSpeedAtPeakCmS = ...
    eventSpeedAtPeak;
AwakeEvents.eventAccelerationAtPeakCmS2 = ...
    eventAccelerationAtPeak;
AwakeEvents.eventPreSpeedCmS = ...
    eventPreSpeed;
AwakeEvents.eventPostSpeedCmS = ...
    eventPostSpeed;
AwakeEvents.eventSpeedChangeCmS = ...
    eventSpeedChange;
AwakeEvents.eventMaxSpeedMinus1ToPlus1CmS = ...
    eventMaxSpeedTwoSec;
AwakeEvents.sustainedImmobility = ...
    eventSustainedImmobility;
AwakeEvents.movementIncrease = ...
    eventMovementIncrease;

AwakeEvents.controlUs = controlUs;
AwakeEvents.controlSpeedAtPeakCmS = ...
    controlSpeedAtPeak;
AwakeEvents.controlAccelerationAtPeakCmS2 = ...
    controlAccelerationAtPeak;
AwakeEvents.controlSpeedChangeCmS = ...
    controlSpeedChange;
AwakeEvents.controlSustainedImmobility = ...
    controlSustainedImmobility;
AwakeEvents.controlMatchDistance = ...
    controlMatchDistance;

%% Initialise or resume beta2 checkpoint

if exist(checkpointPath,'file') == 2
    LoadedCheckpoint = load(checkpointPath);

    PairTable = LoadedCheckpoint.PairTable;
    eventPethZ = LoadedCheckpoint.eventPethZ;
    controlPethZ = LoadedCheckpoint.controlPethZ;

    if height(PairTable) ~= height(AwakeEvents) || ...
            any(PairTable.eventID ~= AwakeEvents.eventID)
        error(['The checkpoint event list does not match ', ...
            'the current corrected master table.']);
    end
else
    PairTable = AwakeEvents;

    PairTable.pairComplete = ...
        false(height(PairTable),1);

    PairTable.eventBeta2FailureReason = ...
        repmat("",height(PairTable),1);

    PairTable.controlBeta2FailureReason = ...
        repmat("",height(PairTable),1);

    metricNames = { ...
        'eventBeta2EffectiveFs', ...
        'eventPreMeanZ', ...
        'eventCentralMeanZ', ...
        'eventEarlyPostMeanZ', ...
        'eventLatePostMeanZ', ...
        'eventPostMinusPreZ', ...
        'eventCentralMinusPreZ', ...
        'eventPreBurstCount', ...
        'eventPostBurstCount', ...
        'eventPreBurstFraction', ...
        'eventPostBurstFraction', ...
        'eventPeakEnvelopeZ', ...
        'controlBeta2EffectiveFs', ...
        'controlPreMeanZ', ...
        'controlCentralMeanZ', ...
        'controlEarlyPostMeanZ', ...
        'controlLatePostMeanZ', ...
        'controlPostMinusPreZ', ...
        'controlCentralMinusPreZ', ...
        'controlPreBurstCount', ...
        'controlPostBurstCount', ...
        'controlPreBurstFraction', ...
        'controlPostBurstFraction', ...
        'controlPeakEnvelopeZ'};

    for metricIndex = 1:numel(metricNames)
        PairTable.(metricNames{metricIndex}) = ...
            nan(height(PairTable),1);
    end

    eventPethZ = nan(height(PairTable),nBins);
    controlPethZ = nan(height(PairTable),nBins);
end

pendingRows = find(~PairTable.pairComplete);

if maximumPairsThisInvocation > 0 && ...
        ~isempty(pendingRows)

    nToProcess = min( ...
        numel(pendingRows), ...
        maximumPairsThisInvocation);

    processingRows = ...
        pendingRows(1:nToProcess);

    fprintf('Processing %d pending event-control pairs.\n', ...
        numel(processingRows));

    for progressIndex = 1:numel(processingRows)
        rowIndex = processingRows(progressIndex);

        EventBeta = ...
            hc31_batch11O_extract_beta2_context( ...
            char(PairTable.cscFile(rowIndex)), ...
            double(PairTable.peakUs(rowIndex)), ...
            settings);

        ControlBeta = ...
            hc31_batch11O_extract_beta2_context( ...
            char(PairTable.cscFile(rowIndex)), ...
            double(PairTable.controlUs(rowIndex)), ...
            settings);

        PairTable.eventBeta2FailureReason(rowIndex) = ...
            EventBeta.failureReason;
        PairTable.controlBeta2FailureReason(rowIndex) = ...
            ControlBeta.failureReason;

        PairTable.eventBeta2EffectiveFs(rowIndex) = ...
            EventBeta.effectiveSamplingRateHz;
        PairTable.eventPreMeanZ(rowIndex) = ...
            EventBeta.preMeanZ;
        PairTable.eventCentralMeanZ(rowIndex) = ...
            EventBeta.centralMeanZ;
        PairTable.eventEarlyPostMeanZ(rowIndex) = ...
            EventBeta.earlyPostMeanZ;
        PairTable.eventLatePostMeanZ(rowIndex) = ...
            EventBeta.latePostMeanZ;
        PairTable.eventPostMinusPreZ(rowIndex) = ...
            EventBeta.postMinusPreZ;
        PairTable.eventCentralMinusPreZ(rowIndex) = ...
            EventBeta.centralMinusPreZ;
        PairTable.eventPreBurstCount(rowIndex) = ...
            EventBeta.preBurstCount;
        PairTable.eventPostBurstCount(rowIndex) = ...
            EventBeta.postBurstCount;
        PairTable.eventPreBurstFraction(rowIndex) = ...
            EventBeta.preBurstFraction;
        PairTable.eventPostBurstFraction(rowIndex) = ...
            EventBeta.postBurstFraction;
        PairTable.eventPeakEnvelopeZ(rowIndex) = ...
            EventBeta.peakEnvelopeZ;

        PairTable.controlBeta2EffectiveFs(rowIndex) = ...
            ControlBeta.effectiveSamplingRateHz;
        PairTable.controlPreMeanZ(rowIndex) = ...
            ControlBeta.preMeanZ;
        PairTable.controlCentralMeanZ(rowIndex) = ...
            ControlBeta.centralMeanZ;
        PairTable.controlEarlyPostMeanZ(rowIndex) = ...
            ControlBeta.earlyPostMeanZ;
        PairTable.controlLatePostMeanZ(rowIndex) = ...
            ControlBeta.latePostMeanZ;
        PairTable.controlPostMinusPreZ(rowIndex) = ...
            ControlBeta.postMinusPreZ;
        PairTable.controlCentralMinusPreZ(rowIndex) = ...
            ControlBeta.centralMinusPreZ;
        PairTable.controlPreBurstCount(rowIndex) = ...
            ControlBeta.preBurstCount;
        PairTable.controlPostBurstCount(rowIndex) = ...
            ControlBeta.postBurstCount;
        PairTable.controlPreBurstFraction(rowIndex) = ...
            ControlBeta.preBurstFraction;
        PairTable.controlPostBurstFraction(rowIndex) = ...
            ControlBeta.postBurstFraction;
        PairTable.controlPeakEnvelopeZ(rowIndex) = ...
            ControlBeta.peakEnvelopeZ;

        eventPethZ(rowIndex,:) = ...
            EventBeta.pethEnvelopeZ;

        controlPethZ(rowIndex,:) = ...
            ControlBeta.pethEnvelopeZ;

        PairTable.pairComplete(rowIndex) = true;

        if mod(progressIndex,10) == 0 || ...
                progressIndex == numel(processingRows)
            fprintf('  %d/%d this invocation; total %d/%d complete\n', ...
                progressIndex, ...
                numel(processingRows), ...
                sum(PairTable.pairComplete), ...
                height(PairTable));
        end

        if mod(progressIndex, ...
                checkpointEveryNPairs) == 0 || ...
                progressIndex == numel(processingRows)

            save(checkpointPath, ...
                'PairTable', ...
                'eventPethZ', ...
                'controlPethZ', ...
                '-v7.3');
        end
    end
end

Progress = table( ...
    height(PairTable), ...
    sum(PairTable.pairComplete), ...
    sum(~PairTable.pairComplete), ...
    100*sum(PairTable.pairComplete)/ ...
        max(height(PairTable),1), ...
    'VariableNames', { ...
    'nPairs', ...
    'nComplete', ...
    'nPending', ...
    'percentComplete'});

writetable(Progress,fullfile(outputFolder, ...
    'hc31_batch11O_awake_beta2_PROGRESS.csv'));

if any(~PairTable.pairComplete)
    fprintf('\nStage B checkpoint saved. Rerun and choose Full/resume.\n');
else
    PairTable.eventMinusControlPostMinusPreZ = ...
        PairTable.eventPostMinusPreZ- ...
        PairTable.controlPostMinusPreZ;

    PairTable.eventMinusControlCentralMinusPreZ = ...
        PairTable.eventCentralMinusPreZ- ...
        PairTable.controlCentralMinusPreZ;

    PairTable.eventMinusControlPostBurstCountChange = ...
        (PairTable.eventPostBurstCount- ...
        PairTable.eventPreBurstCount) - ...
        (PairTable.controlPostBurstCount- ...
        PairTable.controlPreBurstCount);

    PairTable.eventMinusControlPostBurstFractionChange = ...
        (PairTable.eventPostBurstFraction- ...
        PairTable.eventPreBurstFraction) - ...
        (PairTable.controlPostBurstFraction- ...
        PairTable.controlPreBurstFraction);

    writetable(PairTable,fullfile(outputFolder, ...
        'hc31_batch11O_awake_beta2_event_control_pairs.csv'));

    %% Animal summaries

    setNames = ["TierA","TierAB","TierAC","TierABC"];
    movementGroups = [ ...
        "AllMatched", ...
        "SustainedImmobility", ...
        "StableLowSpeed", ...
        "MovementIncrease"];

    animals = unique(PairTable.animal,'stable');
    summaryRows = {};

    for setIndex = 1:numel(setNames)
        setName = setNames(setIndex);

        if setName == "TierA"
            setMask = PairTable.inSetTierA;
        elseif setName == "TierAB"
            setMask = PairTable.inSetTierAB;
        elseif setName == "TierAC"
            setMask = PairTable.inSetTierAC;
        else
            setMask = PairTable.inSetTierABC;
        end

        for movementIndex = 1:numel(movementGroups)
            movementName = ...
                movementGroups(movementIndex);

            if movementName == "AllMatched"
                movementMask = ...
                    isfinite(PairTable.controlUs);
            elseif movementName == "SustainedImmobility"
                movementMask = ...
                    PairTable.sustainedImmobility & ...
                    PairTable.controlSustainedImmobility;
            elseif movementName == "StableLowSpeed"
                movementMask = ...
                    PairTable.eventSpeedAtPeakCmS <= ...
                        lowSpeedThresholdCmS & ...
                    abs(PairTable.eventSpeedChangeCmS) <= ...
                        stableSpeedChangeThresholdCmS & ...
                    abs(PairTable.controlSpeedChangeCmS) <= ...
                        stableSpeedChangeThresholdCmS;
            else
                movementMask = ...
                    PairTable.movementIncrease;
            end

            for animalIndex = 1:numel(animals)
                animalID = animals(animalIndex);

                mask = ...
                    setMask & ...
                    movementMask & ...
                    PairTable.animal == animalID & ...
                    PairTable.pairComplete & ...
                    strlength( ...
                    PairTable.eventBeta2FailureReason) == 0 & ...
                    strlength( ...
                    PairTable.controlBeta2FailureReason) == 0;

                nPairs = sum(mask);

                if nPairs == 0
                    continue
                end

                summaryRows(end+1,:) = { ...
                    char(setName), ...
                    char(movementName), ...
                    char(animalID), ...
                    nPairs, ...
                    mean(PairTable.eventPreMeanZ(mask), ...
                        'omitnan'), ...
                    mean(PairTable.eventEarlyPostMeanZ(mask), ...
                        'omitnan'), ...
                    mean(PairTable.eventPostMinusPreZ(mask), ...
                        'omitnan'), ...
                    mean(PairTable.controlPostMinusPreZ(mask), ...
                        'omitnan'), ...
                    mean(PairTable. ...
                        eventMinusControlPostMinusPreZ(mask), ...
                        'omitnan'), ...
                    mean(PairTable. ...
                        eventMinusControlCentralMinusPreZ(mask), ...
                        'omitnan'), ...
                    mean(PairTable. ...
                        eventMinusControlPostBurstCountChange(mask), ...
                        'omitnan'), ...
                    mean(PairTable. ...
                        eventMinusControlPostBurstFractionChange(mask), ...
                        'omitnan'), ...
                    mean(PairTable.eventSpeedAtPeakCmS(mask), ...
                        'omitnan'), ...
                    mean(PairTable.eventAccelerationAtPeakCmS2(mask), ...
                        'omitnan'), ...
                    mean(PairTable.eventSpeedChangeCmS(mask), ...
                        'omitnan'), ...
                    mean(PairTable.controlMatchDistance(mask), ...
                        'omitnan')}; %#ok<SAGROW>
            end
        end
    end

    AnimalSummary = cell2table(summaryRows, ...
        'VariableNames', { ...
        'eventSet', ...
        'movementGroup', ...
        'animal', ...
        'nPairs', ...
        'eventPreMeanZ', ...
        'eventEarlyPostMeanZ', ...
        'eventPostMinusPreZ', ...
        'controlPostMinusPreZ', ...
        'eventMinusControlPostMinusPreZ', ...
        'eventMinusControlCentralMinusPreZ', ...
        'eventMinusControlPostBurstCountChange', ...
        'eventMinusControlPostBurstFractionChange', ...
        'meanEventSpeedCmS', ...
        'meanEventAccelerationCmS2', ...
        'meanEventSpeedChangeCmS', ...
        'meanControlMatchDistance'});

    writetable(AnimalSummary,fullfile(outputFolder, ...
        'hc31_batch11O_awake_beta2_animal_summary.csv'));

    %% PETH summary

    pethRows = {};

    for setIndex = 1:numel(setNames)
        setName = setNames(setIndex);

        if setName == "TierA"
            setMask = PairTable.inSetTierA;
        elseif setName == "TierAB"
            setMask = PairTable.inSetTierAB;
        elseif setName == "TierAC"
            setMask = PairTable.inSetTierAC;
        else
            setMask = PairTable.inSetTierABC;
        end

        for movementIndex = 1:numel(movementGroups)
            movementName = ...
                movementGroups(movementIndex);

            if movementName == "AllMatched"
                movementMask = ...
                    isfinite(PairTable.controlUs);
            elseif movementName == "SustainedImmobility"
                movementMask = ...
                    PairTable.sustainedImmobility & ...
                    PairTable.controlSustainedImmobility;
            elseif movementName == "StableLowSpeed"
                movementMask = ...
                    PairTable.eventSpeedAtPeakCmS <= ...
                        lowSpeedThresholdCmS & ...
                    abs(PairTable.eventSpeedChangeCmS) <= ...
                        stableSpeedChangeThresholdCmS & ...
                    abs(PairTable.controlSpeedChangeCmS) <= ...
                        stableSpeedChangeThresholdCmS;
            else
                movementMask = ...
                    PairTable.movementIncrease;
            end

            animalEventPeth = [];
            animalControlPeth = [];
            nPairsByAnimal = [];

            for animalIndex = 1:numel(animals)
                animalID = animals(animalIndex);

                mask = ...
                    setMask & movementMask & ...
                    PairTable.animal == animalID & ...
                    PairTable.pairComplete & ...
                    strlength( ...
                    PairTable.eventBeta2FailureReason) == 0 & ...
                    strlength( ...
                    PairTable.controlBeta2FailureReason) == 0;

                rows = find(mask);

                if isempty(rows)
                    continue
                end

                animalEventPeth(end+1,:) = ...
                    mean(eventPethZ(rows,:),1,'omitnan'); %#ok<SAGROW>

                animalControlPeth(end+1,:) = ...
                    mean(controlPethZ(rows,:),1,'omitnan'); %#ok<SAGROW>

                nPairsByAnimal(end+1,1) = ...
                    numel(rows); %#ok<SAGROW>
            end

            if isempty(animalEventPeth)
                continue
            end

            eventMean = mean( ...
                animalEventPeth,1,'omitnan');

            eventSem = std( ...
                animalEventPeth,0,1,'omitnan') / ...
                sqrt(size(animalEventPeth,1));

            controlMean = mean( ...
                animalControlPeth,1,'omitnan');

            controlSem = std( ...
                animalControlPeth,0,1,'omitnan') / ...
                sqrt(size(animalControlPeth,1));

            for binIndex = 1:nBins
                pethRows(end+1,:) = { ...
                    char(setName), ...
                    char(movementName), ...
                    settings.beta2PethCenters(binIndex), ...
                    eventMean(binIndex), ...
                    eventSem(binIndex), ...
                    controlMean(binIndex), ...
                    controlSem(binIndex), ...
                    size(animalEventPeth,1), ...
                    sum(nPairsByAnimal)}; %#ok<SAGROW>
            end
        end
    end

    PethSummary = cell2table(pethRows, ...
        'VariableNames', { ...
        'eventSet', ...
        'movementGroup', ...
        'timeFromEventSec', ...
        'meanEventBeta2EnvelopeZ', ...
        'semEventBeta2EnvelopeZ', ...
        'meanControlBeta2EnvelopeZ', ...
        'semControlBeta2EnvelopeZ', ...
        'nAnimals', ...
        'nPairs'});

    writetable(PethSummary,fullfile(outputFolder, ...
        'hc31_batch11O_awake_beta2_animal_weighted_PETH.csv'));

    %% Statistics

    statRows = {};
    metricNames = { ...
        'eventPostMinusPreZ', ...
        'eventMinusControlPostMinusPreZ', ...
        'eventMinusControlCentralMinusPreZ', ...
        'eventMinusControlPostBurstCountChange', ...
        'eventMinusControlPostBurstFractionChange'};

    for setIndex = 1:numel(setNames)
        setName = setNames(setIndex);

        for movementIndex = 1:numel(movementGroups)
            movementName = ...
                movementGroups(movementIndex);

            mask = ...
                string(AnimalSummary.eventSet) == setName & ...
                string(AnimalSummary.movementGroup) == ...
                    movementName;

            for metricIndex = 1:numel(metricNames)
                metricName = metricNames{metricIndex};
                values = double( ...
                    AnimalSummary.(metricName)(mask));

                values = values(isfinite(values));
                pValue = NaN;
                signedRank = NaN;

                if numel(values) >= 3
                    try
                        [pValue,~,stats] = ...
                            signrank(values,0);

                        signedRank = stats.signedrank;
                    catch
                    end
                end

                statRows(end+1,:) = { ...
                    char(setName), ...
                    char(movementName), ...
                    metricName, ...
                    numel(values), ...
                    mean(values,'omitnan'), ...
                    median(values,'omitnan'), ...
                    pValue, ...
                    signedRank}; %#ok<SAGROW>
            end
        end
    end

    Beta2Stats = cell2table(statRows, ...
        'VariableNames', { ...
        'eventSet', ...
        'movementGroup', ...
        'metric', ...
        'nAnimals', ...
        'meanEffect', ...
        'medianEffect', ...
        'pValue', ...
        'signedRank'});

    Beta2Stats.qValueBH = ...
        hc31_batch11O_bh_fdr(Beta2Stats.pValue);

    writetable(Beta2Stats,fullfile(outputFolder, ...
        'hc31_batch11O_awake_beta2_statistics.csv'));

    %% Figures

    plotMask = ...
        string(PethSummary.eventSet) == "TierAC" & ...
        string(PethSummary.movementGroup) == ...
            "SustainedImmobility";

    fig = figure( ...
        'Visible','off', ...
        'Color','w', ...
        'Position',[80 80 1200 720]);

    hold on

    plot( ...
        PethSummary.timeFromEventSec(plotMask), ...
        PethSummary.meanEventBeta2EnvelopeZ(plotMask), ...
        'LineWidth',1.8);

    plot( ...
        PethSummary.timeFromEventSec(plotMask), ...
        PethSummary.meanControlBeta2EnvelopeZ(plotMask), ...
        'LineWidth',1.8);

    xline(0,'k--');
    yline(0,':');
    xlabel('Time from event or matched pseudo-time (s)');
    ylabel('Local beta2 envelope robust z');
    title('Tier A+C sustained immobility: event vs movement-matched control');
    legend({'Event','Matched control'},'Location','best');
    grid on
    box off

    exportgraphics(fig,fullfile(figureFolder, ...
        'batch11O_TierAC_sustained_immobility_beta2_PETH.png'), ...
        'Resolution',200);

    close(fig);

    fig = figure( ...
        'Visible','off', ...
        'Color','w', ...
        'Position',[80 80 1100 700]);

    summaryMask = ...
        string(AnimalSummary.eventSet) == "TierAC" & ...
        ismember( ...
        string(AnimalSummary.movementGroup), ...
        ["SustainedImmobility","MovementIncrease"]);

    categories = categorical( ...
        string(AnimalSummary.movementGroup(summaryMask)));

    scatter(categories, ...
        AnimalSummary. ...
        eventMinusControlPostMinusPreZ(summaryMask), ...
        55,'filled');

    yline(0,'k--');
    ylabel('Event-control beta2 post-minus-pre z');
    title('Movement-stratified beta2 coupling by animal');
    grid on
    box off

    exportgraphics(fig,fullfile(figureFolder, ...
        'batch11O_movement_stratified_beta2_effect.png'), ...
        'Resolution',200);

    close(fig);

    %% Text summary

    fid = fopen(fullfile(outputFolder, ...
        'hc31_batch11O_STAGE_B_SUMMARY.txt'),'w');

    if fid >= 0
        fprintf(fid, ...
            'HC-31 Batch 11O Stage B\n');
        fprintf(fid, ...
            'Run1-awake beta2 coupling with matched controls\n');
        fprintf(fid, ...
            '================================================\n\n');

        fprintf(fid,'Corrected master table:\n%s\n\n',masterPath);
        fprintf(fid,'Event-control pairs: %d\n',height(PairTable));
        fprintf(fid,'Beta2 band: 23-30 Hz\n');
        fprintf(fid,'Burst threshold: robust z >= %.1f\n', ...
            settings.beta2BurstThresholdZ);
        fprintf(fid,'Minimum burst duration: %.0f ms\n\n', ...
            settings.beta2BurstMinDurationSec*1000);

        fprintf(fid,'Primary analysis\n');
        fprintf(fid,'----------------\n');
        fprintf(fid,[ ...
            'Tier A+C events during sustained immobility, ', ...
            'compared with same-animal pseudo-times matched ', ...
            'on speed, acceleration and speed change.\n\n']);

        fprintf(fid,'Interpretation boundaries\n');
        fprintf(fid,'-------------------------\n');
        fprintf(fid,[ ...
            'Local beta2 z is normalised independently in each ', ...
            'event/control segment.\n']);
        fprintf(fid,[ ...
            'Matched controls reduce movement confounding but ', ...
            'do not establish causality.\n']);
        fprintf(fid,[ ...
            'Animal-level tests use at most five subjects and ', ...
            'should be reported with effect sizes and raw points.\n']);

        fclose(fid);
    end

    fprintf('\nBatch 11O Stage B complete.\n');
    fprintf('Output folder:\n  %s\n',outputFolder);
end
