% MATLAB_REQUIREMENTS
% HC31 repository environment and dependency check.
%
% This file documents the software requirements inferred from the retained
% MATLAB source included in the HC31 repository. It is not a record of the
% exact historical MATLAB release used for every stage of the project.
%
% Recommended MATLAB release
% --------------------------
% Use MATLAB R2020a or newer.
%
% This is a practical compatibility recommendation rather than a recovered
% historical version. The retained scripts use functions such as
% exportgraphics, tiledlayout, string, table, groupsummary, contains, and
% other modern MATLAB language features.
%
% Required MathWorks toolboxes
% ----------------------------
% 1. Signal Processing Toolbox
%    Retained scripts use functions including:
%       butter
%       filtfilt
%       hilbert
%       bandpass
%       decimate
%       spectrogram
%       pwelch
%       findpeaks
%
% 2. Statistics and Machine Learning Toolbox
%    Retained scripts use functions including:
%       signrank
%       linkage
%       corr
%       prctile
%       mad
%
% External dependencies
% ---------------------
% 1. Neuralynx MATLAB import utilities
%    Multiple retained scripts call Nlx2MatCSC to read Neuralynx .ncs files.
%    These utilities are not redistributed in this repository.
%
% 2. Chronux
%    Some retained spectral scripts call:
%       mtspectrumc
%       mtspecgramc
%    Chronux is not redistributed in this repository.
%
%    Important provenance note:
%    The manuscript states that the exact estimator used for some historical
%    saved spectra could not be recovered. Chronux therefore represents an
%    available retained implementation for relevant spectral branches, not a
%    claim that every archived spectrum was necessarily generated by Chronux.
%
% Not required by the curated retained code
% -----------------------------------------
% The curated scripts do not appear to require Parallel Computing Toolbox,
% Image Processing Toolbox, Optimization Toolbox, or Curve Fitting Toolbox
% as repository-wide dependencies.
%
% Platform notes
% --------------
% Many retained scripts were developed with Windows-style paths and local
% folder assumptions. Paths should be configured before execution on another
% machine or operating system.
%
% Neuralynx import utilities may include platform-specific binaries. Their
% compatibility should be checked separately for the user's MATLAB release
% and operating system.
%
% Reproducibility notes
% ---------------------
% The repository is not a single one-command pipeline. Consult:
%   docs/REPRODUCIBILITY.md
%   docs/FIGURE_SCRIPT_MAP.md
%   docs/MANIFEST.csv
%
% Raw hc-31 recordings are not included. Obtain them from CRCNS:
%   https://doi.org/10.6080/K0BV7DT2
%
% Running this script prints a lightweight local environment check.

fprintf('\nHC31 MATLAB environment check\n');
fprintf('=============================\n');
fprintf('MATLAB version: %s\n', version);
fprintf('Computer: %s\n', computer);

fprintf('\nMathWorks toolboxes\n');
fprintf('-------------------\n');

sig = ver('signal');
if isempty(sig)
    fprintf('[MISSING] Signal Processing Toolbox\n');
else
    fprintf('[FOUND]   Signal Processing Toolbox %s\n', sig.Version);
end

stats = ver('stats');
if isempty(stats)
    fprintf('[MISSING] Statistics and Machine Learning Toolbox\n');
else
    fprintf('[FOUND]   Statistics and Machine Learning Toolbox %s\n', stats.Version);
end

fprintf('\nKey MATLAB functions\n');
fprintf('--------------------\n');

requiredFunctions = { ...
    'butter', ...
    'filtfilt', ...
    'hilbert', ...
    'bandpass', ...
    'decimate', ...
    'spectrogram', ...
    'pwelch', ...
    'signrank', ...
    'linkage', ...
    'corr', ...
    'exportgraphics' ...
    };

for i = 1:numel(requiredFunctions)
    fn = requiredFunctions{i};
    if exist(fn, 'file') || exist(fn, 'builtin')
        fprintf('[FOUND]   %s\n', fn);
    else
        fprintf('[MISSING] %s\n', fn);
    end
end

fprintf('\nExternal dependencies\n');
fprintf('---------------------\n');

externalFunctions = { ...
    'Nlx2MatCSC', ...
    'mtspectrumc', ...
    'mtspecgramc' ...
    };

for i = 1:numel(externalFunctions)
    fn = externalFunctions{i};
    if exist(fn, 'file') || exist(fn, 'builtin')
        fprintf('[FOUND]   %s\n', fn);
    else
        fprintf('[NOT ON PATH] %s\n', fn);
    end
end

fprintf('\nNotes\n');
fprintf('-----\n');
fprintf('Nlx2MatCSC is required by raw Neuralynx-loading branches.\n');
fprintf('Chronux functions are required only by retained scripts that call them.\n');
fprintf('See docs/REPRODUCIBILITY.md before attempting a full rerun.\n\n');
