%% HC-31 Batch 11P
% FINAL ROBUSTNESS TABLES AND REPORT FIGURES FROM COMPLETED CSV OUTPUTS
%
% Plain script: no raw CSC or resSave processing.
%
% The finished Word report and CSV/PNG outputs are already supplied in the
% Batch 11P package. This script is provided only to regenerate the main
% summary tables and figures locally from canonical CSV files.

clear; clc; close all; rehash;

fprintf('\nHC-31 Batch 11P final synthesis\n');
fprintf('-------------------------------\n');

[masterFile,masterFolder] = uigetfile('*.csv', ...
    'Select hc31_batch11Nplus_MASTER_EVENT_TABLE_MANUAL_OVERRIDE_CORRECTED.csv');
if isequal(masterFile,0), error('No corrected master table selected.'); end

[tierFile,tierFolder] = uigetfile('*.csv', ...
    'Select hc31_batch11Nplus_tier_summary_MANUAL_OVERRIDE_CORRECTED.csv', ...
    masterFolder);
if isequal(tierFile,0), error('No tier summary selected.'); end

[epochFile,epochFolder] = uigetfile('*.csv', ...
    'Select hc31_batch11Nplus_animal_epoch_summary_MANUAL_OVERRIDE_CORRECTED.csv', ...
    masterFolder);
if isequal(epochFile,0), error('No animal/epoch summary selected.'); end

[detectorFile,detectorFolder] = uigetfile('*.csv', ...
    'Select hc31_batch11L2_BALANCED_RULE_POST_SECOND_REVIEW_PERFORMANCE.csv');
if isequal(detectorFile,0), error('No detector-performance table selected.'); end

[animalFile,stageAFolder] = uigetfile('*.csv', ...
    'Select hc31_batch11O_animal_level_population_recruitment.csv');
if isequal(animalFile,0), error('No Stage A animal summary selected.'); end

[pethFile,~] = uigetfile('*.csv', ...
    'Select hc31_batch11O_animal_weighted_population_PETH.csv', ...
    stageAFolder);
if isequal(pethFile,0), error('No Stage A PETH selected.'); end

[rateFile,~] = uigetfile('*.csv', ...
    'Select hc31_batch11O_state_matched_event_rates.csv', ...
    stageAFolder);
if isequal(rateFile,0), error('No Stage A rate table selected.'); end

[betaAnimalFile,stageBFolder] = uigetfile('*.csv', ...
    'Select hc31_batch11O_awake_beta2_animal_summary_QC_CORRECTED.csv');
if isequal(betaAnimalFile,0), error('No corrected Stage B animal summary selected.'); end

[betaPethFile,~] = uigetfile('*.csv', ...
    'Select hc31_batch11O_awake_beta2_animal_weighted_PETH_QC_CORRECTED.csv', ...
    stageBFolder);
if isequal(betaPethFile,0), error('No corrected Stage B PETH selected.'); end

Master = readtable(fullfile(masterFolder,masterFile), ...
    'TextType','string','VariableNamingRule','preserve');
Tier = readtable(fullfile(tierFolder,tierFile), ...
    'TextType','string','VariableNamingRule','preserve');
Epoch = readtable(fullfile(epochFolder,epochFile), ...
    'TextType','string','VariableNamingRule','preserve');
Detector = readtable(fullfile(detectorFolder,detectorFile), ...
    'TextType','string','VariableNamingRule','preserve');
Recruitment = readtable(fullfile(stageAFolder,animalFile), ...
    'TextType','string','VariableNamingRule','preserve');
Peth = readtable(fullfile(stageAFolder,pethFile), ...
    'TextType','string','VariableNamingRule','preserve');
Rates = readtable(fullfile(stageAFolder,rateFile), ...
    'TextType','string','VariableNamingRule','preserve');
BetaAnimal = readtable(fullfile(stageBFolder,betaAnimalFile), ...
    'TextType','string','VariableNamingRule','preserve');
BetaPeth = readtable(fullfile(stageBFolder,betaPethFile), ...
    'TextType','string','VariableNamingRule','preserve');

outputFolder = fullfile(masterFolder,'hc31_batch11P_final_synthesis');
if ~exist(outputFolder,'dir'), mkdir(outputFolder); end
figureFolder = fullfile(outputFolder,'figures');
if ~exist(figureFolder,'dir'), mkdir(figureFolder); end

% Epoch screening summary.
epochNames = ["PRE","REST","POST","RUN1AWAKE"];
summaryRows = {};
for epochIndex = 1:numel(epochNames)
    epochName = epochNames(epochIndex);
    mask = upper(string(Epoch.epoch)) == epochName;
    summaryRows(end+1,:) = { ...
        char(epochName), ...
        sum(Epoch.nCandidates(mask)), ...
        sum(Epoch.nBalancedL2(mask)), ...
        sum(Epoch.nStrictReviewed(mask)), ...
        sum(Epoch.nScreenedEligible(mask))}; %#ok<SAGROW>
end
EpochSummary = cell2table(summaryRows, ...
    'VariableNames', { ...
    'epoch','nCandidates','nBalancedL2', ...
    'nStrictReviewed','nScreenedEligible'});
EpochSummary.balancedRetentionFraction = ...
    EpochSummary.nBalancedL2 ./ EpochSummary.nCandidates;
EpochSummary.screenedEligibleFraction = ...
    EpochSummary.nScreenedEligible ./ EpochSummary.nCandidates;
writetable(EpochSummary,fullfile(outputFolder, ...
    'hc31_batch11P_epoch_screening_summary.csv'));

% Tier A+C NREM event rates.
rateMask = ...
    string(Rates.eventSet) == "TierAC" & ...
    string(Rates.stateGroup) == "NREM";
PrimaryRates = Rates(rateMask,:);
writetable(PrimaryRates,fullfile(outputFolder, ...
    'hc31_batch11P_TierAC_NREM_event_rates.csv'));

% Recruitment table.
recruitMask = ...
    string(Recruitment.eventSet) == "TierAC" & ...
    string(Recruitment.stateGroup) == "NREM" & ...
    ismember(string(Recruitment.epoch),["PRE","REST","POST"]);
PrimaryRecruitment = Recruitment(recruitMask,:);
writetable(PrimaryRecruitment,fullfile(outputFolder, ...
    'hc31_batch11P_TierAC_NREM_recruitment.csv'));

% Beta2 table.
betaMask = ...
    string(BetaAnimal.eventSet) == "TierAC" & ...
    string(BetaAnimal.movementGroup) == "SustainedImmobility";
PrimaryBeta = BetaAnimal(betaMask,:);
writetable(PrimaryBeta,fullfile(outputFolder, ...
    'hc31_batch11P_TierAC_sustained_beta2.csv'));

% Tier figure.
tierMask = startsWith(string(Tier.masterTier),"Tier") | ...
    startsWith(string(Tier.masterTier),"Review");
fig = figure('Visible','off','Color','w', ...
    'Position',[80 80 1200 720]);
bar(categorical(Tier.masterTier(tierMask)), ...
    Tier.nEvents(tierMask));
set(gca,'YScale','log');
ylabel('Number of events (log scale)');
title('Final Batch 11N+ candidate-event tiers');
xtickangle(30); grid on; box off
exportgraphics(fig,fullfile(figureFolder, ...
    'figure01_final_event_tiers.png'),'Resolution',200);
close(fig);

% Recruitment by animal.
animals = unique(PrimaryRecruitment.animal,'stable');
sleepEpochs = ["PRE","REST","POST"];
fig = figure('Visible','off','Color','w', ...
    'Position',[80 80 1100 700]);
hold on
for animalIndex = 1:numel(animals)
    values = nan(1,3);
    for epochIndex = 1:3
        mask = ...
            string(PrimaryRecruitment.animal) == animals(animalIndex) & ...
            string(PrimaryRecruitment.epoch) == sleepEpochs(epochIndex);
        if any(mask)
            values(epochIndex) = ...
                PrimaryRecruitment.centralMinusFlankRateHzPerUnit(find(mask,1));
        end
    end
    plot(1:3,values,'-o','LineWidth',1.1);
end
hold off
xlim([0.5 3.5]); xticks(1:3); xticklabels(cellstr(sleepEpochs));
yline(0,'k--');
ylabel('Central - flank rate (Hz/unit)');
title('Tier A+C NREM CA1 recruitment by animal');
grid on; box off
exportgraphics(fig,fullfile(figureFolder, ...
    'figure05_CA1_recruitment_by_animal.png'),'Resolution',200);
close(fig);

% CA1 PETH.
fig = figure('Visible','off','Color','w', ...
    'Position',[80 80 1100 700]);
hold on
for epochIndex = 1:3
    mask = ...
        string(Peth.eventSet) == "TierAC" & ...
        string(Peth.stateGroup) == "NREM" & ...
        string(Peth.epoch) == sleepEpochs(epochIndex);
    plot(Peth.timeFromEventSec(mask), ...
        Peth.meanEventPopulationRateHzPerUnit(mask), ...
        'LineWidth',1.5);
end
hold off
xline(0,'k--');
xlabel('Time from event peak (s)');
ylabel('Population spike rate (Hz/unit)');
title('Tier A+C NREM CA1 population PETH');
legend(cellstr(sleepEpochs),'Location','best');
grid on; box off
exportgraphics(fig,fullfile(figureFolder, ...
    'figure06_CA1_population_PETH.png'),'Resolution',200);
close(fig);

% Beta2 PETH.
betaPethMask = ...
    string(BetaPeth.eventSet) == "TierAC" & ...
    string(BetaPeth.movementGroup) == "SustainedImmobility";
fig = figure('Visible','off','Color','w', ...
    'Position',[80 80 1100 700]);
hold on
plot(BetaPeth.timeFromEventSec(betaPethMask), ...
    BetaPeth.meanEventBeta2EnvelopeZ(betaPethMask), ...
    'LineWidth',1.5);
plot(BetaPeth.timeFromEventSec(betaPethMask), ...
    BetaPeth.meanControlBeta2EnvelopeZ(betaPethMask), ...
    'LineWidth',1.5);
hold off
xline(0,'k--');
xlabel('Time from event or matched pseudo-time (s)');
ylabel('Local beta2 envelope robust z');
title('Tier A+C sustained-immobility beta2 coupling');
legend({'Event','Strict matched control'},'Location','best');
grid on; box off
exportgraphics(fig,fullfile(figureFolder, ...
    'figure07_beta2_event_control_PETH.png'),'Resolution',200);
close(fig);

fprintf('\nBatch 11P CSV synthesis complete.\n');
fprintf('Output folder:\n  %s\n',outputFolder);
