function F = hc31_batch11Nplus_extract_l2_features( ...
    cscFile, peakUs, detectorStartUs, detectorEndUs, settings)
% HC31_BATCH11N_EXTRACT_L2_FEATURES
% Extract the final Batch 11L2 parent-window LFP-only morphology features
% for one candidate event.
%
% This is a separate helper function so the main Batch 11N script remains a
% plain script that can be launched through fileread/eval.

F = struct();

F.featureComplete = false;
F.featureFailureReason = "";

F.effectiveSamplingRateHz = NaN;
F.refinedLocalPeakZ = NaN;
F.refinedMainPeakProminenceZ = NaN;
F.refinedMainPeakWidthMs = NaN;
F.refinedMainPeakOffsetMs = NaN;

F.nIndependentEnvelopePeaksZ2 = NaN;
F.nStrongEnvelopePeaksZ3 = NaN;
F.secondEnvelopePeakZ = NaN;
F.secondToFirstEnvelopePeakRatio = NaN;
F.nearestIndependentPeakSeparationMs = NaN;
F.minimumInterPeakValleyFraction = NaN;

F.refinedStartUs = NaN;
F.refinedEndUs = NaN;
F.refinedDurationS = NaN;
F.refinedBoundaryFoundBothSides = false;

F.splitRecommended = false;
F.nRecommendedChildEvents = 0;

F.spectralPeakHz120To250 = NaN;
F.spectralPeakProminenceDb = NaN;
F.spectralPeakToMedian80To300Db = NaN;
F.spectralPeakIsInterior = false;
F.spectralPeakAtBoundary = false;

F.ripplePower120To250 = NaN;
F.wideHighPower80To300 = NaN;
F.upperHighPower250To450 = NaN;
F.rippleFractionOf80To300 = NaN;
F.outsideRippleFraction80To450 = NaN;
F.rippleVsUpperHighDb = NaN;
F.spectralFlatness80To300 = NaN;

F.refinedRawPeakToPeak = NaN;
F.refinedSharpWavePeakAbs = NaN;
F.rawDerivativePeakRobustZ = NaN;
F.derivativeToEnvelopePeakOffsetMs = NaN;
F.rippleEnvelopeSymmetry = NaN;
F.rawToRipplePeakToPeakRatio = NaN;
F.filterRingingRiskIndex = NaN;
F.broadbandTransientIndex = NaN;

if exist(cscFile, 'file') ~= 2
    F.featureFailureReason = ...
        "CSC file does not exist: " + string(cscFile);
    return
end

loadStartUs = peakUs - ...
    settings.loadHalfWindowSec * 1e6;

loadEndUs = peakUs + ...
    settings.loadHalfWindowSec * 1e6;

try
    [recordTimestamps, samples, header] = Nlx2MatCSC( ...
        cscFile, ...
        [1 0 0 0 1], ...
        1, ...
        4, ...
        [loadStartUs loadEndUs]);
catch ME
    F.featureFailureReason = ...
        "Nlx2MatCSC failed: " + string(ME.message);
    return
end

if isempty(recordTimestamps) || isempty(samples)
    F.featureFailureReason = ...
        "CSC interval returned no samples.";
    return
end

recordTimestamps = double(recordTimestamps(:));
samples = double(samples);

recordDifferences = diff(recordTimestamps);
validDifferences = recordDifferences( ...
    isfinite(recordDifferences) & ...
    recordDifferences > 0);

if isempty(validDifferences)
    F.featureFailureReason = ...
        "Could not estimate CSC sampling frequency.";
    return
end

modeDifferenceUs = mode(round(validDifferences));
noSkip = abs(recordDifferences - modeDifferenceUs) <= 2;

if any(noSkip)
    rawFs = 1 / ...
        (mean(recordDifferences(noSkip)) / 512 / 1e6);
else
    rawFs = 1 / ...
        (median(validDifferences) / 512 / 1e6);
end

if ~isfinite(rawFs) || rawFs <= 0
    F.featureFailureReason = ...
        "Invalid CSC sampling frequency.";
    return
end

sampleVector = samples(:);

if all(noSkip)
    timeAllUs = linspace( ...
        recordTimestamps(1), ...
        recordTimestamps(end) + ...
        (511 / rawFs) * 1e6, ...
        numel(sampleVector))';

    lfpVector = sampleVector;
else
    timeGridUs = ( ...
        recordTimestamps(1): ...
        (1 / rawFs) * 1e6: ...
        (recordTimestamps(end) + ...
        (511 / rawFs) * 1e6))';

    valueGrid = nan(numel(timeGridUs),1);
    insertionPosition = 1;

    for recordIndex = 1:size(samples,2)
        while insertionPosition <= ...
                numel(timeGridUs) && ...
                abs(recordTimestamps(recordIndex) - ...
                timeGridUs(insertionPosition)) >= 2
            insertionPosition = insertionPosition + 1;
        end

        if insertionPosition + 511 <= numel(valueGrid)
            valueGrid( ...
                insertionPosition: ...
                insertionPosition+511) = ...
                samples(:,recordIndex);
        end

        insertionPosition = insertionPosition + 512;
    end

    timeAllUs = timeGridUs;
    lfpVector = valueGrid;
end

adBitVolts = 1;

for headerIndex = 1:numel(header)
    headerLine = string(header{headerIndex});

    if contains(headerLine, ...
            'ADBitVolts', ...
            'IgnoreCase', true)

        numericTokens = regexp( ...
            char(headerLine), ...
            '[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?', ...
            'match');

        if ~isempty(numericTokens)
            candidateScale = ...
                str2double(numericTokens{end});

            if isfinite(candidateScale) && ...
                    candidateScale > 0
                adBitVolts = candidateScale;
            end
        end
    end
end

lfpRawUv = lfpVector .* adBitVolts .* 1e6;
validRaw = isfinite(lfpRawUv);

if sum(validRaw) < round(0.5 * rawFs)
    F.featureFailureReason = ...
        "Too few valid LFP samples.";
    return
end

fillValue = median(lfpRawUv(validRaw), 'omitnan');
lfpFilled = lfpRawUv;
lfpFilled(~validRaw) = fillValue;

downsampleFactor = ...
    max(1, round(rawFs / settings.targetFs));

effectiveFs = rawFs / downsampleFactor;

if downsampleFactor > 1
    try
        lfpDs = decimate( ...
            lfpFilled, ...
            downsampleFactor);

        timeDsUs = linspace( ...
            timeAllUs(1), ...
            timeAllUs(end), ...
            numel(lfpDs))';

        validDs = interp1( ...
            timeAllUs, ...
            double(validRaw), ...
            timeDsUs, ...
            'nearest', ...
            0) > 0.5;
    catch
        lfpDs = ...
            lfpFilled(1:downsampleFactor:end);

        timeDsUs = ...
            timeAllUs(1:downsampleFactor:end);

        validDs = ...
            validRaw(1:downsampleFactor:end);
    end
else
    lfpDs = lfpFilled;
    timeDsUs = timeAllUs;
    validDs = validRaw;
end

nCommon = min([ ...
    numel(lfpDs), ...
    numel(timeDsUs), ...
    numel(validDs)]);

lfpDs = double(lfpDs(1:nCommon));
timeDsUs = double(timeDsUs(1:nCommon));
validDs = logical(validDs(1:nCommon));

nyquistHz = effectiveFs / 2;

if settings.rippleBandHz(2) >= nyquistHz || ...
        settings.wideHighBandHz(2) >= nyquistHz || ...
        settings.sharpWaveBandHz(2) >= nyquistHz
    F.featureFailureReason = ...
        "Downsampled Nyquist frequency is too low.";
    return
end

upperHighBandEffectiveHz = settings.upperHighBandHz;

if upperHighBandEffectiveHz(2) >= nyquistHz
    upperHighBandEffectiveHz(2) = ...
        floor(nyquistHz - 2);
end

try
    [bRipple, aRipple] = butter( ...
        settings.filterOrder, ...
        settings.rippleBandHz / nyquistHz, ...
        'bandpass');

    [bSharp, aSharp] = butter( ...
        settings.filterOrder, ...
        settings.sharpWaveBandHz / nyquistHz, ...
        'bandpass');

    rippleFiltered = ...
        filtfilt(bRipple, aRipple, lfpDs);

    sharpFiltered = ...
        filtfilt(bSharp, aSharp, lfpDs);
catch ME
    F.featureFailureReason = ...
        "Filtering failed: " + string(ME.message);
    return
end

relativeTimeSec = ...
    (timeDsUs - peakUs) / 1e6;

rippleEnvelope = ...
    abs(hilbert(rippleFiltered));

envelopeSmoothingSamples = ...
    max(1, round( ...
    settings.envelopeSmoothingSec * effectiveFs));

rippleEnvelope = movmean( ...
    rippleEnvelope, ...
    envelopeSmoothingSamples, ...
    'omitnan');

baselineMask = ...
    validDs & ...
    isfinite(rippleEnvelope) & ...
    abs(relativeTimeSec) >= ...
        settings.baselineExclusionHalfWindowSec;

if sum(baselineMask) < ...
        round(settings.minimumBaselineDurationSec * effectiveFs)
    baselineMask = ...
        validDs & ...
        isfinite(rippleEnvelope);
end

baselineValues = rippleEnvelope(baselineMask);

baselineMedian = ...
    median(baselineValues, 'omitnan');

baselineMad = median( ...
    abs(baselineValues - baselineMedian), ...
    'omitnan');

baselineSigma = 1.4826 * baselineMad;

if ~isfinite(baselineSigma) || ...
        baselineSigma <= 0
    baselineSigma = ...
        std(baselineValues, 'omitnan');
end

if ~isfinite(baselineSigma) || ...
        baselineSigma <= 0
    baselineSigma = 1;
end

envelopeZ = ...
    (rippleEnvelope - baselineMedian) ./ ...
    baselineSigma;

detectorStartTimeSec = ...
    (detectorStartUs - peakUs) / 1e6;

detectorEndTimeSec = ...
    (detectorEndUs - peakUs) / 1e6;

parentSearchStartSec = max( ...
    -settings.parentPeakMaximumHalfWindowSec, ...
    detectorStartTimeSec - ...
    settings.parentPeakPaddingSec);

parentSearchEndSec = min( ...
    settings.parentPeakMaximumHalfWindowSec, ...
    detectorEndTimeSec + ...
    settings.parentPeakPaddingSec);

if ~isfinite(parentSearchStartSec) || ...
        ~isfinite(parentSearchEndSec) || ...
        parentSearchEndSec - ...
        parentSearchStartSec < 0.020

    fallbackHalfWidthSec = max( ...
        0.030, ...
        min( ...
        settings.parentPeakMaximumHalfWindowSec, ...
        0.5 * max( ...
        detectorEndTimeSec - detectorStartTimeSec, ...
        0.040) + ...
        settings.parentPeakPaddingSec));

    parentSearchStartSec = -fallbackHalfWidthSec;
    parentSearchEndSec = fallbackHalfWidthSec;
end

analysisMask = ...
    relativeTimeSec >= parentSearchStartSec & ...
    relativeTimeSec <= parentSearchEndSec & ...
    isfinite(envelopeZ);

analysisRows = find(analysisMask);

if numel(analysisRows) < ...
        round(0.020 * effectiveFs)
    F.featureFailureReason = ...
        "Insufficient samples inside detector parent window.";
    return
end

analysisEnvelopeZ = ...
    envelopeZ(analysisRows);

analysisTimeSec = ...
    relativeTimeSec(analysisRows);

minimumPeakDistanceSamples = max( ...
    1, ...
    round(settings.peakMinimumDistanceSec * ...
    effectiveFs));

prominenceSearchHalfWindowSamples = max( ...
    3, ...
    round(settings.prominenceSearchHalfWindowSec * ...
    effectiveFs));

xPeak = analysisEnvelopeZ(:);
nPeakSamples = numel(xPeak);

candidatePeakLocations = find( ...
    xPeak(2:end-1) >= xPeak(1:end-2) & ...
    xPeak(2:end-1) > xPeak(3:end)) + 1;

if nPeakSamples >= 2
    if xPeak(1) > xPeak(2)
        candidatePeakLocations = [ ...
            1; candidatePeakLocations(:)];
    end

    if xPeak(end) >= xPeak(end-1)
        candidatePeakLocations = [ ...
            candidatePeakLocations(:); ...
            nPeakSamples];
    end
end

candidatePeakLocations = ...
    candidatePeakLocations( ...
    xPeak(candidatePeakLocations) >= ...
    settings.peakHeightZ);

candidatePeakValues = ...
    xPeak(candidatePeakLocations);

candidatePeakProminences = ...
    nan(size(candidatePeakValues));

candidatePeakWidths = ...
    nan(size(candidatePeakValues));

for peakCandidateIndex = ...
        1:numel(candidatePeakLocations)

    thisLocation = ...
        candidatePeakLocations(peakCandidateIndex);

    thisPeakValue = ...
        candidatePeakValues(peakCandidateIndex);

    leftSearchStart = max( ...
        1, ...
        thisLocation - ...
        prominenceSearchHalfWindowSamples);

    rightSearchEnd = min( ...
        nPeakSamples, ...
        thisLocation + ...
        prominenceSearchHalfWindowSamples);

    leftMinimum = min( ...
        xPeak(leftSearchStart:thisLocation), ...
        [], ...
        'omitnan');

    rightMinimum = min( ...
        xPeak(thisLocation:rightSearchEnd), ...
        [], ...
        'omitnan');

    localContour = max( ...
        leftMinimum, ...
        rightMinimum);

    thisProminence = ...
        thisPeakValue - localContour;

    candidatePeakProminences( ...
        peakCandidateIndex) = ...
        thisProminence;

    widthLevel = ...
        thisPeakValue - ...
        0.5 * max(thisProminence,0);

    leftWidthIndex = thisLocation;

    while leftWidthIndex > 1 && ...
            xPeak(leftWidthIndex) > widthLevel
        leftWidthIndex = leftWidthIndex - 1;
    end

    rightWidthIndex = thisLocation;

    while rightWidthIndex < nPeakSamples && ...
            xPeak(rightWidthIndex) > widthLevel
        rightWidthIndex = rightWidthIndex + 1;
    end

    candidatePeakWidths(peakCandidateIndex) = ...
        rightWidthIndex - leftWidthIndex;
end

prominenceKeep = ...
    candidatePeakProminences >= ...
    settings.peakProminenceZ;

candidatePeakLocations = ...
    candidatePeakLocations(prominenceKeep);

candidatePeakValues = ...
    candidatePeakValues(prominenceKeep);

candidatePeakProminences = ...
    candidatePeakProminences(prominenceKeep);

candidatePeakWidths = ...
    candidatePeakWidths(prominenceKeep);

selectedCandidateIndices = [];

if ~isempty(candidatePeakValues)
    [~, candidateAmplitudeOrder] = ...
        sort(candidatePeakValues, 'descend');

    for orderIndex = 1:numel(candidateAmplitudeOrder)
        candidateIndex = ...
            candidateAmplitudeOrder(orderIndex);

        candidateLocation = ...
            candidatePeakLocations(candidateIndex);

        if isempty(selectedCandidateIndices)
            selectedCandidateIndices = candidateIndex;
        else
            selectedLocations = ...
                candidatePeakLocations( ...
                selectedCandidateIndices);

            if all(abs( ...
                    selectedLocations - ...
                    candidateLocation) >= ...
                    minimumPeakDistanceSamples)

                selectedCandidateIndices( ...
                    end+1,1) = ...
                    candidateIndex; %#ok<AGROW>
            end
        end
    end
end

allPeakLocations = ...
    candidatePeakLocations( ...
    selectedCandidateIndices);

allPeakValues = ...
    candidatePeakValues( ...
    selectedCandidateIndices);

allPeakProminences = ...
    candidatePeakProminences( ...
    selectedCandidateIndices);

allPeakWidths = ...
    candidatePeakWidths( ...
    selectedCandidateIndices);

if isempty(allPeakValues)
    [maximumEnvelopeZ, maximumLocation] = ...
        max(analysisEnvelopeZ);

    allPeakValues = maximumEnvelopeZ;
    allPeakLocations = maximumLocation;

    leftMinimum = min( ...
        analysisEnvelopeZ(1:maximumLocation), ...
        [], ...
        'omitnan');

    rightMinimum = min( ...
        analysisEnvelopeZ(maximumLocation:end), ...
        [], ...
        'omitnan');

    fallbackContour = max( ...
        leftMinimum, ...
        rightMinimum);

    fallbackProminence = ...
        maximumEnvelopeZ - fallbackContour;

    allPeakProminences = fallbackProminence;

    widthLevel = ...
        maximumEnvelopeZ - ...
        0.5 * max(fallbackProminence,0);

    leftWidthIndex = maximumLocation;

    while leftWidthIndex > 1 && ...
            analysisEnvelopeZ(leftWidthIndex) > ...
            widthLevel
        leftWidthIndex = leftWidthIndex - 1;
    end

    rightWidthIndex = maximumLocation;

    while rightWidthIndex < ...
            numel(analysisEnvelopeZ) && ...
            analysisEnvelopeZ(rightWidthIndex) > ...
            widthLevel
        rightWidthIndex = rightWidthIndex + 1;
    end

    allPeakWidths = ...
        rightWidthIndex - leftWidthIndex;
end

allPeakTimesSec = ...
    analysisTimeSec(allPeakLocations);

[~, mainSelectionIndex] = ...
    min(abs(allPeakTimesSec));

mainPeakValue = ...
    allPeakValues(mainSelectionIndex);

mainPeakLocationInAnalysis = ...
    allPeakLocations(mainSelectionIndex);

mainPeakGlobalRow = ...
    analysisRows(mainPeakLocationInAnalysis);

mainPeakTimeSec = ...
    relativeTimeSec(mainPeakGlobalRow);

F.refinedLocalPeakZ = mainPeakValue;
F.refinedMainPeakOffsetMs = ...
    mainPeakTimeSec * 1000;

F.refinedMainPeakProminenceZ = ...
    allPeakProminences(mainSelectionIndex);

F.refinedMainPeakWidthMs = ...
    allPeakWidths(mainSelectionIndex) / ...
    effectiveFs * 1000;

F.nIndependentEnvelopePeaksZ2 = ...
    sum(allPeakValues >= settings.peakHeightZ);

strongMask = ...
    allPeakValues >= settings.strongPeakHeightZ & ...
    allPeakProminences >= ...
    settings.strongPeakProminenceZ;

F.nStrongEnvelopePeaksZ3 = ...
    sum(strongMask);

if numel(allPeakValues) >= 2
    otherPeakIndices = setdiff( ...
        (1:numel(allPeakValues))', ...
        mainSelectionIndex);

    F.secondEnvelopePeakZ = ...
        max(allPeakValues(otherPeakIndices));

    F.secondToFirstEnvelopePeakRatio = ...
        F.secondEnvelopePeakZ / ...
        max(mainPeakValue,eps);

    chronologicalPeakTimes = ...
        sort(allPeakTimesSec);

    F.nearestIndependentPeakSeparationMs = ...
        min(diff(chronologicalPeakTimes)) * 1000;

    valleyFractions = nan( ...
        numel(chronologicalPeakTimes)-1, 1);

    for peakIndex = ...
            1:numel(chronologicalPeakTimes)-1

        leftTime = ...
            chronologicalPeakTimes(peakIndex);

        rightTime = ...
            chronologicalPeakTimes(peakIndex+1);

        betweenMask = ...
            analysisTimeSec >= leftTime & ...
            analysisTimeSec <= rightTime;

        valleyValue = ...
            min(analysisEnvelopeZ(betweenMask), ...
            [], ...
            'omitnan');

        leftValue = max( ...
            analysisEnvelopeZ( ...
            abs(analysisTimeSec-leftTime) <= ...
            1/effectiveFs), ...
            [], ...
            'omitnan');

        rightValue = max( ...
            analysisEnvelopeZ( ...
            abs(analysisTimeSec-rightTime) <= ...
            1/effectiveFs), ...
            [], ...
            'omitnan');

        valleyFractions(peakIndex) = ...
            valleyValue / ...
            max(min(leftValue,rightValue),eps);
    end

    F.minimumInterPeakValleyFraction = ...
        min(valleyFractions,[], 'omitnan');
else
    F.secondEnvelopePeakZ = 0;
    F.secondToFirstEnvelopePeakRatio = 0;
end

leftAnalysisIndex = mainPeakLocationInAnalysis;
rightAnalysisIndex = mainPeakLocationInAnalysis;

while leftAnalysisIndex > 1 && ...
        analysisEnvelopeZ(leftAnalysisIndex) > ...
        settings.boundaryZ
    leftAnalysisIndex = leftAnalysisIndex - 1;
end

while rightAnalysisIndex < ...
        numel(analysisEnvelopeZ) && ...
        analysisEnvelopeZ(rightAnalysisIndex) > ...
        settings.boundaryZ
    rightAnalysisIndex = rightAnalysisIndex + 1;
end

leftBoundaryFound = ...
    leftAnalysisIndex > 1 || ...
    analysisEnvelopeZ(1) <= settings.boundaryZ;

rightBoundaryFound = ...
    rightAnalysisIndex < numel(analysisEnvelopeZ) || ...
    analysisEnvelopeZ(end) <= settings.boundaryZ;

F.refinedBoundaryFoundBothSides = ...
    leftBoundaryFound && rightBoundaryFound;

refinedStartTimeSec = ...
    analysisTimeSec(leftAnalysisIndex);

refinedEndTimeSec = ...
    analysisTimeSec(rightAnalysisIndex);

F.refinedStartUs = ...
    peakUs + refinedStartTimeSec * 1e6;

F.refinedEndUs = ...
    peakUs + refinedEndTimeSec * 1e6;

F.refinedDurationS = ...
    refinedEndTimeSec - refinedStartTimeSec;

if numel(allPeakValues) >= 2
    F.splitRecommended = ...
        F.secondToFirstEnvelopePeakRatio >= ...
        settings.splitSecondToFirstRatioMinimum && ...
        F.nearestIndependentPeakSeparationMs >= ...
        settings.minimumSplitSeparationSec * 1000;

    if isfinite(F.minimumInterPeakValleyFraction)
        F.splitRecommended = ...
            F.splitRecommended && ...
            F.minimumInterPeakValleyFraction <= ...
            settings.splitValleyFractionMaximum;
    end
end

if F.splitRecommended
    F.nRecommendedChildEvents = ...
        numel(allPeakValues);
end

spectralMask = ...
    abs(relativeTimeSec - mainPeakTimeSec) <= ...
    settings.spectralHalfWindowSec;

spectralRows = find(spectralMask);

if numel(spectralRows) >= 64
    spectralSignal = lfpDs(spectralRows);
    spectralSignal = spectralSignal - ...
        mean(spectralSignal,'omitnan');

    nfft = max(2048, ...
        2^nextpow2(numel(spectralSignal)));

    spectralWindow = hann(numel(spectralSignal));

    [powerSpectrum, frequencyHz] = pwelch( ...
        spectralSignal, ...
        spectralWindow, ...
        0, ...
        nfft, ...
        effectiveFs);

    spectrumDb = ...
        10*log10(powerSpectrum+eps);

    searchMask = ...
        frequencyHz >= settings.spectralPeakRangeHz(1) & ...
        frequencyHz <= settings.spectralPeakRangeHz(2);

    searchFrequency = frequencyHz(searchMask);
    searchDb = spectrumDb(searchMask);

    localMaxima = find( ...
        searchDb(2:end-1) >= searchDb(1:end-2) & ...
        searchDb(2:end-1) > searchDb(3:end)) + 1;

    if isempty(localMaxima)
        [selectedPeakDb, selectedIndex] = ...
            max(searchDb);

        selectedProminenceDb = ...
            selectedPeakDb - ...
            median(searchDb,'omitnan');
    else
        prominences = nan(numel(localMaxima),1);

        for peakIndex = 1:numel(localMaxima)
            loc = localMaxima(peakIndex);
            leftMin = min(searchDb(1:loc),[], 'omitnan');
            rightMin = min(searchDb(loc:end),[], 'omitnan');
            prominences(peakIndex) = ...
                searchDb(loc) - max(leftMin,rightMin);
        end

        [selectedProminenceDb, bestIndex] = ...
            max(prominences);

        selectedIndex = localMaxima(bestIndex);
        selectedPeakDb = searchDb(selectedIndex);
    end

    selectedPeakFrequency = ...
        searchFrequency(selectedIndex);

    F.spectralPeakHz120To250 = ...
        selectedPeakFrequency;

    F.spectralPeakProminenceDb = ...
        selectedProminenceDb;

    wideMask = ...
        frequencyHz >= settings.wideHighBandHz(1) & ...
        frequencyHz <= settings.wideHighBandHz(2);

    F.spectralPeakToMedian80To300Db = ...
        selectedPeakDb - ...
        median(spectrumDb(wideMask),'omitnan');

    F.spectralPeakAtBoundary = ...
        selectedPeakFrequency <= ...
        settings.spectralPeakRangeHz(1) + ...
        settings.spectralInteriorMarginHz || ...
        selectedPeakFrequency >= ...
        settings.spectralPeakRangeHz(2) - ...
        settings.spectralInteriorMarginHz;

    F.spectralPeakIsInterior = ...
        ~F.spectralPeakAtBoundary && ...
        selectedProminenceDb >= ...
        settings.spectralProminenceMinimumForInteriorFlagDb;

    rippleMask = ...
        frequencyHz >= settings.rippleBandHz(1) & ...
        frequencyHz <= settings.rippleBandHz(2);

    upperMask = ...
        frequencyHz >= upperHighBandEffectiveHz(1) & ...
        frequencyHz <= upperHighBandEffectiveHz(2);

    fullHighMask = ...
        frequencyHz >= settings.wideHighBandHz(1) & ...
        frequencyHz <= upperHighBandEffectiveHz(2);

    F.ripplePower120To250 = trapz( ...
        frequencyHz(rippleMask), ...
        powerSpectrum(rippleMask));

    F.wideHighPower80To300 = trapz( ...
        frequencyHz(wideMask), ...
        powerSpectrum(wideMask));

    F.upperHighPower250To450 = trapz( ...
        frequencyHz(upperMask), ...
        powerSpectrum(upperMask));

    if F.wideHighPower80To300 > 0
        F.rippleFractionOf80To300 = ...
            F.ripplePower120To250 / ...
            F.wideHighPower80To300;
    end

    fullHighPower = trapz( ...
        frequencyHz(fullHighMask), ...
        powerSpectrum(fullHighMask));

    if fullHighPower > 0
        F.outsideRippleFraction80To450 = ...
            max(0, fullHighPower - ...
            F.ripplePower120To250) / ...
            fullHighPower;
    end

    if F.upperHighPower250To450 > 0
        F.rippleVsUpperHighDb = ...
            10*log10( ...
            F.ripplePower120To250 / ...
            F.upperHighPower250To450);
    end

    positiveWide = ...
        powerSpectrum(wideMask);

    positiveWide = positiveWide( ...
        isfinite(positiveWide) & ...
        positiveWide > 0);

    if ~isempty(positiveWide)
        F.spectralFlatness80To300 = ...
            exp(mean(log(positiveWide))) / ...
            mean(positiveWide);
    end
end

sharpMask = ...
    abs(relativeTimeSec-mainPeakTimeSec) <= ...
    settings.sharpFeatureHalfWindowSec;

if any(sharpMask)
    localRaw = lfpDs(sharpMask);
    localSharp = sharpFiltered(sharpMask);
    localRipple = rippleFiltered(sharpMask);

    F.refinedRawPeakToPeak = ...
        max(localRaw)-min(localRaw);

    F.refinedSharpWavePeakAbs = ...
        max(abs(localSharp));

    ripplePeakToPeak = ...
        max(localRipple)-min(localRipple);

    F.rawToRipplePeakToPeakRatio = ...
        F.refinedRawPeakToPeak / ...
        max(ripplePeakToPeak,eps);

    rawDerivative = [0;diff(lfpDs)] .* ...
        effectiveFs;

    derivativeBaseline = ...
        rawDerivative(baselineMask);

    derivativeMedian = ...
        median(derivativeBaseline,'omitnan');

    derivativeMad = median( ...
        abs(derivativeBaseline-derivativeMedian), ...
        'omitnan');

    derivativeSigma = 1.4826*derivativeMad;

    if ~isfinite(derivativeSigma) || ...
            derivativeSigma <= 0
        derivativeSigma = ...
            std(derivativeBaseline,'omitnan');
    end

    if ~isfinite(derivativeSigma) || ...
            derivativeSigma <= 0
        derivativeSigma = 1;
    end

    derivativeRobustZ = abs( ...
        (rawDerivative-derivativeMedian) ./ ...
        derivativeSigma);

    localDerivativeZ = ...
        derivativeRobustZ(sharpMask);

    localSharpRows = find(sharpMask);

    [F.rawDerivativePeakRobustZ, ...
        derivativeLocalIndex] = ...
        max(localDerivativeZ);

    derivativeGlobalRow = ...
        localSharpRows(derivativeLocalIndex);

    derivativePeakTimeSec = ...
        relativeTimeSec(derivativeGlobalRow);

    F.derivativeToEnvelopePeakOffsetMs = ...
        abs(derivativePeakTimeSec-mainPeakTimeSec) * ...
        1000;

    symmetryHalfWindowSec = min( ...
        0.10, ...
        max(0.02,F.refinedDurationS));

    preMask = ...
        relativeTimeSec >= ...
        mainPeakTimeSec-symmetryHalfWindowSec & ...
        relativeTimeSec < mainPeakTimeSec;

    postMask = ...
        relativeTimeSec > mainPeakTimeSec & ...
        relativeTimeSec <= ...
        mainPeakTimeSec+symmetryHalfWindowSec;

    preArea = trapz( ...
        relativeTimeSec(preMask), ...
        rippleEnvelope(preMask));

    postArea = trapz( ...
        relativeTimeSec(postMask), ...
        rippleEnvelope(postMask));

    F.rippleEnvelopeSymmetry = ...
        1-abs(preArea-postArea) / ...
        max(preArea+postArea,eps);

    alignmentWeight = exp( ...
        -F.derivativeToEnvelopePeakOffsetMs / 15);

    F.filterRingingRiskIndex = ...
        F.rawDerivativePeakRobustZ * ...
        alignmentWeight * ...
        max(F.rippleEnvelopeSymmetry,0);

    if isfinite(F.outsideRippleFraction80To450)
        F.broadbandTransientIndex = ...
            F.rawDerivativePeakRobustZ * ...
            F.outsideRippleFraction80To450;
    else
        F.broadbandTransientIndex = ...
            F.rawDerivativePeakRobustZ;
    end
end

F.effectiveSamplingRateHz = effectiveFs;
F.featureComplete = true;
F.featureFailureReason = "";

end
