function CandidateTable = hc31_batch11Nplus_detect_candidates_in_epoch( ...
    cscFile, animalID, epochStartUs, epochEndUs, settings)
% HC31_BATCH11NPLUS_DETECT_CANDIDATES_IN_EPOCH
% Generate a deliberately permissive 120-250 Hz candidate set from one
% confirmed POST epoch.
%
% The broad detector is only a proposal generator. Final inclusion is decided
% later by Batch 11L2 morphology rules, state context and review metadata.

emptyVariables = { ...
    strings(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    false(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    zeros(0,1), ...
    strings(0,1)};

CandidateTable = table( ...
    emptyVariables{:}, ...
    'VariableNames', { ...
    'animal', ...
    'peakUs', ...
    'startUs', ...
    'endUs', ...
    'broadDetectorPeakZ', ...
    'broadDetectorProminenceZ', ...
    'broadDetectorDurationS', ...
    'broadDetectorArtifactFlag', ...
    'broadDetectorRawDerivativeZ', ...
    'broadDetectorRawPeakToPeakUv', ...
    'effectiveSamplingRateHz', ...
    'cscFile'});

if exist(cscFile,'file') ~= 2 || ...
        ~isfinite(epochStartUs) || ...
        ~isfinite(epochEndUs) || ...
        epochEndUs <= epochStartUs
    return
end

lastAcceptedPeakUs = -Inf;
chunkStartUs = epochStartUs;

while chunkStartUs < epochEndUs
    chunkEndUs = min( ...
        epochEndUs, ...
        chunkStartUs + settings.chunkLengthSec*1e6);

    loadStartUs = max( ...
        epochStartUs, ...
        chunkStartUs-settings.chunkPaddingSec*1e6);

    loadEndUs = min( ...
        epochEndUs, ...
        chunkEndUs+settings.chunkPaddingSec*1e6);

    try
        [recordTimestamps, sampleFrequencies, ...
            nValidSamples, samples, header] = ...
            Nlx2MatCSC( ...
            cscFile, ...
            [1 0 1 1 1], ...
            1, ...
            4, ...
            [loadStartUs loadEndUs]);
    catch
        chunkStartUs = chunkEndUs;
        continue
    end

    if isempty(recordTimestamps) || isempty(samples)
        chunkStartUs = chunkEndUs;
        continue
    end

    recordTimestamps = double(recordTimestamps(:));
    samples = double(samples);

    rawFs = median(double(sampleFrequencies(:)),'omitnan');

    if ~isfinite(rawFs) || rawFs <= 0
        recordDifferences = diff(recordTimestamps);
        recordDifferences = recordDifferences( ...
            isfinite(recordDifferences) & ...
            recordDifferences > 0);

        if isempty(recordDifferences)
            chunkStartUs = chunkEndUs;
            continue
        end

        rawFs = 1 / ...
            (median(recordDifferences) / 512 / 1e6);
    end

    adBitVolts = 1;

    for headerIndex = 1:numel(header)
        headerLine = string(header{headerIndex});

        if contains(headerLine,'ADBitVolts', ...
                'IgnoreCase',true)
            numericTokens = regexp( ...
                char(headerLine), ...
                '[-+]?\d*\.?\d+(?:[eE][-+]?\d+)?', ...
                'match');

            if ~isempty(numericTokens)
                candidateScale = ...
                    str2double(numericTokens{end});

                if isfinite(candidateScale) && candidateScale > 0
                    adBitVolts = candidateScale;
                end
            end
        end
    end

    rawTimeCells = cell(numel(recordTimestamps),1);
    rawLfpCells = cell(numel(recordTimestamps),1);
    dtUs = 1e6/rawFs;

    for recordIndex = 1:numel(recordTimestamps)
        validCount = 512;

        if ~isempty(nValidSamples)
            validCount = min( ...
                512, ...
                double(nValidSamples(recordIndex)));
        end

        if validCount <= 0
            continue
        end

        rawTimeCells{recordIndex} = ...
            double(recordTimestamps(recordIndex)) + ...
            (0:validCount-1)'*dtUs;

        rawLfpCells{recordIndex} = ...
            double(samples(1:validCount,recordIndex)) * ...
            adBitVolts * 1e6;
    end

    rawTimeUs = vertcat(rawTimeCells{:});
    rawLfpUv = vertcat(rawLfpCells{:});

    validMask = ...
        isfinite(rawTimeUs) & ...
        isfinite(rawLfpUv) & ...
        rawTimeUs >= loadStartUs & ...
        rawTimeUs <= loadEndUs;

    rawTimeUs = rawTimeUs(validMask);
    rawLfpUv = rawLfpUv(validMask);

    if numel(rawLfpUv) < rawFs
        chunkStartUs = chunkEndUs;
        continue
    end

    [rawTimeUs,sortOrder] = sort(rawTimeUs);
    rawLfpUv = rawLfpUv(sortOrder);

    [rawTimeUs,uniqueIndices] = unique(rawTimeUs,'stable');
    rawLfpUv = rawLfpUv(uniqueIndices);

    rawLfpUv = rawLfpUv - median(rawLfpUv,'omitnan');

    downsampleFactor = max( ...
        1, ...
        round(rawFs/settings.targetFs));

    effectiveFs = rawFs/downsampleFactor;

    if downsampleFactor > 1
        try
            lfpDs = decimate(rawLfpUv,downsampleFactor);
            timeDsUs = linspace( ...
                rawTimeUs(1), ...
                rawTimeUs(end), ...
                numel(lfpDs))';
        catch
            lfpDs = rawLfpUv(1:downsampleFactor:end);
            timeDsUs = rawTimeUs(1:downsampleFactor:end);
        end
    else
        lfpDs = rawLfpUv;
        timeDsUs = rawTimeUs;
    end

    nCommon = min(numel(lfpDs),numel(timeDsUs));
    lfpDs = double(lfpDs(1:nCommon));
    timeDsUs = double(timeDsUs(1:nCommon));

    nyquistHz = effectiveFs/2;

    if settings.rippleBandHz(2) >= nyquistHz
        chunkStartUs = chunkEndUs;
        continue
    end

    try
        [bRipple,aRipple] = butter( ...
            settings.filterOrder, ...
            settings.rippleBandHz/nyquistHz, ...
            'bandpass');

        rippleFiltered = filtfilt(bRipple,aRipple,lfpDs);
    catch
        chunkStartUs = chunkEndUs;
        continue
    end

    rippleEnvelope = abs(hilbert(rippleFiltered));

    smoothSamples = max( ...
        1, ...
        round(settings.envelopeSmoothingSec*effectiveFs));

    rippleEnvelope = movmean( ...
        rippleEnvelope, ...
        smoothSamples, ...
        'omitnan');

    baselineMedian = median(rippleEnvelope,'omitnan');
    baselineMad = median( ...
        abs(rippleEnvelope-baselineMedian), ...
        'omitnan');

    baselineSigma = 1.4826*baselineMad;

    if ~isfinite(baselineSigma) || baselineSigma <= 0
        baselineSigma = std(rippleEnvelope,'omitnan');
    end

    if ~isfinite(baselineSigma) || baselineSigma <= 0
        chunkStartUs = chunkEndUs;
        continue
    end

    envelopeZ = ...
        (rippleEnvelope-baselineMedian) ./ ...
        baselineSigma;

    candidateLocations = find( ...
        envelopeZ(2:end-1) >= envelopeZ(1:end-2) & ...
        envelopeZ(2:end-1) > envelopeZ(3:end)) + 1;

    candidateLocations = candidateLocations( ...
        envelopeZ(candidateLocations) >= ...
        settings.proposalPeakZMin);

    if isempty(candidateLocations)
        chunkStartUs = chunkEndUs;
        continue
    end

    candidateValues = envelopeZ(candidateLocations);
    candidateProminences = nan(size(candidateValues));

    prominenceHalfSamples = max( ...
        3, ...
        round(settings.prominenceSearchHalfWindowSec* ...
        effectiveFs));

    for peakIndex = 1:numel(candidateLocations)
        location = candidateLocations(peakIndex);

        leftStart = max( ...
            1, ...
            location-prominenceHalfSamples);

        rightEnd = min( ...
            numel(envelopeZ), ...
            location+prominenceHalfSamples);

        leftMinimum = min( ...
            envelopeZ(leftStart:location), ...
            [], ...
            'omitnan');

        rightMinimum = min( ...
            envelopeZ(location:rightEnd), ...
            [], ...
            'omitnan');

        candidateProminences(peakIndex) = ...
            candidateValues(peakIndex) - ...
            max(leftMinimum,rightMinimum);
    end

    keepProminence = ...
        candidateProminences >= ...
        settings.proposalProminenceZMin;

    candidateLocations = ...
        candidateLocations(keepProminence);

    candidateValues = ...
        candidateValues(keepProminence);

    candidateProminences = ...
        candidateProminences(keepProminence);

    if isempty(candidateLocations)
        chunkStartUs = chunkEndUs;
        continue
    end

    [~,amplitudeOrder] = sort(candidateValues,'descend');
    selectedIndices = [];
    minimumDistanceSamples = max( ...
        1, ...
        round(settings.proposalMinimumPeakDistanceSec* ...
        effectiveFs));

    for orderIndex = 1:numel(amplitudeOrder)
        candidateIndex = amplitudeOrder(orderIndex);
        location = candidateLocations(candidateIndex);

        if isempty(selectedIndices)
            selectedIndices = candidateIndex;
        else
            selectedLocations = ...
                candidateLocations(selectedIndices);

            if all(abs(selectedLocations-location) >= ...
                    minimumDistanceSamples)
                selectedIndices(end+1,1) = ...
                    candidateIndex; %#ok<AGROW>
            end
        end
    end

    selectedLocations = ...
        candidateLocations(selectedIndices);

    selectedValues = ...
        candidateValues(selectedIndices);

    selectedProminences = ...
        candidateProminences(selectedIndices);

    [selectedLocations,chronologicalOrder] = ...
        sort(selectedLocations);

    selectedValues = ...
        selectedValues(chronologicalOrder);

    selectedProminences = ...
        selectedProminences(chronologicalOrder);

    rawDerivative = [0;diff(lfpDs)]*effectiveFs;
    derivativeMedian = median(rawDerivative,'omitnan');
    derivativeMad = median( ...
        abs(rawDerivative-derivativeMedian), ...
        'omitnan');

    derivativeSigma = 1.4826*derivativeMad;

    if ~isfinite(derivativeSigma) || derivativeSigma <= 0
        derivativeSigma = std(rawDerivative,'omitnan');
    end

    if ~isfinite(derivativeSigma) || derivativeSigma <= 0
        derivativeSigma = 1;
    end

    derivativeZ = abs( ...
        (rawDerivative-derivativeMedian) ./ ...
        derivativeSigma);

    for peakIndex = 1:numel(selectedLocations)
        peakLocation = selectedLocations(peakIndex);
        peakTimestampUs = timeDsUs(peakLocation);

        % Only accept events whose peak lies inside the non-overlapping
        % central portion of the current chunk.
        if peakTimestampUs < chunkStartUs || ...
                peakTimestampUs >= chunkEndUs
            continue
        end

        if peakTimestampUs-lastAcceptedPeakUs < ...
                settings.globalRefractorySec*1e6
            continue
        end

        leftIndex = peakLocation;
        rightIndex = peakLocation;

        while leftIndex > 1 && ...
                envelopeZ(leftIndex) > ...
                settings.proposalBoundaryZ
            leftIndex = leftIndex-1;
        end

        while rightIndex < numel(envelopeZ) && ...
                envelopeZ(rightIndex) > ...
                settings.proposalBoundaryZ
            rightIndex = rightIndex+1;
        end

        eventStartUs = timeDsUs(leftIndex);
        eventEndUs = timeDsUs(rightIndex);
        eventDurationSec = ...
            (eventEndUs-eventStartUs)/1e6;

        if eventDurationSec < ...
                settings.proposalDurationMinSec || ...
                eventDurationSec > ...
                settings.proposalDurationMaxSec
            continue
        end

        contextMask = ...
            abs(timeDsUs-peakTimestampUs) <= ...
            settings.artifactContextHalfWindowSec*1e6;

        localDerivativeZ = max( ...
            derivativeZ(contextMask), ...
            [], ...
            'omitnan');

        localRawPeakToPeak = ...
            max(lfpDs(contextMask),[],'omitnan') - ...
            min(lfpDs(contextMask),[],'omitnan');

        artifactFlag = ...
            localDerivativeZ >= ...
                settings.broadArtifactDerivativeZ || ...
            localRawPeakToPeak >= ...
                settings.broadArtifactRawPeakToPeakUv;

        newRow = table( ...
            string(animalID), ...
            peakTimestampUs, ...
            eventStartUs, ...
            eventEndUs, ...
            selectedValues(peakIndex), ...
            selectedProminences(peakIndex), ...
            eventDurationSec, ...
            artifactFlag, ...
            localDerivativeZ, ...
            localRawPeakToPeak, ...
            effectiveFs, ...
            string(cscFile), ...
            'VariableNames', ...
            CandidateTable.Properties.VariableNames);

        CandidateTable = [CandidateTable;newRow]; %#ok<AGROW>
        lastAcceptedPeakUs = peakTimestampUs;
    end

    chunkStartUs = chunkEndUs;
end

end
