%% HC-31 Batch 11N+
% FINAL MASTER EVENT SET WITH POST SCREENING
%
% Plain script: no local functions.
%
% This batch:
% - assigns permanent event IDs;
% - extracts the final Batch 11L2 parent-window LFP-only morphology features
%   for every current PRE/REST candidate and optional Run1-awake candidate;
% - applies Conservative, Balanced, and Sensitive L2 rules;
% - preserves corrected Batch 11M3 state labels;
% - matches all first-review labels and focused second-review consensus labels;
% - creates strict reviewed, screened, review-required, and excluded tiers;
% - writes resumable MAT checkpoints.
%
% IMPORTANT
% ---------
% This is a tiered master candidate table, not a declaration that every
% retained event is a confirmed physiological sharp-wave ripple.
%
% POST candidates are supplied by the companion Batch 11N+ POST screening
% script. POST events remain screened candidates unless they later receive
% independent manual review.

clearvars -except scriptFile scriptFolder txt
clc
close all

fprintf('\nHC-31 Batch 11N+: final master event set\n');
fprintf('------------------------------------------\n');

%% Settings

defaultRoot = getenv('HC31_DATA_ROOT');

checkpointEveryNEvents = 100;
manualMatchToleranceUs = 2000;
duplicateToleranceUs = 1000;

settings = struct();

settings.targetFs = 1000;
settings.loadHalfWindowSec = 0.80;

settings.rippleBandHz = [120 250];
settings.wideHighBandHz = [80 300];
settings.upperHighBandHz = [250 450];
settings.sharpWaveBandHz = [1 30];

settings.filterOrder = 4;

settings.baselineExclusionHalfWindowSec = 0.30;
settings.minimumBaselineDurationSec = 0.30;

settings.peakHeightZ = 2.0;
settings.peakProminenceZ = 0.75;
settings.peakMinimumDistanceSec = 0.025;
settings.prominenceSearchHalfWindowSec = 0.080;

settings.strongPeakHeightZ = 3.0;
settings.strongPeakProminenceZ = 1.0;
settings.boundaryZ = 1.0;

settings.envelopeSmoothingSec = 0.010;
settings.parentPeakPaddingSec = 0.010;
settings.parentPeakMaximumHalfWindowSec = 0.150;

settings.minimumSplitSeparationSec = 0.025;
settings.splitSecondToFirstRatioMinimum = 0.50;
settings.splitValleyFractionMaximum = 0.60;

settings.spectralHalfWindowSec = 0.12;
settings.sharpFeatureHalfWindowSec = 0.12;

settings.spectralPeakRangeHz = [120 250];
settings.spectralInteriorMarginHz = 5;
settings.spectralProminenceMinimumForInteriorFlagDb = 1.0;

%% Add the script folder so the helper function is available

if exist('scriptFolder','var') && ...
        exist(scriptFolder,'dir') == 7
    addpath(scriptFolder);
else
    thisScriptPath = mfilename('fullpath');

    if ~isempty(thisScriptPath)
        addpath(fileparts(thisScriptPath));
    end
end

if exist('hc31_batch11Nplus_extract_l2_features','file') ~= 2
    error(['The helper function ', ...
        'hc31_batch11Nplus_extract_l2_features.m ', ...
        'must remain beside the main script.']);
end

%% Locate required files

if exist(defaultRoot,'dir') == 7
    rootDir = defaultRoot;
else
    rootDir = uigetdir(pwd, ...
        'Select the HC-31 root folder');

    if isequal(rootDir,0)
        error('No HC-31 root selected.');
    end
end

sleepStatePath = '';

searchCandidates = { ...
    fullfile(rootDir, ...
        'hc31_batch11M3_corrected_pre_rest_post_state_classification', ...
        'hc31_batch11M3_candidate_sleep_ripples_with_state.csv'), ...
    fullfile(rootDir, ...
        'hc31_batch11M3_candidate_sleep_ripples_with_state.csv')};

for q = 1:numel(searchCandidates)
    if exist(searchCandidates{q},'file') == 2
        sleepStatePath = searchCandidates{q};
        break
    end
end

if isempty(sleepStatePath)
    [f,p] = uigetfile('*.csv', ...
        ['Select ', ...
        'hc31_batch11M3_candidate_sleep_ripples_with_state.csv']);

    if isequal(f,0)
        error('No corrected state-annotated candidate table selected.');
    end

    sleepStatePath = fullfile(p,f);
end

epochInventoryPath = '';

inventoryCandidates = { ...
    fullfile(fileparts(sleepStatePath), ...
        'hc31_batch11M3_epoch_inventory.csv'), ...
    fullfile(rootDir, ...
        'hc31_batch11M3_corrected_pre_rest_post_state_classification', ...
        'hc31_batch11M3_epoch_inventory.csv')};

for q = 1:numel(inventoryCandidates)
    if exist(inventoryCandidates{q},'file') == 2
        epochInventoryPath = inventoryCandidates{q};
        break
    end
end

if isempty(epochInventoryPath)
    [f,p] = uigetfile('*.csv', ...
        'Select hc31_batch11M3_epoch_inventory.csv');

    if isequal(f,0)
        error('No corrected epoch inventory selected.');
    end

    epochInventoryPath = fullfile(p,f);
end

coveragePath = '';

coverageCandidates = { ...
    fullfile(fileparts(sleepStatePath), ...
        'hc31_batch11M3_csc_coverage.csv'), ...
    fullfile(rootDir, ...
        'hc31_batch11M3_corrected_pre_rest_post_state_classification', ...
        'hc31_batch11M3_csc_coverage.csv')};

for q = 1:numel(coverageCandidates)
    if exist(coverageCandidates{q},'file') == 2
        coveragePath = coverageCandidates{q};
        break
    end
end

if isempty(coveragePath)
    [f,p] = uigetfile('*.csv', ...
        'Select hc31_batch11M3_csc_coverage.csv');

    if isequal(f,0)
        error('No CSC coverage table selected.');
    end

    coveragePath = fullfile(p,f);
end

stateSummaryPath = fullfile( ...
    fileparts(sleepStatePath), ...
    'hc31_batch11M3_epoch_state_summary.csv');

if exist(stateSummaryPath,'file') ~= 2
    [f,p] = uigetfile('*.csv', ...
        'Select hc31_batch11M3_epoch_state_summary.csv');

    if isequal(f,0)
        error('No epoch-state summary selected.');
    end

    stateSummaryPath = fullfile(p,f);
end

rulesPath = '';

rulesCandidates = { ...
    fullfile(rootDir, ...
        'hc31_batch11K_candidate_ripple_manual_QC', ...
        'hc31_batch11L2_parent_window_peak_fix', ...
        'hc31_batch11L2_recommended_non_circular_rules.csv'), ...
    fullfile(rootDir, ...
        'hc31_batch11L2_recommended_non_circular_rules.csv')};

for q = 1:numel(rulesCandidates)
    if exist(rulesCandidates{q},'file') == 2
        rulesPath = rulesCandidates{q};
        break
    end
end

if isempty(rulesPath)
    [f,p] = uigetfile('*.csv', ...
        ['Select ', ...
        'hc31_batch11L2_recommended_non_circular_rules.csv']);

    if isequal(f,0)
        error('No Batch 11L2 rule table selected.');
    end

    rulesPath = fullfile(p,f);
end

reviewPath = '';

reviewCandidates = { ...
    fullfile(rootDir, ...
        'hc31_batch11K_candidate_ripple_manual_QC', ...
        'hc31_batch11K_UNBLINDED_MANUAL_REVIEWS.csv'), ...
    fullfile(rootDir, ...
        'hc31_batch11K_UNBLINDED_MANUAL_REVIEWS.csv')};

for q = 1:numel(reviewCandidates)
    if exist(reviewCandidates{q},'file') == 2
        reviewPath = reviewCandidates{q};
        break
    end
end

if isempty(reviewPath)
    [f,p] = uigetfile('*.csv', ...
        'Select hc31_batch11K_UNBLINDED_MANUAL_REVIEWS.csv');

    if isequal(f,0)
        error('No complete first-review table selected.');
    end

    reviewPath = fullfile(p,f);
end

consensusPath = '';

consensusCandidates = { ...
    fullfile(rootDir, ...
        'hc31_batch11L2_SECOND_REVIEW_CONSENSUS_LABELS.csv'), ...
    fullfile(fileparts(rulesPath), ...
        'hc31_batch11L2_SECOND_REVIEW_CONSENSUS_LABELS.csv')};

for q = 1:numel(consensusCandidates)
    if exist(consensusCandidates{q},'file') == 2
        consensusPath = consensusCandidates{q};
        break
    end
end

if isempty(consensusPath)
    [f,p] = uigetfile('*.csv', ...
        'Select hc31_batch11L2_SECOND_REVIEW_CONSENSUS_LABELS.csv');

    if isequal(f,0)
        error('No focused second-review consensus table selected.');
    end

    consensusPath = fullfile(p,f);
end

postScreenedPath = fullfile(rootDir, ...
    'hc31_batch11Nplus_post_screening', ...
    'hc31_batch11Nplus_POST_SCREENED_CANDIDATES.csv');

if exist(postScreenedPath,'file') ~= 2
    [f,p] = uigetfile('*.csv', ...
        ['Select ', ...
        'hc31_batch11Nplus_POST_SCREENED_CANDIDATES.csv']);

    if isequal(f,0)
        error(['POST screening is required. Run ', ...
            'hc31_batch11Nplus_generate_and_screen_POST_PLAIN_SCRIPT.m ', ...
            'to completion first.']);
    end

    postScreenedPath = fullfile(p,f);
end

%% Optional Run1-awake candidate table

awakePath = '';

awakeCandidates = { ...
    fullfile(rootDir, ...
        'hc31_batch9_candidate_awake_ripples.csv'), ...
    fullfile(rootDir, ...
        'hc31_batch9_awake_ripple_beta_timing_FORCE', ...
        'hc31_batch9_candidate_awake_ripples.csv'), ...
    fullfile(rootDir, ...
        'allresults', ...
        'hc31_batch9_awake_ripple_beta_timing_FORCE', ...
        'hc31_batch9_candidate_awake_ripples.csv')};

for q = 1:numel(awakeCandidates)
    if exist(awakeCandidates{q},'file') == 2
        awakePath = awakeCandidates{q};
        break
    end
end

if isempty(awakePath)
    awakeChoice = menu( ...
        'Include Run1-awake candidates in the master table?', ...
        'Select awake candidate CSV', ...
        'Skip awake candidates for this run');

    if awakeChoice == 1
        [f,p] = uigetfile('*.csv', ...
            ['Select the Batch 9 ', ...
            'candidate awake-ripple CSV']);

        if ~isequal(f,0)
            awakePath = fullfile(p,f);
        end
    end
end

%% Run mode

runMode = menu( ...
    'Batch 11N run mode', ...
    'Smoke test / resume: process 100 pending events', ...
    'Full / resume: process every pending event', ...
    'Finalise only from an existing complete checkpoint');

if runMode == 0
    error('No run mode selected.');
end

if runMode == 1
    maximumEventsThisInvocation = 100;
elseif runMode == 2
    maximumEventsThisInvocation = Inf;
else
    maximumEventsThisInvocation = 0;
end

%% Output folder

outputFolder = fullfile(rootDir, ...
    'hc31_batch11Nplus_final_master_event_set');

if ~exist(outputFolder,'dir')
    mkdir(outputFolder);
end

checkpointPath = fullfile(outputFolder, ...
    'hc31_batch11Nplus_feature_checkpoint.mat');

%% Read core tables

Sleep = readtable( ...
    sleepStatePath, ...
    'TextType','string', ...
    'VariableNamingRule','preserve');

Inventory = readtable( ...
    epochInventoryPath, ...
    'TextType','string', ...
    'VariableNamingRule','preserve');

Coverage = readtable( ...
    coveragePath, ...
    'TextType','string', ...
    'VariableNamingRule','preserve');

Rules = readtable( ...
    rulesPath, ...
    'TextType','string', ...
    'VariableNamingRule','preserve');

Review = readtable( ...
    reviewPath, ...
    'TextType','string', ...
    'VariableNamingRule','preserve');

Consensus = readtable( ...
    consensusPath, ...
    'TextType','string', ...
    'VariableNamingRule','preserve');

PostScreenedInput = readtable( ...
    postScreenedPath, ...
    'TextType','string', ...
    'VariableNamingRule','preserve');

EpochStateSummary = readtable( ...
    stateSummaryPath, ...
    'TextType','string', ...
    'VariableNamingRule','preserve');

requiredSleep = { ...
    'sourceRow','animal','epoch', ...
    'peakUs','startUs','endUs', ...
    'currentArtifactFlag', ...
    'operationalStateAtPeak', ...
    'thetaDeltaRobustZAtPeak', ...
    'thetaPowerRobustZAtPeak', ...
    'deltaPowerRobustZAtPeak', ...
    'highFrequencyRobustZAtPeak', ...
    'rawRmsRobustZAtPeak', ...
    'stateConfidenceScoreAtPeak'};

missingSleep = setdiff( ...
    requiredSleep, ...
    Sleep.Properties.VariableNames);

if ~isempty(missingSleep)
    error('State candidate table is missing: %s', ...
        strjoin(missingSleep,', '));
end

requiredInventory = { ...
    'animal','epoch','isUsable','cscPath'};

missingInventory = setdiff( ...
    requiredInventory, ...
    Inventory.Properties.VariableNames);

if ~isempty(missingInventory)
    error('Epoch inventory is missing: %s', ...
        strjoin(missingInventory,', '));
end

requiredRules = { ...
    'profile', ...
    'localPeakZMin', ...
    'refinedDurationMinS', ...
    'refinedDurationMaxS', ...
    'independentPeakCountMax', ...
    'secondToFirstPeakRatioMax', ...
    'spectralPeakProminenceMinDb', ...
    'interiorSpectralPeakRequired', ...
    'rippleFraction80To300Min', ...
    'outsideRippleFraction80To450Max', ...
    'rawDerivativeRobustZMax', ...
    'mainPeakCentreErrorMaxMs'};

missingRules = setdiff( ...
    requiredRules, ...
    Rules.Properties.VariableNames);

if ~isempty(missingRules)
    error('Rule table is missing: %s', ...
        strjoin(missingRules,', '));
end

%% Standardise the sleep candidate table

Candidates = table();

Candidates.sourceDataset = ...
    repmat("Batch10SleepStateAnnotated", ...
    height(Sleep),1);

Candidates.sourceRow = Sleep.sourceRow;
Candidates.animal = strtrim(string(Sleep.animal));
Candidates.epoch = upper(strtrim(string(Sleep.epoch)));
Candidates.peakUs = double(Sleep.peakUs);
Candidates.startUs = double(Sleep.startUs);
Candidates.endUs = double(Sleep.endUs);
Candidates.currentArtifactFlag = ...
    logical(Sleep.currentArtifactFlag);

Candidates.detectorPeakZ = nan(height(Sleep),1);
Candidates.peakSpeedCmS = nan(height(Sleep),1);

Candidates.operationalStateAtPeak = ...
    string(Sleep.operationalStateAtPeak);

Candidates.thetaDeltaRobustZAtPeak = ...
    double(Sleep.thetaDeltaRobustZAtPeak);

Candidates.thetaPowerRobustZAtPeak = ...
    double(Sleep.thetaPowerRobustZAtPeak);

Candidates.deltaPowerRobustZAtPeak = ...
    double(Sleep.deltaPowerRobustZAtPeak);

Candidates.highFrequencyRobustZAtPeak = ...
    double(Sleep.highFrequencyRobustZAtPeak);

Candidates.rawRmsRobustZAtPeak = ...
    double(Sleep.rawRmsRobustZAtPeak);

Candidates.stateConfidenceScoreAtPeak = ...
    double(Sleep.stateConfidenceScoreAtPeak);

Candidates.cscFile = ...
    repmat("",height(Sleep),1);

for rr = 1:height(Candidates)
    matchMask = ...
        strtrim(string(Inventory.animal)) == ...
            Candidates.animal(rr) & ...
        upper(strtrim(string(Inventory.epoch))) == ...
            Candidates.epoch(rr) & ...
        logical(Inventory.isUsable);

    if any(matchMask)
        selectedRow = find(matchMask,1);
        Candidates.cscFile(rr) = ...
            string(Inventory.cscPath(selectedRow));
    end
end

%% Append completed POST screened candidates

requiredPost = { ...
    'eventID','sourceRow','animal','epoch', ...
    'peakUs','startUs','endUs', ...
    'currentArtifactFlag', ...
    'operationalStateAtPeak', ...
    'thetaDeltaRobustZAtPeak', ...
    'thetaPowerRobustZAtPeak', ...
    'deltaPowerRobustZAtPeak', ...
    'highFrequencyRobustZAtPeak', ...
    'rawRmsRobustZAtPeak', ...
    'stateConfidenceScoreAtPeak', ...
    'cscFile', ...
    'featureComplete'};

missingPost = setdiff( ...
    requiredPost, ...
    PostScreenedInput.Properties.VariableNames);

if ~isempty(missingPost)
    error('POST screened table is missing: %s', ...
        strjoin(missingPost,', '));
end

PostCandidates = table();

PostCandidates.sourceDataset = ...
    repmat("Batch11NplusPOSTBroadDetector", ...
    height(PostScreenedInput),1);

PostCandidates.sourceRow = ...
    double(PostScreenedInput.sourceRow);

PostCandidates.animal = ...
    strtrim(string(PostScreenedInput.animal));

PostCandidates.epoch = ...
    repmat("POST",height(PostScreenedInput),1);

PostCandidates.peakUs = ...
    double(PostScreenedInput.peakUs);

PostCandidates.startUs = ...
    double(PostScreenedInput.startUs);

PostCandidates.endUs = ...
    double(PostScreenedInput.endUs);

PostCandidates.currentArtifactFlag = ...
    logical(PostScreenedInput.currentArtifactFlag);

PostCandidates.detectorPeakZ = ...
    double(PostScreenedInput.broadDetectorPeakZ);

PostCandidates.peakSpeedCmS = ...
    nan(height(PostScreenedInput),1);

PostCandidates.operationalStateAtPeak = ...
    string(PostScreenedInput.operationalStateAtPeak);

PostCandidates.thetaDeltaRobustZAtPeak = ...
    double(PostScreenedInput.thetaDeltaRobustZAtPeak);

PostCandidates.thetaPowerRobustZAtPeak = ...
    double(PostScreenedInput.thetaPowerRobustZAtPeak);

PostCandidates.deltaPowerRobustZAtPeak = ...
    double(PostScreenedInput.deltaPowerRobustZAtPeak);

PostCandidates.highFrequencyRobustZAtPeak = ...
    double(PostScreenedInput.highFrequencyRobustZAtPeak);

PostCandidates.rawRmsRobustZAtPeak = ...
    double(PostScreenedInput.rawRmsRobustZAtPeak);

PostCandidates.stateConfidenceScoreAtPeak = ...
    double(PostScreenedInput.stateConfidenceScoreAtPeak);

PostCandidates.cscFile = ...
    string(PostScreenedInput.cscFile);

Candidates = [Candidates;PostCandidates];

%% Optional awake candidate table

if ~isempty(awakePath)
    AwakeRaw = readtable( ...
        awakePath, ...
        'TextType','string', ...
        'VariableNamingRule','preserve');

    awakeNames = AwakeRaw.Properties.VariableNames;
    awakeLower = lower(awakeNames);

    animalColumn = '';
    epochColumn = '';
    peakColumn = '';
    startColumn = '';
    endColumn = '';
    artifactColumn = '';
    speedColumn = '';
    peakZColumn = '';

    candidateNames = {'animal','animalid','animal_id','rat','subject'};
    for q = 1:numel(candidateNames)
        hit = find(strcmp( ...
            awakeLower,lower(candidateNames{q})),1);
        if ~isempty(hit)
            animalColumn = awakeNames{hit};
            break
        end
    end

    candidateNames = {'epochname','epoch','epoch_name','session'};
    for q = 1:numel(candidateNames)
        hit = find(strcmp( ...
            awakeLower,lower(candidateNames{q})),1);
        if ~isempty(hit)
            epochColumn = awakeNames{hit};
            break
        end
    end

    candidateNames = { ...
        'peakus','ripplepeakus','eventpeakus', ...
        'peaktimeus','peak_time_us'};
    for q = 1:numel(candidateNames)
        hit = find(strcmp( ...
            awakeLower,lower(candidateNames{q})),1);
        if ~isempty(hit)
            peakColumn = awakeNames{hit};
            break
        end
    end

    candidateNames = { ...
        'startus','ripplestartus','eventstartus', ...
        'starttimeus','start_time_us'};
    for q = 1:numel(candidateNames)
        hit = find(strcmp( ...
            awakeLower,lower(candidateNames{q})),1);
        if ~isempty(hit)
            startColumn = awakeNames{hit};
            break
        end
    end

    candidateNames = { ...
        'endus','rippleendus','eventendus', ...
        'endtimeus','end_time_us'};
    for q = 1:numel(candidateNames)
        hit = find(strcmp( ...
            awakeLower,lower(candidateNames{q})),1);
        if ~isempty(hit)
            endColumn = awakeNames{hit};
            break
        end
    end

    candidateNames = { ...
        'isartifactlike','isartifact', ...
        'artifactlike','excludedasartifact'};
    for q = 1:numel(candidateNames)
        hit = find(strcmp( ...
            awakeLower,lower(candidateNames{q})),1);
        if ~isempty(hit)
            artifactColumn = awakeNames{hit};
            break
        end
    end

    candidateNames = { ...
        'peakspeedcms','speedcms','speedcmsec', ...
        'speed','peakspeed'};
    for q = 1:numel(candidateNames)
        hit = find(strcmp( ...
            awakeLower,lower(candidateNames{q})),1);
        if ~isempty(hit)
            speedColumn = awakeNames{hit};
            break
        end
    end

    candidateNames = { ...
        'peakz','peakenvz','peakzscore', ...
        'detectorpeakz'};
    for q = 1:numel(candidateNames)
        hit = find(strcmp( ...
            awakeLower,lower(candidateNames{q})),1);
        if ~isempty(hit)
            peakZColumn = awakeNames{hit};
            break
        end
    end

    if isempty(animalColumn) || isempty(peakColumn)
        warning(['Awake table was skipped because animal or ', ...
            'peak timestamp columns could not be identified.']);
    else
        Awake = table();

        Awake.sourceDataset = ...
            repmat("Batch9Run1Awake", ...
            height(AwakeRaw),1);

        Awake.sourceRow = (1:height(AwakeRaw))';
        Awake.animal = ...
            strtrim(string(AwakeRaw.(animalColumn)));

        Awake.epoch = ...
            repmat("RUN1AWAKE",height(AwakeRaw),1);

        if ~isempty(epochColumn)
            rawAwakeEpoch = ...
                upper(strtrim(string( ...
                AwakeRaw.(epochColumn))));

            Awake.epoch(contains( ...
                rawAwakeEpoch,'RUN1')) = ...
                "RUN1AWAKE";
        end

        Awake.peakUs = double(AwakeRaw.(peakColumn));

        if median(abs(Awake.peakUs),'omitnan') < 1e6
            Awake.peakUs = Awake.peakUs .* 1e6;
        end

        if ~isempty(startColumn)
            Awake.startUs = ...
                double(AwakeRaw.(startColumn));

            if median(abs(Awake.startUs),'omitnan') < 1e6
                Awake.startUs = Awake.startUs .* 1e6;
            end
        else
            Awake.startUs = Awake.peakUs - 0.050e6;
        end

        if ~isempty(endColumn)
            Awake.endUs = ...
                double(AwakeRaw.(endColumn));

            if median(abs(Awake.endUs),'omitnan') < 1e6
                Awake.endUs = Awake.endUs .* 1e6;
            end
        else
            Awake.endUs = Awake.peakUs + 0.050e6;
        end

        Awake.currentArtifactFlag = ...
            false(height(Awake),1);

        if ~isempty(artifactColumn)
            rawArtifact = ...
                AwakeRaw.(artifactColumn);

            if islogical(rawArtifact)
                Awake.currentArtifactFlag = ...
                    rawArtifact;
            elseif isnumeric(rawArtifact)
                Awake.currentArtifactFlag = ...
                    rawArtifact ~= 0;
            else
                rawArtifactString = ...
                    lower(strtrim(string(rawArtifact)));

                Awake.currentArtifactFlag = ...
                    rawArtifactString == "true" | ...
                    rawArtifactString == "1" | ...
                    rawArtifactString == "yes";
            end
        end

        Awake.detectorPeakZ = ...
            nan(height(Awake),1);

        if ~isempty(peakZColumn)
            Awake.detectorPeakZ = ...
                double(AwakeRaw.(peakZColumn));
        end

        Awake.peakSpeedCmS = ...
            nan(height(Awake),1);

        if ~isempty(speedColumn)
            Awake.peakSpeedCmS = ...
                double(AwakeRaw.(speedColumn));
        end

        Awake.operationalStateAtPeak = ...
            repmat("Run1 awake candidate context", ...
            height(Awake),1);

        Awake.thetaDeltaRobustZAtPeak = ...
            nan(height(Awake),1);
        Awake.thetaPowerRobustZAtPeak = ...
            nan(height(Awake),1);
        Awake.deltaPowerRobustZAtPeak = ...
            nan(height(Awake),1);
        Awake.highFrequencyRobustZAtPeak = ...
            nan(height(Awake),1);
        Awake.rawRmsRobustZAtPeak = ...
            nan(height(Awake),1);
        Awake.stateConfidenceScoreAtPeak = ...
            nan(height(Awake),1);

        Awake.cscFile = ...
            repmat("",height(Awake),1);

        Coverage.animal = ...
            strtrim(string(Coverage.animal));

        for rr = 1:height(Awake)
            coverageMask = ...
                Coverage.animal == Awake.animal(rr) & ...
                logical(Coverage.coverageReadable) & ...
                double(Coverage.coverageStartUs) <= ...
                    Awake.peakUs(rr) & ...
                double(Coverage.coverageEndUs) >= ...
                    Awake.peakUs(rr);

            if any(coverageMask)
                selectedRow = find(coverageMask,1);
                Awake.cscFile(rr) = ...
                    string(Coverage.cscPath(selectedRow));
            end
        end

        Awake = Awake( ...
            isfinite(Awake.peakUs),:);

        Candidates = [Candidates;Awake];
    end
end

%% Permanent event IDs and duplicate handling

Candidates.animal = ...
    strtrim(string(Candidates.animal));

Candidates.epoch = ...
    upper(strtrim(string(Candidates.epoch)));

Candidates.eventID = ...
    strings(height(Candidates),1);

for rr = 1:height(Candidates)
    Candidates.eventID(rr) = sprintf( ...
        'HC31_%s_%s_%013.0f', ...
        char(Candidates.animal(rr)), ...
        char(Candidates.epoch(rr)), ...
        Candidates.peakUs(rr));
end

Candidates = sortrows( ...
    Candidates, ...
    {'animal','epoch','peakUs'});

duplicateOfEventID = ...
    repmat("",height(Candidates),1);

isDuplicate = ...
    false(height(Candidates),1);

for rr = 2:height(Candidates)
    sameGroup = ...
        Candidates.animal(rr) == ...
            Candidates.animal(rr-1) & ...
        Candidates.epoch(rr) == ...
            Candidates.epoch(rr-1);

    if sameGroup && ...
            abs(Candidates.peakUs(rr) - ...
            Candidates.peakUs(rr-1)) <= ...
            duplicateToleranceUs

        isDuplicate(rr) = true;
        duplicateOfEventID(rr) = ...
            Candidates.eventID(rr-1);
    end
end

DuplicateReport = Candidates(isDuplicate,:);
DuplicateReport.duplicateOfEventID = ...
    duplicateOfEventID(isDuplicate);

writetable(DuplicateReport,fullfile(outputFolder, ...
    'hc31_batch11Nplus_duplicate_candidate_report.csv'));

Candidates = Candidates(~isDuplicate,:);

fprintf('Unique candidate events: %d\n', ...
    height(Candidates));

% POST features were already completed by the companion screening script.
% Preserve them and avoid a second raw-LFP extraction pass.
postFeatureLookup = PostScreenedInput;

%% Initialise or resume feature checkpoint

featureNames = { ...
    'featureComplete', ...
    'featureFailureReason', ...
    'effectiveSamplingRateHz', ...
    'refinedLocalPeakZ', ...
    'refinedMainPeakProminenceZ', ...
    'refinedMainPeakWidthMs', ...
    'refinedMainPeakOffsetMs', ...
    'nIndependentEnvelopePeaksZ2', ...
    'nStrongEnvelopePeaksZ3', ...
    'secondEnvelopePeakZ', ...
    'secondToFirstEnvelopePeakRatio', ...
    'nearestIndependentPeakSeparationMs', ...
    'minimumInterPeakValleyFraction', ...
    'refinedStartUs', ...
    'refinedEndUs', ...
    'refinedDurationS', ...
    'refinedBoundaryFoundBothSides', ...
    'splitRecommended', ...
    'nRecommendedChildEvents', ...
    'spectralPeakHz120To250', ...
    'spectralPeakProminenceDb', ...
    'spectralPeakToMedian80To300Db', ...
    'spectralPeakIsInterior', ...
    'spectralPeakAtBoundary', ...
    'ripplePower120To250', ...
    'wideHighPower80To300', ...
    'upperHighPower250To450', ...
    'rippleFractionOf80To300', ...
    'outsideRippleFraction80To450', ...
    'rippleVsUpperHighDb', ...
    'spectralFlatness80To300', ...
    'refinedRawPeakToPeak', ...
    'refinedSharpWavePeakAbs', ...
    'rawDerivativePeakRobustZ', ...
    'derivativeToEnvelopePeakOffsetMs', ...
    'rippleEnvelopeSymmetry', ...
    'rawToRipplePeakToPeakRatio', ...
    'filterRingingRiskIndex', ...
    'broadbandTransientIndex'};

if exist(checkpointPath,'file') == 2
    LoadedCheckpoint = load(checkpointPath);

    if ~isfield(LoadedCheckpoint,'FeatureTable')
        error('Checkpoint MAT does not contain FeatureTable.');
    end

    FeatureTable = LoadedCheckpoint.FeatureTable;

    if height(FeatureTable) ~= height(Candidates) || ...
            any(FeatureTable.eventID ~= Candidates.eventID)
        error(['The checkpoint event list does not match ', ...
            'the current candidate inputs.']);
    end

    fprintf('Resumed checkpoint: %d/%d complete.\n', ...
        sum(FeatureTable.featureComplete), ...
        height(FeatureTable));
else
    FeatureTable = table();
    FeatureTable.eventID = Candidates.eventID;

    FeatureTable.featureComplete = ...
        false(height(Candidates),1);

    FeatureTable.featureFailureReason = ...
        repmat("",height(Candidates),1);

    numericFeatureNames = setdiff( ...
        featureNames, ...
        { ...
        'featureComplete', ...
        'featureFailureReason', ...
        'refinedBoundaryFoundBothSides', ...
        'splitRecommended', ...
        'spectralPeakIsInterior', ...
        'spectralPeakAtBoundary'});

    for q = 1:numel(numericFeatureNames)
        FeatureTable.(numericFeatureNames{q}) = ...
            nan(height(Candidates),1);
    end

    FeatureTable.refinedBoundaryFoundBothSides = ...
        false(height(Candidates),1);

    FeatureTable.splitRecommended = ...
        false(height(Candidates),1);

    FeatureTable.spectralPeakIsInterior = ...
        false(height(Candidates),1);

    FeatureTable.spectralPeakAtBoundary = ...
        false(height(Candidates),1);

    save(checkpointPath,'FeatureTable','-v7.3');
end

% Pre-fill completed POST feature rows.
postFeatureNames = intersect( ...
    FeatureTable.Properties.VariableNames, ...
    postFeatureLookup.Properties.VariableNames, ...
    'stable');

for postIndex = 1:height(postFeatureLookup)
    eventMask = ...
        FeatureTable.eventID == ...
        string(postFeatureLookup.eventID(postIndex));

    if ~any(eventMask)
        continue
    end

    selectedRow = find(eventMask,1);

    for fieldIndex = 1:numel(postFeatureNames)
        fieldName = postFeatureNames{fieldIndex};

        if fieldName == "eventID"
            continue
        end

        FeatureTable.(fieldName)(selectedRow) = ...
            postFeatureLookup.(fieldName)(postIndex);
    end

    FeatureTable.featureComplete(selectedRow) = true;
end

save(checkpointPath,'FeatureTable','-v7.3');

%% Extract pending raw-LFP features

pendingRows = find(~FeatureTable.featureComplete);

if maximumEventsThisInvocation > 0 && ...
        ~isempty(pendingRows)

    nToProcess = min( ...
        numel(pendingRows), ...
        maximumEventsThisInvocation);

    processingRows = ...
        pendingRows(1:nToProcess);

    fprintf('Processing %d pending events this invocation.\n', ...
        numel(processingRows));

    for progressIndex = 1:numel(processingRows)
        rr = processingRows(progressIndex);

        if strlength(Candidates.cscFile(rr)) == 0
            FeatureTable.featureFailureReason(rr) = ...
                "No CSC file was assigned.";
            FeatureTable.featureComplete(rr) = true;
        else
            F = hc31_batch11Nplus_extract_l2_features( ...
                char(Candidates.cscFile(rr)), ...
                Candidates.peakUs(rr), ...
                Candidates.startUs(rr), ...
                Candidates.endUs(rr), ...
                settings);

            returnedFields = fieldnames(F);

            for fieldIndex = 1:numel(returnedFields)
                fieldName = returnedFields{fieldIndex};

                if ismember( ...
                        fieldName, ...
                        FeatureTable.Properties.VariableNames)

                    FeatureTable.(fieldName)(rr) = ...
                        F.(fieldName);
                end
            end

            % An extraction attempt is complete even when it produced a
            % failure reason. This prevents permanently retrying an
            % unreadable event on every resume.
            FeatureTable.featureComplete(rr) = true;
        end

        if mod(progressIndex,25) == 0 || ...
                progressIndex == numel(processingRows)
            fprintf('  %d/%d this invocation; total %d/%d complete\n', ...
                progressIndex, ...
                numel(processingRows), ...
                sum(FeatureTable.featureComplete), ...
                height(FeatureTable));
        end

        if mod(progressIndex, ...
                checkpointEveryNEvents) == 0 || ...
                progressIndex == numel(processingRows)
            save(checkpointPath, ...
                'FeatureTable', ...
                '-v7.3');
        end
    end
end

nComplete = sum(FeatureTable.featureComplete);
nTotal = height(FeatureTable);

Progress = table( ...
    nTotal, ...
    nComplete, ...
    nTotal-nComplete, ...
    100*nComplete/max(nTotal,1), ...
    'VariableNames', { ...
    'nTotalEvents', ...
    'nFeatureComplete', ...
    'nPending', ...
    'percentComplete'});

writetable(Progress,fullfile(outputFolder, ...
    'hc31_batch11Nplus_progress.csv'));

if nComplete < nTotal
    fprintf('\nBatch 11N checkpoint saved.\n');
    fprintf('%d of %d events are complete.\n', ...
        nComplete,nTotal);
    fprintf(['Rerun the main script and choose ', ...
        '"Full / resume" to continue.\n']);
else
    %% Apply L2 rules

    Master = [Candidates FeatureTable(:,2:end)];

    profileNames = string(Rules.profile);

    for profileIndex = 1:height(Rules)
        rule = Rules(profileIndex,:);

        rulePass = ...
            Master.featureComplete & ...
            Master.refinedLocalPeakZ >= ...
                rule.localPeakZMin & ...
            Master.refinedDurationS >= ...
                rule.refinedDurationMinS & ...
            Master.refinedDurationS <= ...
                rule.refinedDurationMaxS & ...
            Master.nIndependentEnvelopePeaksZ2 <= ...
                rule.independentPeakCountMax & ...
            Master.secondToFirstEnvelopePeakRatio <= ...
                rule.secondToFirstPeakRatioMax & ...
            Master.spectralPeakProminenceDb >= ...
                rule.spectralPeakProminenceMinDb & ...
            (rule.interiorSpectralPeakRequired == 0 | ...
                Master.spectralPeakIsInterior) & ...
            Master.rippleFractionOf80To300 >= ...
                rule.rippleFraction80To300Min & ...
            Master.outsideRippleFraction80To450 <= ...
                rule.outsideRippleFraction80To450Max & ...
            Master.rawDerivativePeakRobustZ <= ...
                rule.rawDerivativeRobustZMax & ...
            abs(Master.refinedMainPeakOffsetMs) <= ...
                rule.mainPeakCentreErrorMaxMs;

        outputColumn = ...
            "pass" + string(rule.profile) + "L2";

        outputColumn = ...
            matlab.lang.makeValidName( ...
            char(outputColumn));

        Master.(outputColumn) = rulePass;
    end

    if ~ismember('passBalancedL2', ...
            Master.Properties.VariableNames)
        error('Balanced L2 rule was not found.');
    end

    %% Match reviewed events

    Master.blindID = ...
        repmat("",height(Master),1);

    Master.firstReviewClassification = ...
        repmat("Not manually reviewed", ...
        height(Master),1);

    Master.firstReviewConfidence = ...
        repmat("",height(Master),1);

    Master.finalManualClassification = ...
        repmat("Not manually reviewed", ...
        height(Master),1);

    Master.finalManualConfidence = ...
        repmat("",height(Master),1);

    Master.manualReviewLevel = ...
        repmat("None",height(Master),1);

    Master.manualMatchDistanceUs = ...
        nan(height(Master),1);

    Review.animal = ...
        strtrim(string(Review.animal));

    Review.epoch = ...
        upper(strtrim(string(Review.epoch)));

    Review.epoch(Review.epoch == "RUN1AWAKE") = ...
        "RUN1AWAKE";

    matchedMasterRows = false(height(Master),1);

    for reviewIndex = 1:height(Review)
        candidateMask = ...
            Master.animal == Review.animal(reviewIndex) & ...
            Master.epoch == Review.epoch(reviewIndex);

        candidateRows = find(candidateMask);

        if isempty(candidateRows)
            continue
        end

        [minimumDistance, relativeIndex] = min( ...
            abs(Master.peakUs(candidateRows) - ...
            double(Review.peakUs(reviewIndex))));

        if minimumDistance <= manualMatchToleranceUs
            masterRow = candidateRows(relativeIndex);

            if matchedMasterRows(masterRow)
                continue
            end

            matchedMasterRows(masterRow) = true;

            Master.blindID(masterRow) = ...
                string(Review.blindID(reviewIndex));

            Master.firstReviewClassification(masterRow) = ...
                string(Review.primaryClassification(reviewIndex));

            Master.firstReviewConfidence(masterRow) = ...
                string(Review.confidence(reviewIndex));

            Master.finalManualClassification(masterRow) = ...
                string(Review.primaryClassification(reviewIndex));

            Master.finalManualConfidence(masterRow) = ...
                string(Review.confidence(reviewIndex));

            Master.manualReviewLevel(masterRow) = ...
                "First blinded review";

            Master.manualMatchDistanceUs(masterRow) = ...
                minimumDistance;
        end
    end

    for consensusIndex = 1:height(Consensus)
        masterMask = ...
            Master.blindID == ...
            string(Consensus.blindID(consensusIndex));

        if any(masterMask)
            Master.finalManualClassification(masterMask) = ...
                string( ...
                Consensus.consensusClassification( ...
                consensusIndex));

            Master.finalManualConfidence(masterMask) = ...
                string( ...
                Consensus.secondReviewConfidence( ...
                consensusIndex));

            Master.manualReviewLevel(masterMask) = ...
                "Focused LFP-only second review";
        end
    end

    %% State-use categories

    Master.stateUseGroup = ...
        repmat("Missing or unknown state", ...
        height(Master),1);

    nremMask = contains( ...
        Master.operationalStateAtPeak, ...
        "NREM", ...
        'IgnoreCase',true);

    thetaMask = contains( ...
        Master.operationalStateAtPeak, ...
        "Theta-dominant", ...
        'IgnoreCase',true);

    intermediateMask = contains( ...
        Master.operationalStateAtPeak, ...
        "Intermediate", ...
        'IgnoreCase',true);

    stateArtifactMask = contains( ...
        Master.operationalStateAtPeak, ...
        "Artefact", ...
        'IgnoreCase',true);

    awakeMask = ...
        Master.epoch == "RUN1AWAKE";

    awakeLowSpeedMask = ...
        awakeMask & ...
        isfinite(Master.peakSpeedCmS) & ...
        Master.peakSpeedCmS <= 5;

    awakeOtherMask = ...
        awakeMask & ...
        ~awakeLowSpeedMask;

    Master.stateUseGroup(nremMask) = ...
        "Sleep primary: low theta/delta slow-wave-compatible";

    Master.stateUseGroup(intermediateMask) = ...
        "Sleep secondary: intermediate";

    Master.stateUseGroup(thetaMask) = ...
        "Sleep separate: theta-dominant";

    Master.stateUseGroup(stateArtifactMask) = ...
        "Exclude: state artefact/unusable";

    Master.stateUseGroup(awakeLowSpeedMask) = ...
        "Awake primary: low speed";

    Master.stateUseGroup(awakeOtherMask) = ...
        "Awake secondary or unknown speed";

    %% Tier and eligibility rules

    manualLikely = ...
        Master.finalManualClassification == ...
        "Likely physiological ripple";

    manualAmbiguous = ...
        Master.finalManualClassification == ...
        "Ambiguous";

    manualClearNegative = ismember( ...
        Master.finalManualClassification, ...
        [ ...
        "Broadband artefact", ...
        "Filter ringing", ...
        "Multiple merged events", ...
        "Movement-related high-frequency activity"]);

    currentArtifact = ...
        logical(Master.currentArtifactFlag);

    featureFailure = ...
        strlength(Master.featureFailureReason) > 0;

    stateExcluded = stateArtifactMask;

    balancedPass = ...
        logical(Master.passBalancedL2);

    primaryState = ...
        nremMask | awakeLowSpeedMask;

    secondaryState = ...
        intermediateMask | ...
        thetaMask | ...
        awakeOtherMask;

    Master.strictReviewedEligible = ...
        manualLikely & ...
        ~currentArtifact & ...
        ~stateExcluded & ...
        ~featureFailure;

    Master.strictRuleConcordantEligible = ...
        manualLikely & ...
        balancedPass & ...
        ~currentArtifact & ...
        ~stateExcluded & ...
        ~featureFailure;

    Master.screenedAnalysisEligible = ...
        balancedPass & ...
        ~manualClearNegative & ...
        ~currentArtifact & ...
        ~stateExcluded & ...
        ~featureFailure;

    Master.masterTier = ...
        repmat("Excluded: Balanced L2 fail", ...
        height(Master),1);

    Master.exclusionReason = ...
        repmat("",height(Master),1);

    Master.masterTier(featureFailure) = ...
        "Excluded: feature extraction failure";

    Master.exclusionReason(featureFailure) = ...
        Master.featureFailureReason(featureFailure);

    Master.masterTier(currentArtifact) = ...
        "Excluded: original detector artefact flag";

    Master.exclusionReason(currentArtifact) = ...
        "Original candidate table marked the event as artefact-like";

    Master.masterTier(stateExcluded) = ...
        "Excluded: state artefact/unusable";

    Master.exclusionReason(stateExcluded) = ...
        "Batch 11M3 state window was artefact/unusable";

    Master.masterTier(manualClearNegative) = ...
        "Excluded: manual clear-negative classification";

    Master.exclusionReason(manualClearNegative) = ...
        Master.finalManualClassification( ...
        manualClearNegative);

    tierAMask = ...
        manualLikely & ...
        balancedPass & ...
        ~currentArtifact & ...
        ~stateExcluded & ...
        ~featureFailure;

    Master.masterTier(tierAMask) = ...
        "Tier A: reviewed likely + Balanced L2";

    tierBMask = ...
        manualLikely & ...
        ~balancedPass & ...
        ~currentArtifact & ...
        ~stateExcluded & ...
        ~featureFailure;

    Master.masterTier(tierBMask) = ...
        "Tier B: reviewed likely rule exception";

    tierCMask = ...
        ~manualLikely & ...
        ~manualClearNegative & ...
        balancedPass & ...
        primaryState & ...
        ~currentArtifact & ...
        ~stateExcluded & ...
        ~featureFailure;

    Master.masterTier(tierCMask) = ...
        "Tier C: Balanced L2 + primary state";

    tierDMask = ...
        ~manualLikely & ...
        ~manualClearNegative & ...
        balancedPass & ...
        secondaryState & ...
        ~currentArtifact & ...
        ~stateExcluded & ...
        ~featureFailure;

    Master.masterTier(tierDMask) = ...
        "Tier D: Balanced L2 + secondary state";

    reviewMask = ...
        manualAmbiguous & ...
        ~balancedPass & ...
        ~currentArtifact & ...
        ~stateExcluded & ...
        ~featureFailure;

    Master.masterTier(reviewMask) = ...
        "Review required: manual ambiguous + rule fail";

    %% Provenance

    Master.detectorSourceVersion = ...
        Master.sourceDataset;

    Master.featureVersion = ...
        repmat("Batch11L2ParentWindowPeakFix", ...
        height(Master),1);

    Master.ruleVersion = ...
        repmat("Batch11L2BalancedProvisional", ...
        height(Master),1);

    Master.stateVersion = ...
        repmat("Batch11M3_PRE1_REST3_POST4", ...
        height(Master),1);

    Master.manualReviewVersion = ...
        repmat("Batch11K_FirstPlusL2_FocusedSecond", ...
        height(Master),1);

    %% Output tables

    writetable(Master,fullfile(outputFolder, ...
        'hc31_batch11Nplus_MASTER_EVENT_TABLE.csv'));

    writetable(Master( ...
        Master.strictReviewedEligible,:), ...
        fullfile(outputFolder, ...
        'hc31_batch11Nplus_STRICT_REVIEWED_EVENTS.csv'));

    writetable(Master( ...
        Master.screenedAnalysisEligible,:), ...
        fullfile(outputFolder, ...
        'hc31_batch11Nplus_SCREENED_ELIGIBLE_EVENTS.csv'));

    excludedMask = startsWith( ...
        Master.masterTier, ...
        "Excluded");

    writetable(Master(excludedMask,:), ...
        fullfile(outputFolder, ...
        'hc31_batch11Nplus_EXCLUDED_EVENTS.csv'));

    reviewRequiredMask = contains( ...
        Master.masterTier, ...
        "Review required");

    writetable(Master(reviewRequiredMask,:), ...
        fullfile(outputFolder, ...
        'hc31_batch11Nplus_REVIEW_REQUIRED_EVENTS.csv'));

    writetable(FeatureTable,fullfile(outputFolder, ...
        'hc31_batch11Nplus_ALL_EVENT_L2_FEATURES.csv'));

    %% Summary tables

    [tierGroup,tierNames] = findgroups( ...
        Master.masterTier);

    tierCounts = splitapply(@numel, ...
        Master.eventID, ...
        tierGroup);

    TierSummary = table( ...
        tierNames, ...
        tierCounts, ...
        'VariableNames', { ...
        'masterTier','nEvents'});

    writetable(TierSummary,fullfile(outputFolder, ...
        'hc31_batch11Nplus_tier_summary.csv'));

    % With two grouping variables, findgroups returns the unique animal and
    % epoch labels as two separate outputs. They are not a two-column array.
    [epochGroup,epochAnimals,epochNames] = findgroups( ...
        Master.animal, ...
        Master.epoch);

    nCandidates = splitapply(@numel, ...
        Master.eventID, ...
        epochGroup);

    nBalanced = splitapply(@sum, ...
        double(Master.passBalancedL2), ...
        epochGroup);

    nStrict = splitapply(@sum, ...
        double(Master.strictReviewedEligible), ...
        epochGroup);

    nScreened = splitapply(@sum, ...
        double(Master.screenedAnalysisEligible), ...
        epochGroup);

    EpochSummary = table( ...
        epochAnimals, ...
        epochNames, ...
        nCandidates, ...
        nBalanced, ...
        nStrict, ...
        nScreened, ...
        'VariableNames', { ...
        'animal','epoch','nCandidates', ...
        'nBalancedL2','nStrictReviewed', ...
        'nScreenedEligible'});

    writetable(EpochSummary,fullfile(outputFolder, ...
        'hc31_batch11Nplus_animal_epoch_summary.csv'));

    %% Candidate rates before and after screening by state

    EpochStateSummary.animal = ...
        strtrim(string(EpochStateSummary.animal));

    EpochStateSummary.epoch = ...
        upper(strtrim(string(EpochStateSummary.epoch)));

    EpochStateSummary.operationalState = ...
        string(EpochStateSummary.operationalState);

    rateRows = {};

    for summaryIndex = 1:height(EpochStateSummary)
        animalID = EpochStateSummary.animal(summaryIndex);
        epochName = EpochStateSummary.epoch(summaryIndex);
        stateName = ...
            EpochStateSummary.operationalState(summaryIndex);

        durationMin = double( ...
            EpochStateSummary.stateDurationMin(summaryIndex));

        eventMask = ...
            Master.animal == animalID & ...
            Master.epoch == epochName & ...
            Master.operationalStateAtPeak == stateName;

        nAll = sum(eventMask);
        nBalanced = sum( ...
            eventMask & Master.passBalancedL2);
        nScreened = sum( ...
            eventMask & ...
            Master.screenedAnalysisEligible);
        nStrict = sum( ...
            eventMask & ...
            Master.strictReviewedEligible);

        allRate = NaN;
        balancedRate = NaN;
        screenedRate = NaN;
        strictRate = NaN;

        if durationMin > 0
            allRate = nAll/durationMin;
            balancedRate = nBalanced/durationMin;
            screenedRate = nScreened/durationMin;
            strictRate = nStrict/durationMin;
        end

        rateRows(end+1,:) = { ...
            char(animalID), ...
            char(epochName), ...
            char(stateName), ...
            durationMin, ...
            nAll, ...
            nBalanced, ...
            nScreened, ...
            nStrict, ...
            allRate, ...
            balancedRate, ...
            screenedRate, ...
            strictRate}; %#ok<SAGROW>
    end

    StateRateSummary = cell2table(rateRows, ...
        'VariableNames', { ...
        'animal', ...
        'epoch', ...
        'operationalState', ...
        'stateDurationMin', ...
        'nAllCandidates', ...
        'nBalancedL2', ...
        'nScreenedEligible', ...
        'nStrictReviewed', ...
        'allCandidateRatePerMinute', ...
        'balancedL2RatePerMinute', ...
        'screenedEligibleRatePerMinute', ...
        'strictReviewedRatePerMinute'});

    writetable(StateRateSummary,fullfile(outputFolder, ...
        'hc31_batch11Nplus_candidate_rate_by_state_before_after.csv'));

    % Preserve complete epoch coverage, including POST.
    Inventory.animal = strtrim(string(Inventory.animal));
    Inventory.epoch = upper(strtrim(string(Inventory.epoch)));

    Inventory.nMasterCandidates = ...
        zeros(height(Inventory),1);

    Inventory.candidateCoverageStatus = ...
        repmat("Candidate source not present", ...
        height(Inventory),1);

    for inventoryIndex = 1:height(Inventory)
        candidateMask = ...
            Master.animal == ...
                Inventory.animal(inventoryIndex) & ...
            Master.epoch == ...
                Inventory.epoch(inventoryIndex);

        Inventory.nMasterCandidates(inventoryIndex) = ...
            sum(candidateMask);

        if any(candidateMask)
            Inventory.candidateCoverageStatus( ...
                inventoryIndex) = ...
                "Candidate table processed";
        elseif Inventory.epoch(inventoryIndex) == "POST"
            Inventory.candidateCoverageStatus( ...
                inventoryIndex) = ...
                "POST screening expected but no event rows were found";
        end
    end

    writetable(Inventory,fullfile(outputFolder, ...
        'hc31_batch11Nplus_epoch_candidate_coverage.csv'));

    %% Simple figures

    fig = figure( ...
        'Visible','off', ...
        'Color','w', ...
        'Position',[100 100 1100 650]);

    bar(categorical(TierSummary.masterTier), ...
        TierSummary.nEvents);

    ylabel('Number of events');
    title('Batch 11N master-event tiers');
    xtickangle(25);
    grid on
    box off

    try
        exportgraphics(fig,fullfile(outputFolder, ...
            'batch11Nplus_master_tier_counts.png'), ...
            'Resolution',190);
    catch
        saveas(fig,fullfile(outputFolder, ...
            'batch11Nplus_master_tier_counts.png'));
    end

    close(fig);

    fig = figure( ...
        'Visible','off', ...
        'Color','w', ...
        'Position',[100 100 1050 650]);

    % EpochSummary contains one row per animal and epoch. Aggregate across
    % animals before using epoch labels as categorical X values.
    [epochPlotGroup,epochPlotNames] = findgroups( ...
        EpochSummary.epoch);

    epochPlotCandidates = splitapply(@sum, ...
        EpochSummary.nCandidates, ...
        epochPlotGroup);

    epochPlotBalanced = splitapply(@sum, ...
        EpochSummary.nBalancedL2, ...
        epochPlotGroup);

    epochCategories = categorical(epochPlotNames);

    bar(epochCategories, ...
        [epochPlotCandidates epochPlotBalanced], ...
        'grouped');

    ylabel('Events');
    title('Candidate counts before and after Balanced L2 screening');
    legend({'All candidates','Balanced L2'}, ...
        'Location','northoutside');
    grid on
    box off

    try
        exportgraphics(fig,fullfile(outputFolder, ...
            'batch11Nplus_candidate_counts_before_after_screening.png'), ...
            'Resolution',190);
    catch
        saveas(fig,fullfile(outputFolder, ...
            'batch11Nplus_candidate_counts_before_after_screening.png'));
    end

    close(fig);

    %% Text manifest

    fid = fopen(fullfile(outputFolder, ...
        'hc31_batch11Nplus_MASTER_MANIFEST.txt'),'w');

    if fid >= 0
        fprintf(fid,'HC-31 Batch 11N master manifest\n');
        fprintf(fid,'================================\n\n');

        fprintf(fid,'Sleep/state candidate table:\n%s\n\n', ...
            sleepStatePath);

        fprintf(fid,'Epoch inventory:\n%s\n\n', ...
            epochInventoryPath);

        fprintf(fid,'CSC coverage:\n%s\n\n', ...
            coveragePath);

        fprintf(fid,'L2 rules:\n%s\n\n',rulesPath);
        fprintf(fid,'First review:\n%s\n\n',reviewPath);
        fprintf(fid,'Second-review consensus:\n%s\n\n', ...
            consensusPath);

        fprintf(fid,'POST screened candidates:\n%s\n\n', ...
            postScreenedPath);

        if ~isempty(awakePath)
            fprintf(fid,'Awake candidate table:\n%s\n\n', ...
                awakePath);
        else
            fprintf(fid,'Awake candidate table: not included\n\n');
        end

        fprintf(fid,'Unique master candidates: %d\n', ...
            height(Master));
        fprintf(fid,'Feature failures: %d\n', ...
            sum(strlength( ...
            Master.featureFailureReason)>0));
        fprintf(fid,'Strict reviewed eligible: %d\n', ...
            sum(Master.strictReviewedEligible));
        fprintf(fid,'Screened eligible: %d\n\n', ...
            sum(Master.screenedAnalysisEligible));

        fprintf(fid,'Interpretation boundary\n');
        fprintf(fid,'-----------------------\n');
        fprintf(fid,[ ...
            'Tier A is the highest-confidence reviewed and ', ...
            'rule-concordant set.\n']);
        fprintf(fid,[ ...
            'Tier B preserves manual likely events that the ', ...
            'Balanced rule misses; use only in sensitivity ', ...
            'analyses.\n']);
        fprintf(fid,[ ...
            'Tiers C and D are provisional screened candidates, ', ...
            'not manually confirmed ripples.\n']);
        fprintf(fid,[ ...
            'POST candidates were generated by the companion ', ...
            'Batch 11N+ broad detector and screened with the ', ...
            'same final L2 morphology rules.\n']);

        fclose(fid);
    end

    fprintf('\nBatch 11N+ final master set complete.\n');
    fprintf('Output folder:\n  %s\n',outputFolder);
end
