%% HC-31 Batch 11N+ manual-review override correction
% Plain script: no local functions.
%
% Purpose
% -------
% Correct the final master tier logic so a final manual classification of
% "Likely physiological ripple" overrides the legacy currentArtifactFlag.
%
% This correction does NOT alter:
% - raw LFP features;
% - Balanced/Conservative/Sensitive rule outcomes;
% - state labels;
% - event IDs;
% - manual classifications.
%
% It only recalculates:
% - strictReviewedEligible;
% - strictRuleConcordantEligible;
% - screenedAnalysisEligible;
% - masterTier;
% - exclusionReason;
% - tier/epoch/state summaries and dependent output subsets.
%
% No raw data or checkpoint processing is required.

clear; clc; close all;

fprintf('\nHC-31 Batch 11N+ manual-review override correction\n');
fprintf('--------------------------------------------------\n');

%% Select completed master table

[masterFile, masterFolder] = uigetfile( ...
    '*.csv', ...
    'Select hc31_batch11Nplus_MASTER_EVENT_TABLE.csv');

if isequal(masterFile,0)
    error('No master event table selected.');
end

masterPath = fullfile(masterFolder,masterFile);

Master = readtable( ...
    masterPath, ...
    'TextType','string', ...
    'VariableNamingRule','preserve');

requiredColumns = { ...
    'eventID', ...
    'animal', ...
    'epoch', ...
    'operationalStateAtPeak', ...
    'currentArtifactFlag', ...
    'featureFailureReason', ...
    'passBalancedL2', ...
    'finalManualClassification', ...
    'manualReviewLevel', ...
    'stateUseGroup', ...
    'strictReviewedEligible', ...
    'strictRuleConcordantEligible', ...
    'screenedAnalysisEligible', ...
    'masterTier', ...
    'exclusionReason'};

missingColumns = setdiff( ...
    requiredColumns, ...
    Master.Properties.VariableNames);

if ~isempty(missingColumns)
    error('Master table is missing: %s', ...
        strjoin(missingColumns,', '));
end

%% Locate epoch-state duration table for corrected rate summary

defaultStateSummaryPath = fullfile( ...
    'C:\Users\angel\Documents\MATLAB\CRCN', ...
    'hc31_batch11M3_corrected_pre_rest_post_state_classification', ...
    'hc31_batch11M3_epoch_state_summary.csv');

stateSummaryPath = '';

if exist(defaultStateSummaryPath,'file') == 2
    stateSummaryPath = defaultStateSummaryPath;
else
    [stateFile,stateFolder] = uigetfile( ...
        '*.csv', ...
        'Select hc31_batch11M3_epoch_state_summary.csv');

    if ~isequal(stateFile,0)
        stateSummaryPath = ...
            fullfile(stateFolder,stateFile);
    end
end

%% Output folder

outputFolder = fullfile(masterFolder, ...
    'hc31_batch11Nplus_manual_review_override_corrected');

if ~exist(outputFolder,'dir')
    mkdir(outputFolder);
end

%% Preserve original fields for audit

Master.originalStrictReviewedEligible = ...
    logical(Master.strictReviewedEligible);

Master.originalStrictRuleConcordantEligible = ...
    logical(Master.strictRuleConcordantEligible);

Master.originalScreenedAnalysisEligible = ...
    logical(Master.screenedAnalysisEligible);

Master.originalMasterTier = ...
    string(Master.masterTier);

Master.originalExclusionReason = ...
    string(Master.exclusionReason);

Master.manualReviewOverridesOriginalArtifact = ...
    false(height(Master),1);

%% Recalculate eligibility and tiers

manualLikely = ...
    string(Master.finalManualClassification) == ...
    "Likely physiological ripple";

manualAmbiguous = ...
    string(Master.finalManualClassification) == ...
    "Ambiguous";

manualClearNegative = ismember( ...
    string(Master.finalManualClassification), ...
    [ ...
    "Broadband artefact", ...
    "Filter ringing", ...
    "Multiple merged events", ...
    "Movement-related high-frequency activity"]);

balancedPass = ...
    logical(Master.passBalancedL2);

currentArtifact = ...
    logical(Master.currentArtifactFlag);

featureFailure = ...
    strlength(string(Master.featureFailureReason)) > 0;

stateExcluded = contains( ...
    string(Master.operationalStateAtPeak), ...
    "Artefact", ...
    'IgnoreCase',true);

primaryState = contains( ...
    string(Master.stateUseGroup), ...
    "primary", ...
    'IgnoreCase',true);

secondaryState = contains( ...
    string(Master.stateUseGroup), ...
    "secondary", ...
    'IgnoreCase',true) | ...
    contains( ...
    string(Master.stateUseGroup), ...
    "separate", ...
    'IgnoreCase',true);

Master.manualReviewOverridesOriginalArtifact = ...
    manualLikely & currentArtifact;

% A completed manual likely classification supersedes the legacy automatic
% artefact flag. State artefact and feature failure still exclude the event.
Master.strictReviewedEligible = ...
    manualLikely & ...
    ~stateExcluded & ...
    ~featureFailure;

Master.strictRuleConcordantEligible = ...
    manualLikely & ...
    balancedPass & ...
    ~stateExcluded & ...
    ~featureFailure;

% For unreviewed events, preserve the original artefact exclusion.
% For manually likely events, allow human review to override it.
Master.screenedAnalysisEligible = ...
    balancedPass & ...
    ~manualClearNegative & ...
    (~currentArtifact | manualLikely) & ...
    ~stateExcluded & ...
    ~featureFailure;

Master.masterTier = ...
    repmat("Excluded: Balanced L2 fail", ...
    height(Master),1);

Master.exclusionReason = ...
    repmat("",height(Master),1);

Master.masterTier(featureFailure) = ...
    "Excluded: feature extraction failure";

Master.exclusionReason(featureFailure) = ...
    string(Master.featureFailureReason(featureFailure));

Master.masterTier(currentArtifact) = ...
    "Excluded: original detector artefact flag";

Master.exclusionReason(currentArtifact) = ...
    "Original candidate table marked the event as artefact-like";

Master.masterTier(stateExcluded) = ...
    "Excluded: state artefact/unusable";

Master.exclusionReason(stateExcluded) = ...
    "Batch 11M3 state window was artefact/unusable";

Master.masterTier(manualClearNegative) = ...
    "Excluded: manual clear-negative classification";

Master.exclusionReason(manualClearNegative) = ...
    string(Master.finalManualClassification( ...
    manualClearNegative));

% Manual likely tiers are assigned after automatic exclusions, intentionally
% overriding currentArtifactFlag but not state artefact or feature failure.
tierAMask = ...
    manualLikely & ...
    balancedPass & ...
    ~stateExcluded & ...
    ~featureFailure;

Master.masterTier(tierAMask) = ...
    "Tier A: reviewed likely + Balanced L2";

Master.exclusionReason(tierAMask) = "";

tierBMask = ...
    manualLikely & ...
    ~balancedPass & ...
    ~stateExcluded & ...
    ~featureFailure;

Master.masterTier(tierBMask) = ...
    "Tier B: reviewed likely rule exception";

Master.exclusionReason(tierBMask) = "";

tierCMask = ...
    ~manualLikely & ...
    ~manualClearNegative & ...
    balancedPass & ...
    primaryState & ...
    ~currentArtifact & ...
    ~stateExcluded & ...
    ~featureFailure;

Master.masterTier(tierCMask) = ...
    "Tier C: Balanced L2 + primary state";

tierDMask = ...
    ~manualLikely & ...
    ~manualClearNegative & ...
    balancedPass & ...
    secondaryState & ...
    ~currentArtifact & ...
    ~stateExcluded & ...
    ~featureFailure;

Master.masterTier(tierDMask) = ...
    "Tier D: Balanced L2 + secondary state";

reviewRequiredMask = ...
    manualAmbiguous & ...
    ~balancedPass & ...
    ~currentArtifact & ...
    ~stateExcluded & ...
    ~featureFailure;

Master.masterTier(reviewRequiredMask) = ...
    "Review required: manual ambiguous + rule fail";

%% Audit changed reviewed events

OverrideEvents = Master( ...
    Master.manualReviewOverridesOriginalArtifact,:);

overrideKeepColumns = intersect( ...
    { ...
    'eventID', ...
    'blindID', ...
    'animal', ...
    'epoch', ...
    'operationalStateAtPeak', ...
    'currentArtifactFlag', ...
    'passBalancedL2', ...
    'finalManualClassification', ...
    'finalManualConfidence', ...
    'manualReviewLevel', ...
    'originalMasterTier', ...
    'masterTier', ...
    'originalExclusionReason', ...
    'exclusionReason'}, ...
    OverrideEvents.Properties.VariableNames, ...
    'stable');

writetable( ...
    OverrideEvents(:,overrideKeepColumns), ...
    fullfile(outputFolder, ...
    'hc31_batch11Nplus_MANUAL_OVERRIDE_EVENTS.csv'));

%% Write corrected master and subsets

writetable(Master,fullfile(outputFolder, ...
    'hc31_batch11Nplus_MASTER_EVENT_TABLE_MANUAL_OVERRIDE_CORRECTED.csv'));

writetable(Master( ...
    Master.strictReviewedEligible,:), ...
    fullfile(outputFolder, ...
    'hc31_batch11Nplus_STRICT_REVIEWED_EVENTS_MANUAL_OVERRIDE_CORRECTED.csv'));

writetable(Master( ...
    Master.screenedAnalysisEligible,:), ...
    fullfile(outputFolder, ...
    'hc31_batch11Nplus_SCREENED_ELIGIBLE_EVENTS_MANUAL_OVERRIDE_CORRECTED.csv'));

excludedMask = startsWith( ...
    string(Master.masterTier), ...
    "Excluded");

writetable(Master(excludedMask,:), ...
    fullfile(outputFolder, ...
    'hc31_batch11Nplus_EXCLUDED_EVENTS_MANUAL_OVERRIDE_CORRECTED.csv'));

reviewRequiredMask = contains( ...
    string(Master.masterTier), ...
    "Review required");

writetable(Master(reviewRequiredMask,:), ...
    fullfile(outputFolder, ...
    'hc31_batch11Nplus_REVIEW_REQUIRED_EVENTS_MANUAL_OVERRIDE_CORRECTED.csv'));

%% Corrected tier summary

[tierGroup,tierNames] = findgroups( ...
    string(Master.masterTier));

tierCounts = splitapply(@numel, ...
    Master.eventID, ...
    tierGroup);

TierSummary = table( ...
    tierNames, ...
    tierCounts, ...
    'VariableNames', { ...
    'masterTier','nEvents'});

writetable(TierSummary,fullfile(outputFolder, ...
    'hc31_batch11Nplus_tier_summary_MANUAL_OVERRIDE_CORRECTED.csv'));

%% Corrected animal/epoch summary

[epochGroup,epochAnimals,epochNames] = findgroups( ...
    string(Master.animal), ...
    string(Master.epoch));

nCandidates = splitapply(@numel, ...
    Master.eventID, ...
    epochGroup);

nBalanced = splitapply(@sum, ...
    double(Master.passBalancedL2), ...
    epochGroup);

nStrict = splitapply(@sum, ...
    double(Master.strictReviewedEligible), ...
    epochGroup);

nScreened = splitapply(@sum, ...
    double(Master.screenedAnalysisEligible), ...
    epochGroup);

EpochSummary = table( ...
    epochAnimals, ...
    epochNames, ...
    nCandidates, ...
    nBalanced, ...
    nStrict, ...
    nScreened, ...
    'VariableNames', { ...
    'animal','epoch','nCandidates', ...
    'nBalancedL2','nStrictReviewed', ...
    'nScreenedEligible'});

writetable(EpochSummary,fullfile(outputFolder, ...
    'hc31_batch11Nplus_animal_epoch_summary_MANUAL_OVERRIDE_CORRECTED.csv'));

%% Corrected state-rate summary

if ~isempty(stateSummaryPath) && ...
        exist(stateSummaryPath,'file') == 2

    StateSummary = readtable( ...
        stateSummaryPath, ...
        'TextType','string', ...
        'VariableNamingRule','preserve');

    StateSummary.animal = ...
        strtrim(string(StateSummary.animal));

    StateSummary.epoch = ...
        upper(strtrim(string(StateSummary.epoch)));

    StateSummary.operationalState = ...
        string(StateSummary.operationalState);

    rateRows = {};

    for summaryIndex = 1:height(StateSummary)
        animalID = ...
            StateSummary.animal(summaryIndex);

        epochName = ...
            StateSummary.epoch(summaryIndex);

        stateName = ...
            StateSummary.operationalState(summaryIndex);

        durationMin = double( ...
            StateSummary.stateDurationMin(summaryIndex));

        eventMask = ...
            string(Master.animal) == animalID & ...
            string(Master.epoch) == epochName & ...
            string(Master.operationalStateAtPeak) == ...
                stateName;

        nAll = sum(eventMask);
        nBalanced = sum( ...
            eventMask & ...
            logical(Master.passBalancedL2));

        nScreened = sum( ...
            eventMask & ...
            logical(Master.screenedAnalysisEligible));

        nStrict = sum( ...
            eventMask & ...
            logical(Master.strictReviewedEligible));

        allRate = NaN;
        balancedRate = NaN;
        screenedRate = NaN;
        strictRate = NaN;

        if durationMin > 0
            allRate = nAll/durationMin;
            balancedRate = nBalanced/durationMin;
            screenedRate = nScreened/durationMin;
            strictRate = nStrict/durationMin;
        end

        rateRows(end+1,:) = { ...
            char(animalID), ...
            char(epochName), ...
            char(stateName), ...
            durationMin, ...
            nAll, ...
            nBalanced, ...
            nScreened, ...
            nStrict, ...
            allRate, ...
            balancedRate, ...
            screenedRate, ...
            strictRate}; %#ok<SAGROW>
    end

    StateRateSummary = cell2table( ...
        rateRows, ...
        'VariableNames', { ...
        'animal', ...
        'epoch', ...
        'operationalState', ...
        'stateDurationMin', ...
        'nAllCandidates', ...
        'nBalancedL2', ...
        'nScreenedEligible', ...
        'nStrictReviewed', ...
        'allCandidateRatePerMinute', ...
        'balancedL2RatePerMinute', ...
        'screenedEligibleRatePerMinute', ...
        'strictReviewedRatePerMinute'});

    writetable(StateRateSummary,fullfile(outputFolder, ...
        'hc31_batch11Nplus_candidate_rate_by_state_before_after_MANUAL_OVERRIDE_CORRECTED.csv'));
end

%% Correction summary

nOverride = sum( ...
    Master.manualReviewOverridesOriginalArtifact);

nStrict = sum(Master.strictReviewedEligible);
nRuleConcordant = sum( ...
    Master.strictRuleConcordantEligible);
nScreened = sum(Master.screenedAnalysisEligible);

fid = fopen(fullfile(outputFolder, ...
    'hc31_batch11Nplus_MANUAL_OVERRIDE_CORRECTION_SUMMARY.txt'),'w');

if fid >= 0
    fprintf(fid, ...
        'HC-31 Batch 11N+ manual-review override correction\n');
    fprintf(fid, ...
        '==================================================\n\n');

    fprintf(fid, ...
        'Events where manual likely review overrides legacy artefact flag: %d\n', ...
        nOverride);

    fprintf(fid, ...
        'Corrected strict reviewed eligible events: %d\n', ...
        nStrict);

    fprintf(fid, ...
        'Corrected strict rule-concordant events: %d\n', ...
        nRuleConcordant);

    fprintf(fid, ...
        'Corrected screened eligible events: %d\n\n', ...
        nScreened);

    fprintf(fid,'Corrected tier counts\n');
    fprintf(fid,'---------------------\n');

    for rowIndex = 1:height(TierSummary)
        fprintf(fid,'%s: %d\n', ...
            TierSummary.masterTier(rowIndex), ...
            TierSummary.nEvents(rowIndex));
    end

    fprintf(fid,'\nInterpretation\n');
    fprintf(fid,'--------------\n');
    fprintf(fid,[ ...
        'Manual likely labels now supersede currentArtifactFlag. ', ...
        'The original flag remains preserved as provenance and ', ...
        'continues to exclude unreviewed events.\n']);

    fclose(fid);
end

fprintf('\nCorrection complete.\n');
fprintf('Output folder:\n  %s\n',outputFolder);
fprintf('Manual likely artefact-flag overrides: %d\n',nOverride);
fprintf('Corrected strict reviewed eligible: %d\n',nStrict);
fprintf('Corrected screened eligible: %d\n',nScreened);
