%% HC-31 Batch 11N+
% POST CANDIDATE GENERATION AND BALANCED L2 SCREENING
%
% Plain script: no local functions.
%
% Stage 1 generates a deliberately permissive 120-250 Hz proposal set from
% confirmed POST column 4.
% Stage 2 annotates state context and applies the final Batch 11L2
% Conservative/Balanced/Sensitive morphology rules.
%
% The broad proposal detector is not a physiological ripple definition.

clearvars -except scriptFile scriptFolder txt
clc
close all

fprintf('\nHC-31 Batch 11N+: POST candidate screening\n');
fprintf('------------------------------------------\n');

%% Settings

defaultRoot = 'C:\Users\angel\Documents\MATLAB\CRCN';

settings = struct();

settings.chunkLengthSec = 120;
settings.chunkPaddingSec = 1.5;
settings.targetFs = 1000;
settings.rippleBandHz = [120 250];
settings.filterOrder = 4;
settings.envelopeSmoothingSec = 0.010;

% Broad proposal thresholds. These are intentionally more permissive than
% the final Balanced L2 morphology screen.
settings.proposalPeakZMin = 4.0;
settings.proposalProminenceZMin = 0.50;
settings.proposalBoundaryZ = 1.0;
settings.proposalMinimumPeakDistanceSec = 0.025;
settings.prominenceSearchHalfWindowSec = 0.080;
settings.proposalDurationMinSec = 0.015;
settings.proposalDurationMaxSec = 0.300;
settings.globalRefractorySec = 0.020;

settings.artifactContextHalfWindowSec = 0.050;
settings.broadArtifactDerivativeZ = 25;
settings.broadArtifactRawPeakToPeakUv = 5000;

% Final L2 feature settings.
settings.loadHalfWindowSec = 0.80;
settings.wideHighBandHz = [80 300];
settings.upperHighBandHz = [250 450];
settings.sharpWaveBandHz = [1 30];
settings.baselineExclusionHalfWindowSec = 0.30;
settings.minimumBaselineDurationSec = 0.30;
settings.peakHeightZ = 2.0;
settings.peakProminenceZ = 0.75;
settings.peakMinimumDistanceSec = 0.025;
settings.strongPeakHeightZ = 3.0;
settings.strongPeakProminenceZ = 1.0;
settings.boundaryZ = 1.0;
settings.parentPeakPaddingSec = 0.010;
settings.parentPeakMaximumHalfWindowSec = 0.150;
settings.minimumSplitSeparationSec = 0.025;
settings.splitSecondToFirstRatioMinimum = 0.50;
settings.splitValleyFractionMaximum = 0.60;
settings.spectralHalfWindowSec = 0.12;
settings.sharpFeatureHalfWindowSec = 0.12;
settings.spectralPeakRangeHz = [120 250];
settings.spectralInteriorMarginHz = 5;
settings.spectralProminenceMinimumForInteriorFlagDb = 1.0;

checkpointEveryNEvents = 100;
stateMatchMaximumDistanceSec = 2;

%% Add helper folder and Neuralynx importer

if exist('scriptFolder','var') && ...
        exist(scriptFolder,'dir') == 7
    addpath(scriptFolder);
else
    thisScriptPath = mfilename('fullpath');

    if ~isempty(thisScriptPath)
        scriptFolder = fileparts(thisScriptPath);
        addpath(scriptFolder);
    end
end

if exist('hc31_batch11Nplus_detect_candidates_in_epoch','file') ~= 2 || ...
        exist('hc31_batch11Nplus_extract_l2_features','file') ~= 2
    error(['Extract the complete Batch 11N+ ZIP and keep the ', ...
        'main script with both helper functions.']);
end

if exist(defaultRoot,'dir') == 7
    rootDir = defaultRoot;
else
    rootDir = uigetdir(pwd,'Select the HC-31 root folder');

    if isequal(rootDir,0)
        error('No root folder selected.');
    end
end

if exist(fullfile(rootDir,'neuralynximport'),'dir') == 7
    addpath(genpath(fullfile(rootDir,'neuralynximport')));
end

if exist(fullfile(rootDir, ...
        'neuralynximport','nlximport'),'dir') == 7
    addpath(genpath(fullfile(rootDir, ...
        'neuralynximport','nlximport')));
end

if exist('Nlx2MatCSC','file') ~= 2 && ...
        exist('Nlx2MatCSC','file') ~= 3
    error('MATLAB cannot find Nlx2MatCSC.');
end

%% Locate inputs

inventoryPath = fullfile(rootDir, ...
    'hc31_batch11M3_corrected_pre_rest_post_state_classification', ...
    'hc31_batch11M3_epoch_inventory.csv');

if exist(inventoryPath,'file') ~= 2
    [f,p] = uigetfile('*.csv', ...
        'Select hc31_batch11M3_epoch_inventory.csv');

    if isequal(f,0)
        error('No corrected epoch inventory selected.');
    end

    inventoryPath = fullfile(p,f);
end

stateWindowsPath = fullfile(rootDir, ...
    'hc31_batch11M3_corrected_pre_rest_post_state_classification', ...
    'hc31_batch11M3_state_windows.csv');

if exist(stateWindowsPath,'file') ~= 2
    [f,p] = uigetfile('*.csv', ...
        'Select hc31_batch11M3_state_windows.csv');

    if isequal(f,0)
        error('No corrected state-window table selected.');
    end

    stateWindowsPath = fullfile(p,f);
end

stateSummaryPath = fullfile(rootDir, ...
    'hc31_batch11M3_corrected_pre_rest_post_state_classification', ...
    'hc31_batch11M3_epoch_state_summary.csv');

if exist(stateSummaryPath,'file') ~= 2
    [f,p] = uigetfile('*.csv', ...
        'Select hc31_batch11M3_epoch_state_summary.csv');

    if isequal(f,0)
        error('No corrected epoch-state summary selected.');
    end

    stateSummaryPath = fullfile(p,f);
end

rulesPath = '';

ruleCandidates = { ...
    fullfile(rootDir, ...
        'hc31_batch11K_candidate_ripple_manual_QC', ...
        'hc31_batch11L2_parent_window_peak_fix', ...
        'hc31_batch11L2_recommended_non_circular_rules.csv'), ...
    fullfile(rootDir, ...
        'hc31_batch11L2_recommended_non_circular_rules.csv')};

for q = 1:numel(ruleCandidates)
    if exist(ruleCandidates{q},'file') == 2
        rulesPath = ruleCandidates{q};
        break
    end
end

if isempty(rulesPath)
    [f,p] = uigetfile('*.csv', ...
        'Select hc31_batch11L2_recommended_non_circular_rules.csv');

    if isequal(f,0)
        error('No final Batch 11L2 rule table selected.');
    end

    rulesPath = fullfile(p,f);
end

%% Output and run mode

outputFolder = fullfile(rootDir, ...
    'hc31_batch11Nplus_post_screening');

if ~exist(outputFolder,'dir')
    mkdir(outputFolder);
end

broadCandidatePath = fullfile(outputFolder, ...
    'hc31_batch11Nplus_POST_BROAD_CANDIDATES.csv');

detectionCheckpointPath = fullfile(outputFolder, ...
    'hc31_batch11Nplus_POST_detection_checkpoint.mat');

featureCheckpointPath = fullfile(outputFolder, ...
    'hc31_batch11Nplus_POST_feature_checkpoint.mat');

runMode = menu( ...
    'Batch 11N+ POST run mode', ...
    'Smoke test / resume: extract 100 pending L2 feature rows', ...
    'Full / resume: complete POST screening', ...
    'Finalise only from completed checkpoints');

if runMode == 0
    error('No run mode selected.');
end

if runMode == 1
    maximumFeaturesThisRun = 100;
elseif runMode == 2
    maximumFeaturesThisRun = Inf;
else
    maximumFeaturesThisRun = 0;
end

%% Read tables

Inventory = readtable( ...
    inventoryPath, ...
    'TextType','string', ...
    'VariableNamingRule','preserve');

StateWindows = readtable( ...
    stateWindowsPath, ...
    'TextType','string', ...
    'VariableNamingRule','preserve');

StateSummary = readtable( ...
    stateSummaryPath, ...
    'TextType','string', ...
    'VariableNamingRule','preserve');

Rules = readtable( ...
    rulesPath, ...
    'TextType','string', ...
    'VariableNamingRule','preserve');

Inventory.animal = strtrim(string(Inventory.animal));
Inventory.epoch = upper(strtrim(string(Inventory.epoch)));

StateWindows.animal = strtrim(string(StateWindows.animal));
StateWindows.epoch = upper(strtrim(string(StateWindows.epoch)));
StateWindows.operationalState = ...
    string(StateWindows.operationalState);

%% Stage 1: generate broad POST candidate proposals

if exist(detectionCheckpointPath,'file') == 2
    DetectionCheckpoint = load(detectionCheckpointPath);

    if isfield(DetectionCheckpoint,'PostBroadCandidates')
        PostBroadCandidates = ...
            DetectionCheckpoint.PostBroadCandidates;
    else
        PostBroadCandidates = table();
    end

    if isfield(DetectionCheckpoint,'completedAnimals')
        completedAnimals = ...
            DetectionCheckpoint.completedAnimals;
    else
        completedAnimals = strings(0,1);
    end
else
    PostBroadCandidates = table();
    completedAnimals = strings(0,1);
end

postInventory = Inventory( ...
    Inventory.epoch == "POST" & ...
    logical(Inventory.isUsable),:);

for inventoryIndex = 1:height(postInventory)
    animalID = postInventory.animal(inventoryIndex);

    if any(completedAnimals == animalID)
        continue
    end

    fprintf('\nGenerating POST proposals for %s...\n',animalID);

    thisCandidates = ...
        hc31_batch11Nplus_detect_candidates_in_epoch( ...
        char(postInventory.cscPath(inventoryIndex)), ...
        char(animalID), ...
        double(postInventory.epochStartUs(inventoryIndex)), ...
        double(postInventory.epochEndUs(inventoryIndex)), ...
        settings);

    if ~isempty(thisCandidates)
        PostBroadCandidates = [ ...
            PostBroadCandidates; ...
            thisCandidates]; %#ok<AGROW>
    end

    completedAnimals(end+1,1) = animalID; %#ok<SAGROW>

    save(detectionCheckpointPath, ...
        'PostBroadCandidates', ...
        'completedAnimals', ...
        '-v7.3');

    fprintf('  %d broad proposals generated.\n', ...
        height(thisCandidates));
end

if isempty(PostBroadCandidates)
    error('No POST proposals were generated.');
end

PostBroadCandidates = sortrows( ...
    PostBroadCandidates, ...
    {'animal','peakUs'});

PostBroadCandidates.sourceRow = ...
    (1:height(PostBroadCandidates))';

PostBroadCandidates.epoch = ...
    repmat("POST",height(PostBroadCandidates),1);

PostBroadCandidates.currentArtifactFlag = ...
    PostBroadCandidates.broadDetectorArtifactFlag;

PostBroadCandidates.eventID = ...
    strings(height(PostBroadCandidates),1);

for rr = 1:height(PostBroadCandidates)
    PostBroadCandidates.eventID(rr) = sprintf( ...
        'HC31_%s_POST_%013.0f', ...
        char(PostBroadCandidates.animal(rr)), ...
        PostBroadCandidates.peakUs(rr));
end

%% State annotation

PostBroadCandidates.operationalStateAtPeak = ...
    repmat("No matching state window", ...
    height(PostBroadCandidates),1);

PostBroadCandidates.stateWindowCenterUs = ...
    nan(height(PostBroadCandidates),1);

PostBroadCandidates.distanceToStateWindowSec = ...
    nan(height(PostBroadCandidates),1);

PostBroadCandidates.thetaDeltaRobustZAtPeak = ...
    nan(height(PostBroadCandidates),1);

PostBroadCandidates.thetaPowerRobustZAtPeak = ...
    nan(height(PostBroadCandidates),1);

PostBroadCandidates.deltaPowerRobustZAtPeak = ...
    nan(height(PostBroadCandidates),1);

PostBroadCandidates.highFrequencyRobustZAtPeak = ...
    nan(height(PostBroadCandidates),1);

PostBroadCandidates.rawRmsRobustZAtPeak = ...
    nan(height(PostBroadCandidates),1);

PostBroadCandidates.stateConfidenceScoreAtPeak = ...
    nan(height(PostBroadCandidates),1);

for rr = 1:height(PostBroadCandidates)
    stateMask = ...
        StateWindows.animal == ...
            PostBroadCandidates.animal(rr) & ...
        StateWindows.epoch == "POST";

    stateRows = find(stateMask);

    if isempty(stateRows)
        continue
    end

    [minimumDistanceUs,relativeIndex] = min( ...
        abs( ...
        double(StateWindows.windowCenterUs(stateRows)) - ...
        PostBroadCandidates.peakUs(rr)));

    selectedRow = stateRows(relativeIndex);
    distanceSec = minimumDistanceUs/1e6;

    PostBroadCandidates.distanceToStateWindowSec(rr) = ...
        distanceSec;

    if distanceSec <= stateMatchMaximumDistanceSec
        PostBroadCandidates.operationalStateAtPeak(rr) = ...
            StateWindows.operationalState(selectedRow);

        PostBroadCandidates.stateWindowCenterUs(rr) = ...
            double(StateWindows.windowCenterUs(selectedRow));

        PostBroadCandidates.thetaDeltaRobustZAtPeak(rr) = ...
            double(StateWindows.thetaDeltaRobustZ(selectedRow));

        PostBroadCandidates.thetaPowerRobustZAtPeak(rr) = ...
            double(StateWindows.thetaPowerRobustZ(selectedRow));

        PostBroadCandidates.deltaPowerRobustZAtPeak(rr) = ...
            double(StateWindows.deltaPowerRobustZ(selectedRow));

        PostBroadCandidates.highFrequencyRobustZAtPeak(rr) = ...
            double(StateWindows.highFrequencyRobustZ(selectedRow));

        PostBroadCandidates.rawRmsRobustZAtPeak(rr) = ...
            double(StateWindows.rawRmsRobustZ(selectedRow));

        PostBroadCandidates.stateConfidenceScoreAtPeak(rr) = ...
            double(StateWindows.stateConfidenceScore(selectedRow));
    end
end

writetable(PostBroadCandidates,broadCandidatePath);

%% Stage 2: final L2 features, checkpointed

featureVariableNames = { ...
    'featureComplete', ...
    'featureFailureReason', ...
    'effectiveSamplingRateHz', ...
    'refinedLocalPeakZ', ...
    'refinedMainPeakProminenceZ', ...
    'refinedMainPeakWidthMs', ...
    'refinedMainPeakOffsetMs', ...
    'nIndependentEnvelopePeaksZ2', ...
    'nStrongEnvelopePeaksZ3', ...
    'secondEnvelopePeakZ', ...
    'secondToFirstEnvelopePeakRatio', ...
    'nearestIndependentPeakSeparationMs', ...
    'minimumInterPeakValleyFraction', ...
    'refinedStartUs', ...
    'refinedEndUs', ...
    'refinedDurationS', ...
    'refinedBoundaryFoundBothSides', ...
    'splitRecommended', ...
    'nRecommendedChildEvents', ...
    'spectralPeakHz120To250', ...
    'spectralPeakProminenceDb', ...
    'spectralPeakToMedian80To300Db', ...
    'spectralPeakIsInterior', ...
    'spectralPeakAtBoundary', ...
    'ripplePower120To250', ...
    'wideHighPower80To300', ...
    'upperHighPower250To450', ...
    'rippleFractionOf80To300', ...
    'outsideRippleFraction80To450', ...
    'rippleVsUpperHighDb', ...
    'spectralFlatness80To300', ...
    'refinedRawPeakToPeak', ...
    'refinedSharpWavePeakAbs', ...
    'rawDerivativePeakRobustZ', ...
    'derivativeToEnvelopePeakOffsetMs', ...
    'rippleEnvelopeSymmetry', ...
    'rawToRipplePeakToPeakRatio', ...
    'filterRingingRiskIndex', ...
    'broadbandTransientIndex'};

if exist(featureCheckpointPath,'file') == 2
    LoadedFeatureCheckpoint = load(featureCheckpointPath);
    FeatureTable = LoadedFeatureCheckpoint.FeatureTable;

    if height(FeatureTable) ~= ...
            height(PostBroadCandidates) || ...
            any(FeatureTable.eventID ~= ...
            PostBroadCandidates.eventID)
        error('POST feature checkpoint does not match candidate table.');
    end
else
    FeatureTable = table();
    FeatureTable.eventID = PostBroadCandidates.eventID;
    FeatureTable.featureComplete = ...
        false(height(PostBroadCandidates),1);
    FeatureTable.featureFailureReason = ...
        repmat("",height(PostBroadCandidates),1);

    numericNames = setdiff( ...
        featureVariableNames, ...
        { ...
        'featureComplete', ...
        'featureFailureReason', ...
        'refinedBoundaryFoundBothSides', ...
        'splitRecommended', ...
        'spectralPeakIsInterior', ...
        'spectralPeakAtBoundary'});

    for q = 1:numel(numericNames)
        FeatureTable.(numericNames{q}) = ...
            nan(height(PostBroadCandidates),1);
    end

    FeatureTable.refinedBoundaryFoundBothSides = ...
        false(height(PostBroadCandidates),1);
    FeatureTable.splitRecommended = ...
        false(height(PostBroadCandidates),1);
    FeatureTable.spectralPeakIsInterior = ...
        false(height(PostBroadCandidates),1);
    FeatureTable.spectralPeakAtBoundary = ...
        false(height(PostBroadCandidates),1);
end

pendingRows = find(~FeatureTable.featureComplete);

if maximumFeaturesThisRun > 0 && ~isempty(pendingRows)
    nToProcess = min( ...
        numel(pendingRows), ...
        maximumFeaturesThisRun);

    processingRows = pendingRows(1:nToProcess);

    fprintf('\nExtracting final L2 features for %d POST proposals...\n', ...
        numel(processingRows));

    for progressIndex = 1:numel(processingRows)
        rr = processingRows(progressIndex);

        F = hc31_batch11Nplus_extract_l2_features( ...
            char(PostBroadCandidates.cscFile(rr)), ...
            PostBroadCandidates.peakUs(rr), ...
            PostBroadCandidates.startUs(rr), ...
            PostBroadCandidates.endUs(rr), ...
            settings);

        returnedFields = fieldnames(F);

        for fieldIndex = 1:numel(returnedFields)
            fieldName = returnedFields{fieldIndex};

            if ismember(fieldName, ...
                    FeatureTable.Properties.VariableNames)
                FeatureTable.(fieldName)(rr) = ...
                    F.(fieldName);
            end
        end

        FeatureTable.featureComplete(rr) = true;

        if mod(progressIndex,25) == 0 || ...
                progressIndex == numel(processingRows)
            fprintf('  %d/%d this invocation; total %d/%d complete\n', ...
                progressIndex, ...
                numel(processingRows), ...
                sum(FeatureTable.featureComplete), ...
                height(FeatureTable));
        end

        if mod(progressIndex,checkpointEveryNEvents) == 0 || ...
                progressIndex == numel(processingRows)
            save(featureCheckpointPath, ...
                'FeatureTable','-v7.3');
        end
    end
end

Progress = table( ...
    height(FeatureTable), ...
    sum(FeatureTable.featureComplete), ...
    sum(~FeatureTable.featureComplete), ...
    100*sum(FeatureTable.featureComplete)/ ...
        max(height(FeatureTable),1), ...
    'VariableNames', { ...
    'nPostBroadCandidates', ...
    'nFeatureComplete', ...
    'nPending', ...
    'percentComplete'});

writetable(Progress,fullfile(outputFolder, ...
    'hc31_batch11Nplus_POST_PROGRESS.csv'));

if any(~FeatureTable.featureComplete)
    fprintf('\nPOST checkpoint saved. Rerun and choose Full/resume.\n');
else
    % Preserve both sampling-rate fields with distinct names before
    % concatenating the broad-proposal table and final L2 feature table.
    if ismember('effectiveSamplingRateHz', ...
            PostBroadCandidates.Properties.VariableNames)
        PostBroadCandidates.broadDetectorSamplingRateHz = ...
            PostBroadCandidates.effectiveSamplingRateHz;

        PostBroadCandidates.effectiveSamplingRateHz = [];
    end

    PostScreened = [ ...
        PostBroadCandidates ...
        FeatureTable(:,2:end)];

    for profileIndex = 1:height(Rules)
        rule = Rules(profileIndex,:);

        rulePass = ...
            PostScreened.featureComplete & ...
            PostScreened.refinedLocalPeakZ >= ...
                rule.localPeakZMin & ...
            PostScreened.refinedDurationS >= ...
                rule.refinedDurationMinS & ...
            PostScreened.refinedDurationS <= ...
                rule.refinedDurationMaxS & ...
            PostScreened.nIndependentEnvelopePeaksZ2 <= ...
                rule.independentPeakCountMax & ...
            PostScreened.secondToFirstEnvelopePeakRatio <= ...
                rule.secondToFirstPeakRatioMax & ...
            PostScreened.spectralPeakProminenceDb >= ...
                rule.spectralPeakProminenceMinDb & ...
            (rule.interiorSpectralPeakRequired == 0 | ...
                PostScreened.spectralPeakIsInterior) & ...
            PostScreened.rippleFractionOf80To300 >= ...
                rule.rippleFraction80To300Min & ...
            PostScreened.outsideRippleFraction80To450 <= ...
                rule.outsideRippleFraction80To450Max & ...
            PostScreened.rawDerivativePeakRobustZ <= ...
                rule.rawDerivativeRobustZMax & ...
            abs(PostScreened.refinedMainPeakOffsetMs) <= ...
                rule.mainPeakCentreErrorMaxMs;

        outputColumn = matlab.lang.makeValidName( ...
            char("pass"+string(rule.profile)+"L2"));

        PostScreened.(outputColumn) = rulePass;
    end

    PostScreened.sourceDataset = ...
        repmat("Batch11NplusPOSTBroadDetector", ...
        height(PostScreened),1);

    PostScreened.detectorSourceVersion = ...
        repmat("POSTBroadZ4_Prom0p5_120to250Hz", ...
        height(PostScreened),1);

    PostScreened.featureVersion = ...
        repmat("Batch11L2ParentWindowPeakFix", ...
        height(PostScreened),1);

    PostScreened.ruleVersion = ...
        repmat("Batch11L2BalancedProvisional", ...
        height(PostScreened),1);

    PostScreened.stateVersion = ...
        repmat("Batch11M3_PRE1_REST3_POST4", ...
        height(PostScreened),1);

    writetable(PostScreened,fullfile(outputFolder, ...
        'hc31_batch11Nplus_POST_SCREENED_CANDIDATES.csv'));

    if ismember('passBalancedL2', ...
            PostScreened.Properties.VariableNames)
        writetable(PostScreened( ...
            PostScreened.passBalancedL2,:), ...
            fullfile(outputFolder, ...
            'hc31_batch11Nplus_POST_BALANCED_L2_EVENTS.csv'));
    end

    %% Candidate rates before and after screening

    stateNames = unique( ...
        string(StateSummary.operationalState), ...
        'stable');

    rateRows = {};

    for animalIndex = 1:height(postInventory)
        animalID = postInventory.animal(animalIndex);

        for stateIndex = 1:numel(stateNames)
            stateName = stateNames(stateIndex);

            durationMask = ...
                strtrim(string(StateSummary.animal)) == ...
                    animalID & ...
                upper(strtrim(string(StateSummary.epoch))) == ...
                    "POST" & ...
                string(StateSummary.operationalState) == ...
                    stateName;

            durationMin = 0;

            if any(durationMask)
                durationMin = sum( ...
                    double(StateSummary.stateDurationMin( ...
                    durationMask)), ...
                    'omitnan');
            end

            candidateMask = ...
                PostScreened.animal == animalID & ...
                PostScreened.operationalStateAtPeak == ...
                    stateName;

            nBroad = sum(candidateMask);
            nBalanced = sum( ...
                candidateMask & ...
                PostScreened.passBalancedL2);

            broadRate = NaN;
            balancedRate = NaN;

            if durationMin > 0
                broadRate = nBroad/durationMin;
                balancedRate = nBalanced/durationMin;
            end

            rateRows(end+1,:) = { ...
                char(animalID), ...
                char(stateName), ...
                durationMin, ...
                nBroad, ...
                nBalanced, ...
                broadRate, ...
                balancedRate}; %#ok<SAGROW>
        end
    end

    RateTable = cell2table(rateRows, ...
        'VariableNames', { ...
        'animal', ...
        'operationalState', ...
        'stateDurationMin', ...
        'nBroadCandidates', ...
        'nBalancedL2', ...
        'broadCandidateRatePerMinute', ...
        'balancedL2RatePerMinute'});

    writetable(RateTable,fullfile(outputFolder, ...
        'hc31_batch11Nplus_POST_RATE_BY_STATE.csv'));

    %% Summary

    % No event-level categorical bar plot is created here. MATLAB requires
    % unique categorical X values, whereas PostScreened contains repeated
    % animal labels for many events.

    Summary = table( ...
        height(PostScreened), ...
        sum(PostScreened.passBalancedL2), ...
        sum(PostScreened.currentArtifactFlag), ...
        sum(strlength( ...
        PostScreened.featureFailureReason)>0), ...
        'VariableNames', { ...
        'nBroadPostCandidates', ...
        'nBalancedL2PostEvents', ...
        'nBroadArtifactFlags', ...
        'nFeatureFailures'});

    writetable(Summary,fullfile(outputFolder, ...
        'hc31_batch11Nplus_POST_SCREENING_SUMMARY.csv'));

    fid = fopen(fullfile(outputFolder, ...
        'hc31_batch11Nplus_POST_SCREENING_MANIFEST.txt'),'w');

    if fid >= 0
        fprintf(fid,'HC-31 Batch 11N+ POST screening\n');
        fprintf(fid,'================================\n\n');
        fprintf(fid,'Broad POST proposals: %d\n', ...
            height(PostScreened));
        fprintf(fid,'Balanced L2 POST events: %d\n', ...
            sum(PostScreened.passBalancedL2));
        fprintf(fid,'Feature failures: %d\n\n', ...
            sum(strlength( ...
            PostScreened.featureFailureReason)>0));
        fprintf(fid,[ ...
            'The broad detector is a permissive proposal ', ...
            'generator. Balanced L2 events are screened ', ...
            'candidates, not manually confirmed ripples.\n']);
        fclose(fid);
    end

    fprintf('\nPOST screening complete.\n');
    fprintf('Output folder:\n  %s\n',outputFolder);
end
